### ISSUE TITLE
Modus Button - Add a Badge for Notification Icon button

### ISSUE THREAD

**Issue by anamarquezz** [trimble-oss/modus-web-components#1011]
As part of a new webApp at Trimble we are using modus, but we enconter more new cool things that we wish modus have, 
for example now, the ui show us a button with an icon is possible request for this in modus?

would be cool to add the icon property and also set the position of the icon,
for example:

![image](https://user-images.githubusercontent.com/12877909/217389169-6705e367-3e63-4765-9108-b57d2349ea63.png)

And we actually have more request on the way , for example a property to add the number in the notifications as show in the image 

Thank you so much, for the replies, 😄

**Comment by msankaran0712** [comment]
@msankaran0712 add more details

**Comment by msankaran0712** [comment]
@msankaran0712 check with @anamarquezz

**Comment by msankaran0712** [comment]
This is to reaffirm that Modus has approved the functionality for the development of the icon with the text button. 
Note: Modus team assign a `modus-approved` tag to the approved issues 

cc @anamarquezz 

However, we need some details for Notification Icon with the Number button.

- What is the colour of the number
- What is the size of the number
- Mention it in the Modus Style guide and Figma
cc @soniakaukonen @egunther39

**Comment by msankaran0712** [comment]
@soniakaukonen @egunther39 any updates?

**Comment by egunther39** [comment]
@msankaran0712 - The notification icon with a number is really just a Counter Badge overlayed on the icon button but I assume you'll need to build as part of the button. That being the case. Those badges are 20 x 20 and the font size 12px/Bold.

For color - we offer the colors below but if we had to pick just one color I'd say  red #da212c

![image](https://github.com/trimble-oss/modus-web-components/assets/98049598/d647f0bf-ce15-4987-a64c-d68b28d5f71e)

**Comment by msankaran0712** [comment]
@anamarquezz are you willing to contribute this one?

**Comment by cjwinsor** [comment]
We discussed and decided to allow the notification icon to have a badge for a count, styling controlled by the modus component.

@anamarquezz Do you have an active use case in the product you work on that needs this feature?  Can you share how it works today with a screenshot?

**Comment by cjwinsor** [comment]
Initially this will be a red badge only.

**Comment by ElishaSamPeterPrabhu** [comment]
With modus badge 


![Image](https://github.com/trimble-oss/modus-web-components/assets/122255626/d94c51f2-3ce4-4888-936e-9bdfb1b9e73e)
![Image](https://github.com/trimble-oss/modus-web-components/assets/122255626/ca597580-9e76-439f-a5c3-df9e79a60c4b)
