### ISSUE TITLE
placement and header of the notifications menu

### ISSUE THREAD

**Issue by rubie9816** [trimble-oss/modus-web-components#1012]
Hi, I am working with Modus in Angular, and I'm trying to insert my own component for the notifications menu, but there is a static header that is not possible to remove.
It would be nice if the header for the notifications menu was optional or editable.

![image](https://user-images.githubusercontent.com/49250842/217391431-ca1428ce-71c2-4d34-8963-f7cd138c822d.png)

Also, as required by the UX design of my project, it would be great if the menu can be displayed on the right side of the screen as well:
![image](https://user-images.githubusercontent.com/49250842/217392215-a4d592b4-5d88-46b4-ad3f-090c953914fe.png)

Similar to the side navigation component.

Thanks :)

**Comment by msankaran0712** [comment]
hi@rubie9816, we will be able to fix the static header in the notifications pop-up and regarding displaying the menu on the right side, we believe it is a use case and it could be achieved by a Side panel component (not Modus Side Navigation).

**Comment by rubie9816** [comment]
Thanks for your answer, 
I have tried activating the notificationsMenuOpen event, but as the name suggests, it only detects the "open" action but not the close one, so if I want to hide the side panel I have no way to detect that action (maybe a Click event ?)
I also can't find a way to "hide" the default notification menu.
It would be great if you could give me an example of how to implement our own component (side panel) instead of the default notification menu  component (pop-up menu).
<img width="208" alt="image" src="https://user-images.githubusercontent.com/49250842/233716950-90e0074f-71d4-45e4-a9b9-1199aa0fe144.png">

**Comment by msankaran0712** [comment]
This is to reaffirm that Modus has approved the functionality for development.

cc @rubie9816 

Note: Modus team tag the approved issues with `modus-approved`

**Comment by cjwinsor** [comment]
Team Notes: We can proceed with the removal of the Notification Header.  We will need to split the ticket for the second request.

As for the side panel/utility panel, how much of a priority is this @rubie9816?
