### ISSUE TITLE
Example for Breadcrumb component

### ISSUE THREAD

**Issue by rubie9816** [trimble-oss/modus-web-components#1015]
Hi, I'm trying to implement the Breadcrumb component but I'm unable to redirect the app to the specified path. 
Here's the code:

TS:

![image](https://user-images.githubusercontent.com/49250842/219458604-b507982c-a39b-40f0-a80e-6c2d8046f795.png)

HTML:

`<modus-breadcrumb [crumbs]="crumbs" (crumbClick)="crumbClick($event)"></modus-breadcrumb>
`

As you can see, I tried to use the crumbs array and also the click event, but it failed in both options

Can you please give me a working example?

**Comment by ryan-henness-trimble** [comment]
I suspect this is a bug with the crumb anchor tag pushing '#' to the route as an href link automatically - interfering with the Angular router

For now, let's remove the href attribute from the breadcrumb anchor

I've got a PR submitted to remove the '#' push: https://github.com/trimble-oss/modus-web-components/pull/1017

**Comment by ryan-henness-trimble** [comment]
@rubie9816 I will let you know when the updated package is released so that you can give it a shot

**Comment by ryan-henness-trimble** [comment]
@rubie9816 The packages have been updated:

- Web Components: https://github.com/trimble-oss/modus-web-components/pkgs/npm/modus-web-components
- Angular (v14): https://www.npmjs.com/package/@trimble-oss/modus-angular-components

Please let me know if this fixes the issue

**Comment by rubie9816** [comment]
It's fixed, Thank you! :)
