### ISSUE TITLE
unable to modify button width

### ISSUE THREAD

**Issue by rubie9816** [trimble-oss/modus-web-components#1018]
Is there a way to set a specific width to the button component? 
![image](https://user-images.githubusercontent.com/49250842/219503791-c45f033f-1f1e-4b28-8aa9-b5a5d8b30ff1.png)
I want both buttons to have the same size like this:
![image](https://user-images.githubusercontent.com/49250842/219504156-fd07a8ec-d2a5-479c-b80c-32b29d0181b8.png)
But the width wraps to the text inside, it would be great have another property  which modifies the width, like the "size" one, wich only modifies the height

**Comment by msankaran0712** [comment]
@egunther39 @soniakaukonen @coliff @enowak1031 Is it a valid use case to set button widths? maybe for achieving same width for buttons

**Comment by coliff** [comment]
I don't think we should add this option. The button width varies depending on the amount of characters on the button and we don't always know what that is (so if we added a set width button with a max and minimum size it could have adverse effects).

The Modus styleguide doesn't offer such an option and it isn't a common use case to set a set width. Instead they should have 16px padding on left and right.

**Comment by egunther39** [comment]
I agree with @coliff on this. This use case is more for mobile where buttons are vertically stacked

**Comment by soniakaukonen** [comment]
Agreed here too. Only this way we ensure same padding reacting upon length of label.
