### ISSUE TITLE
Sentiment Scale in Web Components

### ISSUE THREAD

**Issue by enowak1031** [trimble-oss/modus-web-components#1054]
### IMPORTANT:  This issue must be broken down into smaller issues.

Full description in https://github.com/trimble-oss/website-modus.trimble.com/issues/449

https://www.figma.com/file/wyfVJUHWRMkeCfdB38HFEE/Modus---Web?node-id=15854%3A33980&mode=dev

**Comment by msankaran0712** [comment]
@enowak1031 we did not start working on it yet, it would be great if the e-builder team can help.

**Comment by msankaran0712** [comment]
@PankajMahendran is interested in this component, @enowak1031 to confirm whether he can start with it

**Comment by pankaj-mahendran** [comment]
Sure @msankaran0712.

**Comment by msankaran0712** [comment]
Questions to clarify:
1. Does the Sentiment scale resemble a borderless button group? Is it a variant of the radio button group component? 
2. Is using a card mandatory? 
3. Is a label required to be placed below the icon? 
4. Should we incorporate tooltips as well? 
5. Is it always Thumbs up/down and Smileys? Are there any other options for a sentiment scale? 
6. Do we need a component for Ratings where multiple items can be selected? 
7. Do we need a two-tiered, five-tiered, or a combination of two, three, four, and five-tiered systems?
8. Can you clarify the statement, "When using a sentiment scale with chips, the user may remove and submit more than one chip."? 
9. What is a Title? What is a Short/Direct question? What is a Label? The guidelines require titles to be one to five words long, in title case, and with capitalized prepositions of four letters or more. Short and direct questions can replace the title or label. 
10. Can you provide more information on the accessibility guidelines? It states that a sentiment scale must have noticeable text that clearly describes the destination, purpose, function, or action of each emoticon for screen reader users.

**Comment by msankaran0712** [comment]
ARIA Labels:

- Thumbs up/down - Helpful/Not Helpful
- Not satisfied
- Somewhat dissatisfied
- Neutral
- Somewhat satisfied
- Satisfied

Is it always Thumbs up/down and Smileys? Are there any other options for a sentiment scale?
- Yes

Ratings
- Create an issue

Do we need a two-tiered, five-tiered, or a combination of two, three, four, and five-tiered systems?
- Only 2 and 5

Can you clarify the statement, "When using a sentiment scale with chips, the user may remove and submit more than one chip."?
-
