### ISSUE TITLE
Input and Button group  in Web Components

### ISSUE THREAD

**Issue by enowak1031** [trimble-oss/modus-web-components#1056]
Actual title: Interactive Search Button Inside Input Field in Web Components

Submitted by David Silcock

**Amendement**
- Having an interactive search button inside the field. It means we don't need to add an extra button outside of the field to search. It just looks a lot cleaner in my opinion.
- Just added the option to have a button on the right of the inside field
- Adding a 24px x 24px button to the write of a text input field.
- Has a hover and pressed state. When clicked it will (in my case) perform the search.

![Image](https://user-images.githubusercontent.com/97305117/221261056-c2725253-ad6a-4af7-b8ff-6b48e96250e9.png)

**Comment by msankaran0712** [comment]
Please refer the comments in https://github.com/trimble-oss/website-modus.trimble.com/issues/451

**Comment by msankaran0712** [comment]
Moving to backlog until prioritized

**Comment by msankaran0712** [comment]
One suggestion is we can add a button outside the text box.
