### ISSUE TITLE
Remove Navigating through Content Tree by Tabbing

### ISSUE THREAD

**Issue by enowak1031** [trimble-oss/modus-web-components#1057]
Tabbing should take the user out of the tree into the main content area. Arrows enable the user to navigate through the tree. 

This is because we need a way for the user to skip the tree and go straight to the content. Tabbing through the entire tree could be really frustrating. 

- [x] Decide how to handle checkbox selection when tabbing is disabled

**Comment by msankaran0712** [comment]
As discussed with @egunther39 @enowak1031 We decided to use right arrow key for checkbox and pressing the right arrow again will expand the item.
Also Check and add it to style guide about keyboard navigation
