### ISSUE TITLE
Add Blue Navbar Option to Web Components

### ISSUE THREAD

**Issue by enowak1031** [trimble-oss/modus-web-components#1058]
Currently, only the white version of the navbar is available. 

- When we add the dark blue version, we need to revisit hover and active states for icon buttons. Current do not meet color contrast ratios, but more importantly, they are just plain difficult to see.

**Comment by leohaughton** [comment]
Hi @enowak1031 
Just confirming that by Trimble Dark Blue you are referring to this?
https://modus.trimble.com/foundations/color-palette/

![image](https://user-images.githubusercontent.com/8316511/221995806-adcf4003-dfbc-4e72-9fa6-21383d7048df.png)

**Comment by enowak1031** [comment]
There should be only two options, white and blue. Devs should not be able to pick any other color. @egunther39 Do you agree?

**Comment by egunther39** [comment]
Correct. If its a Trimble product, White & Trimble Blue Dark are the only nav bar color options

**Comment by coliff** [comment]
> Correct. If its a Trimble product, White & Trimble Blue Dark are the only nav bar color options

There's a black version for dark mode in images on the docs.
https://modus.trimble.com/img/components/navbar-color-examples-dark.svg

![image](https://user-images.githubusercontent.com/1212885/226497371-1068057b-8573-410e-86dd-fa9aec5881cb.png)

**Comment by msankaran0712** [comment]
As discussed with @enowak1031 @egunther39 let's wait for more details from Dafnee

**Comment by egunther39** [comment]
@msankaran0712 - Here the changes which need to be made to the NavBar.
This is NOT an additional option but rather replaces the existing Blue NavBar styles.

Note: @christian will need to make changes in Modus components.


![Image](https://user-images.githubusercontent.com/98049598/228938906-01769508-de8d-4dc6-9093-e6a33cf5a61d.png)



**New Navbar color:** Blue Dark (#0E416C)

Blue Navbar Button
**Hover BG:** Blue Light (#217CBB stays as is)
**Hover BG Border (NEW):** 1px #019AEB

**Active/Pressed BG: (NEW):** #019AEB

**FYI - #019AEB** is the same color we added to
Dark Mode as the Highlight

**Comment by msankaran0712** [comment]
@coliff @egunther39 issues are created for React and Bootstrap
