### ISSUE TITLE
Modus Text Area Component

### ISSUE THREAD

**Issue by quynh-le-trimble** [trimble-oss/modus-web-components#1059]
Similar to the Modus text input, we need a text input that allows 

- multi-line
- configurable height (Defined by how many lines you want to show. eg. {multi-line: true, lines: 3 } 
- self-expanding?

Use Case:
This field can be used for description fields or fields that may need a paragraph worth of data.

**Comment by quynh-le-trimble** [comment]
Example: 
![image](https://user-images.githubusercontent.com/89219400/221280192-3990ed13-5484-42ba-ab1b-7188993b6266.png)

**Comment by msankaran0712** [comment]
@quynh-le-trimble I think this is related to https://github.com/trimble-oss/modus-web-components/issues/1053
and we can resolve the issue if there isn't anything else.

**Comment by msankaran0712** [comment]
hey @quynh-le-trimble I believe that is a Rich Text Editor and we have an issue for that #1053.
please feel free to re-open this issue if needed.

cc @coliff @enowak1031
