### ISSUE TITLE
Chip component enhancements

### ISSUE THREAD

**Issue by yohernandez** [trimble-oss/modus-web-components#1079]
**Describe the solution you'd like**
We would like to do these things in Modus Chips (See image below):
- Change the background color.
- Add a different icon at the left (other than the checkmark)
- Format the value, maybe be able to use HTML. For example, changing the weight of part of the text.
- Add a badge component at the right. 

**Describe alternatives you've considered**
Modus buttons allow the last three points but we will need to change the border-radius to make the button looks like a chip. See image below.

**Additional context**
<img width="690" alt="Screen Shot 2023-02-28 at 4 10 33 PM" src="https://user-images.githubusercontent.com/48927186/222200303-83c0fc4d-8c3a-4264-9a2b-5df8d8940157.png">

**Comment by msankaran0712** [comment]
We need more clarity on whether we need all,

- Change the background color - _(maha: currently we can use CSS variables to change the background color)_
- Add a different icon at the left (other than the checkmark) - _(maha: currently it is possible)_
- Format the value, maybe be able to use HTML. For example, changing the weight of part of the text. - _(maha - do we need this ?)_
- Add a badge component at the right - _(maha - do we need this?)_

**Comment by msankaran0712** [comment]
no badge

**Comment by msankaran0712** [comment]
@yohernandez are your questions answered?
If yes, we can close the issue.

**Comment by msankaran0712** [comment]
@yohernandez Closing the issue as there is no action pending. Please feel free to reopen the issue if there is anything unresolved.
