### ISSUE TITLE
Set up a Development Website which auto-builds deploys from `main`?

### ISSUE THREAD

**Issue by coliff** [trimble-oss/modus-web-components#1080]
On the new [Modus Icons website](http://modus-icons.trimble.com/) we have it setup to deploy to production on each new release.

We also have [a completely separate Azure SWA site](https://ambitious-sky-021d71010.2.azurestaticapps.net/) setup which does deploy previews and auto-builds from the main branch. It was straight-forward to setup and is good because it means recently added icons don't show on the production site until a release has shipped (which may only be once a month).

Do you think it might be useful for a similar setup for Modus Web Components? Maybe, as releases are made very frequently it may not be needed? What do you think?

**Comment by msankaran0712** [comment]
> On the new [Modus Icons website](http://modus-icons.trimble.com/) we have it setup to deploy to production on each new release.
> 
> We also have [a completely separate Azure SWA site](https://ambitious-sky-021d71010.2.azurestaticapps.net/) setup which does deploy previews and auto-builds from the main branch. It was straight-forward to setup and is good because it means recently added icons don't show on the production site until a release has shipped (which may only be once a month).
> 
> Do you think it might be useful for a similar setup for Modus Web Components? Maybe, as releases are made very frequently it may not be needed? What do you think?

Yes, I agree with the point that is not needed because we do releases frequently maybe we can revisit it when the frequency is less. @ryan-henness-trimble

**Comment by msankaran0712** [comment]
@coliff can we consider having a `develop` branch and push the PR changes to that branch and use `main`  branch only for production release.

**Comment by coliff** [comment]
I'm not in favour of that really. If we did that it would mean that we wouldn't have a site built from the develop branch (which could be annoying in some circumstances if you're making a PR to fix or improve a recently merged PR which isn't yet live) and just means an extra complication at release time. 

I think the original idea of using a separate Azure SWA for main would be a better option, and then the (current) production site only gets updated when a release is made (not on every merged PR).

**Comment by coliff** [comment]
We will use https://moduswebcomponents.netlify.app/ for the dev site (always has all changes from 'main' branch.

Modus Web Components (hosted on Azure SWA) will only update when a new version is published. I just have a small adjustment to make for the GitHub Action for that.
