### ISSUE TITLE
Datatable Resizable Column

### ISSUE THREAD

**Issue by anamarquezz** [trimble-oss/modus-web-components#1083]
I have this suggestion about a resizable column for the data table component, so when the user is on mobile, they can see differently the data table, 

I put this link, as an example what I'm trying to say 😅

https://codepen.io/crwilson311/pen/Bajbdwd

Thanks!

**Comment by msankaran0712** [comment]
hey @anamarquezz we are implementing it and very soon it will be available as part of the revamped Modus Data Table component. https://github.com/trimble-oss/modus-web-components/issues/1112
