### ISSUE TITLE
Update all icons in Web Components

### ISSUE THREAD

**Issue by msankaran0712** [trimble-oss/modus-web-components#1098]

**Comment by msankaran0712** [comment]
Christian to create a script for importing Solid icons

**Comment by msankaran0712** [comment]
maha to create another issue for work post script

**Comment by enowak1031** [comment]
@msankaran0712 Is this issue still part of this sprint?

**Comment by msankaran0712** [comment]
Duplicate of https://github.com/trimble-oss/modus-web-components/issues/1860
