### ISSUE TITLE
Modus Table - Add support for Expandable(Summary) row

### ISSUE THREAD

**Issue by msankaran0712** [trimble-oss/modus-web-components#1114]
More details at https://docs.google.com/document/d/1CKKDkgKHHktu_6yxg-dF7iJ5bHAZkydo69qJMQO_2so/edit

**Comment by Ankur-Koul** [comment]
![image](https://github.com/trimble-oss/modus-web-components/assets/129370095/655e6268-6b1d-43f7-a733-0276d003e280)

![image](https://github.com/trimble-oss/modus-web-components/assets/129370095/6e9e715d-573d-4eb4-8036-376b77b36fa4)

**Comment by msankaran0712** [comment]
@HarshithaNous @Ankur-Koul Just a reminder, this issue also covers showing a summary in the expandable row 

https://www.figma.com/file/ygURNTfPtwqsdu4NsqoQQT/Modus-%26-eBuilder?node-id=37%3A3494&mode=dev


![Image](https://github.com/trimble-oss/modus-web-components/assets/50131391/db81f6be-2826-4ba1-b2f0-ac7b4b410ff5)

**Comment by msankaran0712** [comment]
> @HarshithaNous @Ankur-Koul Just a reminder, this issue also covers showing a summary in the expandable row
> 
> https://www.figma.com/file/ygURNTfPtwqsdu4NsqoQQT/Modus-%26-eBuilder?node-id=37%3A3494&mode=dev
> 
> ![Image](https://user-images.githubusercontent.com/50131391/251487837-db81f6be-2826-4ba1-b2f0-ac7b4b410ff5.png)

Let's finish the expandable row with frozen first column

**Comment by msankaran0712** [comment]
Let us finish the expandable row with four levels and freeze the first column as part of the issue.
