### ISSUE TITLE
Modus Side Navigation - Export `ModusSideNavigationItemInfo` interface

### ISSUE THREAD

**Issue by G-L-Anghel** [trimble-oss/modus-web-components#1117]
**Describe the bug**
We need ModusSideNavigationItemInfo to be exported from modus library. Right now we duplicated it on our side
to be able to strongly type the input data model.
Below you'll see that the export is missing 
![image](https://user-images.githubusercontent.com/99797883/227440306-02e0a6e2-5496-4d34-b3d7-2739ca55cfd8.png)

**Comment by msankaran0712** [comment]
Fixed in PR https://github.com/trimble-oss/modus-web-components/pull/1121
