### ISSUE TITLE
[BUG] Tooltips colors are incorrect in Dark Mode

### ISSUE THREAD

**Issue by coliff** [trimble-oss/modus-web-components#1120]
**Describe the bug**

Tooltip colors are incorrect (dark mode)

**To Reproduce**

Go to: https://modus-web-components.trimble.com/?path=/docs/components-tooltip--default - inspect the tooltips in dark mode

**Expected behavior**

background Gray 0 (`#E0E1E9`),
text: Trimble Gray (`#252A2E`)

**Comment by soniakaukonen** [comment]
New decision:

Due to accessibility issues, change for dark mode tooltip to: 

background Gray 0 (#E0E1E9), 
text: Trimble Gray (#252A2E) 

as below:

![Image](https://user-images.githubusercontent.com/101354258/229160700-1a6f4954-6330-4c16-a6de-17ab1ca1c63a.png)
