### ISSUE TITLE
Ability to toggle Chip component state

### ISSUE THREAD

**Issue by msankaran0712** [trimble-oss/modus-web-components#1136]
click/tap on a chip component to select it and click back to de-select it

![image](https://user-images.githubusercontent.com/50131391/229447829-a98340d7-f8ab-4157-8737-bc7bd4d16d3e.png)

![image](https://user-images.githubusercontent.com/50131391/229447405-2e43ee8d-edb7-41f3-95cd-6aa8cc3bc42e.png)

**Comment by msankaran0712** [comment]
This is to reaffirm that Modus has approved the functionality for development.

Note: Modus team tag the approved issues with `modus-approved`

**Comment by msankaran0712** [comment]
Check with Sara if her team can contribute.

**Comment by msankaran0712** [comment]
After Sprint RTF and Critical Action Button

**Comment by cjwinsor** [comment]
@enowak1031 Can we refine these requirements to ensure we are meeting the design system needs?

**Comment by cjwinsor** [comment]
@cjwinsor Check if there is a way to persist the chip as active.
