### ISSUE TITLE
Update to Storybook v8.x

### ISSUE THREAD

**Issue by coliff** [trimble-oss/modus-web-components#1143]
Storybook v8 is a major new version with lots of new features and big improvements. It has been in development for more than a year and was recently finally published live.

https://storybook.js.org/docs/react/migration-guide

It'd be great to update our site to use this! We need to test this properly before deploying.

cc @cjwinsor

**Comment by msankaran0712** [comment]
@coliff  are we doing this in the current sprint?

**Comment by coliff** [comment]
@msankaran0712 @ryan-henness-trimble - this is a major upgrade and requires quite a few changes. There is a multi-step upgrade process run via CLI which walks you through it. I tried a few times but couldn't get it working.

Would appreciate it if you could give it a try. It's not critical but Storybook v6 is no longer being updated and has a few issues which are resolved in Storybook v7 (including a security fix and Node v18 compatibility).

**Comment by cjwinsor** [comment]
Updated to reference that 8 is now the latest version

**Comment by prashanth-offcl** [comment]
@prashanth-offcl to try this in local and list down the changes
