### ISSUE TITLE
[BUG] Color Scheme is always on light mode

### ISSUE THREAD

**Issue by coliff** [trimble-oss/modus-web-components#1155]
**Describe the bug**

Noticed a bug on [modus-web-components.trimble.com](https://modus-web-components.trimble.com/?path=/docs/introduction-getting-started--page). The [color-scheme CSS](https://developer.mozilla.org/en-US/docs/Web/CSS/color-scheme) is always on lightmode. it's not a major problem, it just means some OS level controls like the scrollbar and autocomplete input form fields are always light.

**To Reproduce**

1. Go to 'https://modus-web-components.trimble.com/?path=/docs/introduction-getting-started--page' when browser set to dark mode
2. Notice the left scrollbar is light gray and not dark gray as expected.

**Screenshots**

![image](https://user-images.githubusercontent.com/1212885/231117981-c6ec7b1c-d6bf-4296-b3d2-e24f22ae3b29.png)

I think we need something like:

```css
body.dark {
  color-scheme: dark;
}
```

**Comment by msankaran0712** [comment]
@coliff do we need this issue?

**Comment by coliff** [comment]
Actually, the color scheme needs to be set on the html tag, but the theme mode is on the body tag so we need to use the :has selector like this - tested locally works great in all major browsers!:

```css
html:has(body.dark) {
  color-scheme: dark;
}
```
