### ISSUE TITLE
[BUG] Modus Cards - prop `backgroundColor` is not working

### ISSUE THREAD

**Issue by msankaran0712** [trimble-oss/modus-web-components#1166]
Reported by Robert Nagy and Adela Duna from the Trimble Creator team.

**Comment by msankaran0712** [comment]
This is to reaffirm that Modus has approved the functionality for development.

Note: Modus team tag the approved issues with `modus-approved`

**Comment by msankaran0712** [comment]
Users should be able to use `--modus-card-bg` CSS variable going forward inorder to customize the background color for cards.

**Comment by prashanth-offcl** [comment]
The changes are already merged so closing this issue
