### ISSUE TITLE
Property "disabled" of button doesn't work

### ISSUE THREAD

**Issue by rubie9816** [trimble-oss/modus-web-components#1196]
The "disabled" property of buttons doesn't work, it only changes the colors to appears disabled.

```html
<modus-button disabled size="medium" (click)="clickTest()" button-style="outline" color="secondary">
  Button Modus
</modus-button>
```

![image](https://user-images.githubusercontent.com/49250842/232925862-55510c60-0437-4031-a50c-95d888de538a.png)

**Comment by coliff** [comment]
We need to add the `pointer-events: none;` to the disabled state.

**Comment by rubie9816** [comment]
Thank you so much! I have tried to update the npm package for the modus-web-components but I have an error related to the modus-angular-components
<img width="800" alt="image" src="https://user-images.githubusercontent.com/49250842/233739666-be4af2e6-7cbc-49b3-979a-c08358e2a99b.png">
It looks like a mismatch of dependencies with the versions. Could you help me with this?

**Comment by coliff** [comment]
> Thank you so much! I have tried to update the npm package for the modus-web-components but I have an error related to the modus-angular-components. It looks like a mismatch of dependencies with the versions. Could you help me with this?

Thanks for reporting. We will publish a new version of modus-angular-components with this issue resolved soon.
