### ISSUE TITLE
error related to the modus-angular-components version mismatch

### ISSUE THREAD

**Issue by coliff** [trimble-oss/modus-web-components#1219]
### Prerequisites

- [X] I have [searched](https://github.com/trimble-oss/modus-web-components/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have validated any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/trimble-oss/modus-web-components/blob/main/CONTRIBUTING.md)

### Describe the issue

<img width="800" alt="233739666-be4af2e6-7cbc-49b3-979a-c08358e2a99b" src="https://user-images.githubusercontent.com/1212885/233943440-a62fa4f3-555f-4aa1-9e5a-15b0e88c2200.png">

Issues reported by @rubie9816.

### Reduced test cases

npm i

### Priority

High

### What product/project are you using Modus Components for?

CCX Connected Climate Exchange

### What is your team/division name?

Agriculture

**Comment by coliff** [comment]
We will fix this for the next version.

**Comment by ryan-henness-trimble** [comment]
@rubie9816 in your `package.json`, are you installing both the angular and web components manually?
