### ISSUE TITLE
Modus NavBar - Update Style of User Menu

### ISSUE THREAD

**Issue by cjwinsor** [trimble-oss/modus-web-components#1268]
### Prerequisites

- [X] I have [searched](https://github.com/trimble-oss/modus-web-components/issues?q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/trimble-oss/modus-web-components/blob/main/CONTRIBUTING.md)

### Proposal

We were given the following UX, shown below.  We will ensure alignment with Modus Design System and Modus Web Components teams before starting work

![image](https://github.com/trimble-oss/modus-web-components/assets/1130129/a2f023d6-259f-4519-ad22-5d207cabf702)
![image](https://github.com/trimble-oss/modus-web-components/assets/1130129/0529ec4c-e933-443e-a0c7-dd4478b2c6c4)

**Tasks**
1. Add ability to set icons to Menu Links
2. Option to hide Avatar / Initials in menu
3. Show Avatar / Initials above subtitle line
4. Propose replacing email line with user defined text (which could still be email if desired)
5. Change formatting of `Sign out`

It is e-Builder's intent to work on this request.

### Motivation and context

UX direction to update styling in collaboration with Modus Design System

### Which npm package?

@trimble-oss/modus-web-components

### Priority

Medium

### What is the product name the feature is requested for?

e-Builder

### What is the team name the product belongs to?

e-Builder

### What is the division name the team belongs to?

e-Builder

**Comment by msankaran0712** [comment]
This is to reaffirm that Modus has approved the functionality for development.

cc @cjwinsor 

Note: Modus team tag the approved issues with `modus-approved`

**Comment by msankaran0712** [comment]
Moving this to the backlog as the issue not been worked up at present

**Comment by msankaran0712** [comment]
@cjwinsor any updates on when are we taking this issue?

**Comment by prashanth-offcl** [comment]
The changes are already merged so closing this issue
