### ISSUE TITLE
Modus NavBar - Slot in user menu for custom content

### ISSUE THREAD

**Issue by cjwinsor** [trimble-oss/modus-web-components#1269]
### Prerequisites

- [X] I have [searched](https://github.com/trimble-oss/modus-web-components/issues?q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/trimble-oss/modus-web-components/blob/main/CONTRIBUTING.md)

### Proposal

We were given the following UX, shown below. We will ensure alignment with Modus Design System and Modus Web Components teams before starting work

The scope of this change would be to add a `slot` under the profile menu links.  We will use that for user delegation within e-Builder, but would leave this area generic to allow it to be flexible.

![image](https://github.com/trimble-oss/modus-web-components/assets/1130129/18fbb1c5-2bf7-49a2-8c44-6e1e4bd87875)

**Tasks**
1. Add `slot` area to User Profile Menu
2. Handle styling when there is and isn't content to be added.

It is e-Builder's intent to work on this request.

### Motivation and context

We have a user delegation feature in e-Builder which allows a user to work on behalf of another individual. In order to maintain that feature and use the Modus NavBar, we require an area enable user context switching.  By making it a slot, we enable reusability and flexibility with its use.

### Which npm package?

@trimble-oss/modus-web-components

### Priority

Medium

### What is the product name the feature is requested for?

e-Builder

### What is the team name the product belongs to?

e-Builder

### What is the division name the team belongs to?

e-Builder

**Comment by msankaran0712** [comment]
This is to reaffirm that Modus has approved the functionality for development.

cc @cjwinsor 

Note: Modus team tag the approved issues with `modus-approved`

**Comment by msankaran0712** [comment]
Moving this to the backlog as the issue not been worked up on currently

**Comment by msankaran0712** [comment]
@cjwinsor any updates on when are we taking this issue?

**Comment by prashanth-offcl** [comment]
Closing this issue as the changes are already merged
