### ISSUE TITLE
Tooltip - Web component element is missing in Canvas section

### ISSUE THREAD

**Issue by HarshithaNous** [trimble-oss/modus-web-components#1276]
### Prerequisites

- [X] I have [searched](https://github.com/trimble-oss/modus-web-components/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have validated any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/trimble-oss/modus-web-components/blob/main/CONTRIBUTING.md)

### Describe the issue

Tooltip - Web component element is missing in Canvas section

Steps to reproduce:
1. Access storybook webpage
2. Select Tooltip component
3. Click on Canvas section
4. Verify if the tooltip component is displayed
5. Tooltip component is currently not displayed
6. Click on Docs section
7. Verify if the tooltip component is displayed
8. Tooltip component is displayed

Expected Behavior: Tooltip component should be displayed in the canvas section

Current Behavior: Tooltip component is not displayed in the canvas section

Please refer the below screenshot:
![image](https://github.com/trimble-oss/modus-web-components/assets/129380495/0bc9f5b7-4274-43d2-8816-71f8f9342bf0)

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome, Firefox, Microsoft Edge

### Priority

Medium

### What product/project are you using Modus Components for?

QA

### What is your team/division name?

QA

**Comment by ryan-henness-trimble** [comment]
Looks like this was resolved via #1384
