### ISSUE TITLE
Autocomplete - Controls - The behavior of Disabled functionality is not as expected

### ISSUE THREAD

**Issue by HarshithaNous** [trimble-oss/modus-web-components#1279]
### Prerequisites

- [X] I have [searched](https://github.com/trimble-oss/modus-web-components/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have validated any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/trimble-oss/modus-web-components/blob/main/CONTRIBUTING.md)

### Describe the issue

Autocomplete - Controls - The behavior of Disabled functionality is not as expected

When the auto search field is disabled we expect the text field to be disabled where the user should not be able to enter any text in the text box and the field should only be focused when the user selects the text field.

Currently, the textbox is active and also user is able to type in search box. After entering the data user will have to give a space and "No results found" text is displayed as shown in the below screenshot:
![image](https://github.com/trimble-oss/modus-web-components/assets/129380495/3c80872c-53c1-4c42-b445-bc9f05969c97)
However, the dropdown values is not displayed

**Steps to reproduce:**
1. Access the storybook
2. Select Autocomplete web component Default/With Option/With Custom Option
3. On the canvas section, under Controls set 'Disabled' status to 'True'
4. Place the cursor on the Search textbox
5. Enter the required data and give a space

**Expected Behavior:** When the auto search field is disabled we expect the text field to be disabled where the user should not be able to enter any text in the text box and the field should only be focused when the user selects the text field.

**Current Behavior:** The textbox is active and also user is able to type in search box. After entering the data user will have to give a space and "No results found" text is displayed.

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome, Firefox, Microsoft Edge

### Which npm package?

@trimble-oss/modus-web-components

### Priority

Low

### What product/project are you using Modus Components for?

QA

### What is your team/division name?

QA

**Comment by cjwinsor** [comment]
Make sure the autocomplete looks disabled the same as a text input would, and the chips are also marked disabled.  No events should be triggered while disabled.  Pay special attention to any borders that might be on autocomplete instead of text input.

**Comment by coliff** [comment]
This is partially fixed with CSS. Visually appears disabled and has no pointer-events.. but it can be tabbed into. We should leave this ticket open as a JavaScript based fix would be ideal.

**Comment by jewel-shajan** [comment]
@prashanthr6383 Testing has been completed successfully, and everything is functioning as expected. Please proceed with the next steps to move this to PR.
