### ISSUE TITLE
Autocomplete - Controls - The behavior of Read-only functionality is not as expected

### ISSUE THREAD

**Issue by HarshithaNous** [trimble-oss/modus-web-components#1280]
### Prerequisites

- [X] I have [searched](https://github.com/trimble-oss/modus-web-components/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have validated any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/trimble-oss/modus-web-components/blob/main/CONTRIBUTING.md)

### Describe the issue

Autocomplete - Controls - The behavior of Read-only functionality is not as expected

When the auto search field is set to Read-only, we expect the text field to be disabled where the user should not be able to enter any text in the text box and the field should only be focused when the user selects the text field.

Currently, the textbox is active and also user is able to type in search box. After entering the data user will have to give a space and "No results found" text is displayed as shown in the below screenshot:
![image](https://github.com/trimble-oss/modus-web-components/assets/129380495/5727fbfc-bce0-4922-a2fe-396b868655ca)

**Steps to reproduce:**

1. Access the storybook
2. Select Autocomplete web component Default/With Option/With Custom Option
3. On the canvas section, under Controls set 'Read-only' status to 'True'
4. Place the cursor on the Search textbox
5. Enter the required data and give a space

**Expected Behavior:** When the auto search field is set Read only we expect the text field to be disabled where the user should not be able to enter any text in the text box and the field should only be focused when the user selects the text field.

**Current Behavior:** The textbox is active and also user is able to type in search box. After entering the data user will have to give a space and "No results found" text is displayed.

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome, Firefox, Microsoft Edge

### Priority

Low

### What product/project are you using Modus Components for?

QA

### What is your team/division name?

QA

**Comment by prashanth-offcl** [comment]
With disabled attribute set to true, the user is still able to type in the textbox by using keyboard navigation.  This needs to be fixed.

**Comment by mitch-trimble** [comment]
Looks like the expected behavior and current behavior outlined above are accurate. 

With read-only enabled you can still select new options from the list, and their value is set in the box (for both single select and multi-select).

The main change needed seems to be not allowing new selections or editing current selections in read-only mode.

**Comment by jewel-shajan** [comment]
@prashanthr6383  Could you confirm if the item needs to remain highlighted while clicking, similar to its behavior when tabbing?
