### ISSUE TITLE
TP-7019: modus-text-input and modus-number-input components should have ability to right align the value

### ISSUE THREAD

**Issue by kmamidipalli** [trimble-oss/modus-web-components#1301]
### Prerequisites

- [X] I have [searched](https://github.com/trimble-oss/modus-web-components/issues?q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/trimble-oss/modus-web-components/blob/main/CONTRIBUTING.md)

### Proposal

![image](https://github.com/trimble-oss/modus-web-components/assets/40302378/cf57adc9-b2ac-44ff-8d19-85967ce55003)

Align the text to the right of the modus-text-input and modus-number-input components.

### Motivation and context

monetary amounts are better read right-aligned when using two decimal places, especially when using several fields in a single-column form

### Which npm package?

@trimble-oss/modus-web-components

### Priority

Medium

### What is the product name the feature is requested for?

e-Builder

### What is the team name the product belongs to?

e-Builder

### What is the division name the team belongs to?

e-Builder

**Comment by msankaran0712** [comment]
It is possible to set text-align to right for the HTML input. @egunther39 @enowak1031 @soniakaukonen Is this a valid use case ? If yes, we need to add a configuration.

**Comment by msankaran0712** [comment]
@kmamidipalli is your team willing to contribute?

**Comment by msankaran0712** [comment]
@kmamidipalli The issue has been fixed and closed.

**Comment by kmamidipalli** [comment]
> @kmamidipalli The issue has been fixed and closed.

Alright, Thanks @msankaran0712
