### ISSUE TITLE
TP-6913: modus-modal should have option to disable primary-button and secondary-button

### ISSUE THREAD

**Issue by kmamidipalli** [trimble-oss/modus-web-components#1308]
### Prerequisites

- [X] I have [searched](https://github.com/trimble-oss/modus-web-components/issues?q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/trimble-oss/modus-web-components/blob/main/CONTRIBUTING.md)

### Proposal

We want to be able to disable the buttons at the bottom of this modal. Currently there is no option to do that.
![image](https://github.com/trimble-oss/modus-web-components/assets/40302378/038750f1-3e9a-4d75-a928-19bf016b62d5)

### Motivation and context

In the screenshot attached in Proposal, we want to disable the button until a valid input is entered in the Update retainage text box above. However we don't have option to do that in current modus-modal. I only see the properties primary-button-text and secondary-button-text

### Which npm package?

@trimble-oss/modus-web-components

### Priority

Medium

### What is the product name the feature is requested for?

e-Builder

### What is the team name the product belongs to?

e-Builder

### What is the division name the team belongs to?

e-Builder

**Comment by msankaran0712** [comment]
I think it is okay to add two new configurations for disabling the primary and secondary buttons.

cc @ryan-henness-trimble

**Comment by msankaran0712** [comment]
@kmamidipalli is your team willing to contribute?

**Comment by msankaran0712** [comment]
This is to reaffirm that Modus has approved the functionality for development.

cc @kmamidipalli 

Note: Modus team tag the approved issues with `modus-approved`

**Comment by msankaran0712** [comment]
As confirmed by @kmamidipalli, this issue is blocking the team.

**Comment by msankaran0712** [comment]
@kmamidipalli PR is approved and merged. Please expect the fix in v0.1.48 by EOD.
