### ISSUE TITLE
All components on the storybook should include Controls tab

### ISSUE THREAD

**Issue by HarshithaNous** [trimble-oss/modus-web-components#1318]
### Describe the issue

All components on the storybook should include Controls tab

**Expected Result:** All the web components in Storybook should have the controls tab

**Actual Result:**
Few of the below mentioned components does not have the Controls tab.

- Accordion
- Breadcrumb
- Card
- Data Table
- Dropdown
- List
- Modal
- Navbar
- Radio group
- Side Navigation
- Tabs
- Tooltip
- Select

**Comment by msankaran0712** [comment]
@msankaran0712 Break it up and ask for @ryan-henness-trimble 's help

**Comment by msankaran0712** [comment]
We are gradually making it available in all the components as in when a component is updated.

**Comment by msankaran0712** [comment]
The issue can be kept until all the components are enabled.

**Comment by enowak1031** [comment]
@prashanth-offcl This issue is in To Do but has not been sized.

**Comment by coliff** [comment]
This is complete
