### ISSUE TITLE
Message: Color code is not as per the style guide for question element in Dark theme

### ISSUE THREAD

**Issue by HarshithaNous** [trimble-oss/modus-web-components#1319]
### Describe the issue

Messages Web component - Color code is not as per the style guide for question element in Dark theme

**Steps to Reproduce:**

1. Access the storybook web page
2. Select Dark theme
3. Select Messages Web component
4. Under Messages, select Questions element
5. Verify the text color code is as per the style guide

**Expected Result:**  As per the style guide, Questions element should have the text with white (`#ffffff`) color.

**Actual Result:** Currently on the story book the text color for Questions element is grey (`#a3a6b1`) color

Please refer the below screenshots:
<img width="920" alt="image" src="https://github.com/trimble-oss/website-modus.trimble.com/assets/129380495/5c391ffe-b952-4cdb-bf35-be2a9d6ea43d">

<img width="916" alt="image" src="https://github.com/trimble-oss/website-modus.trimble.com/assets/129380495/7d235a2e-9e7d-43a5-9684-a44d90f89e4d">

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome, Firefox, Microsoft Edge

**Comment by enowak1031** [comment]
@prashanth-offcl This is in the To Do column but has not been sized.
