### ISSUE TITLE
Modus-Select needs vertical and horizontal scroll when exceeding height and width

### ISSUE THREAD

**Issue by gallelauren816** [trimble-oss/modus-web-components#1327]
### Prerequisites

- [X] I have [searched](https://github.com/trimble-oss/modus-web-components/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have validated any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/trimble-oss/modus-web-components/blob/main/CONTRIBUTING.md)

### Describe the issue

With the modus-select component, there is no vertical or horizontal scroll so the dropdown box continues to grow as long as the text list inside. This creates a poor user experience. 

![image](https://github.com/trimble-oss/modus-web-components/assets/95942407/affbf0df-559f-47bc-afc1-8526579cb8df)

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome

### Which npm package?

@trimble-oss/modus-web-components

### What version of npm package are you using?

8.15.0

### Priority

High

### What product/project are you using Modus Components for?

HR Management

### What is your team/division name?

HRM

**Comment by coliff** [comment]
We will add a max-height to the select dropdown but it might be worthwhile considering revising the UI of your time selector. The hours, minutes and am/pm might be faster for users to select if they were separate inputs.
See the native `input type="time"` for reference:
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/time

![edge_time](https://github.com/trimble-oss/modus-web-components/assets/1212885/d889a03e-1f1d-4e8d-a31e-e6fbe60e11ae)
