### ISSUE TITLE
[BUG] Modus Select Component - State issues

### ISSUE THREAD

**Issue by msankaran0712** [trimble-oss/modus-web-components#1334]
### Prerequisites

- [X] I have [searched](https://github.com/trimble-oss/modus-web-components/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have validated any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/trimble-oss/modus-web-components/blob/main/CONTRIBUTING.md)

### Describe the issue

- Select dropdown icon on right isn't the correct one
- input options are not correct font
- Focus state doesn't have blue bottom border
- Also, the active class is applied to any option that is hovered over creating confusion about whether an item is hovered or selected.
- Can we have a placeholder text for this control? Thanks!

Split from #559 

### What operating system(s) are you seeing the problem on?

Windows

### Which npm package?

@trimble-oss/modus-web-components

### Priority

High

### What product/project are you using Modus Components for?

Modus

### What is your team/division name?

Modus

**Comment by sarafarhat13** [comment]
Any updates on the placeholder text? The web component still doesn't have a placeholder text.
