### ISSUE TITLE
Chip close icon and height

### ISSUE THREAD

**Issue by yohernandez** [trimble-oss/modus-web-components#1336]
### Prerequisites

- [X] I have [searched](https://github.com/trimble-oss/modus-web-components/issues?q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/trimble-oss/modus-web-components/blob/main/CONTRIBUTING.md)

### Proposal

Modus Chip close icon uses `icon-remove` which is different from the icon described in Modus Style Guide (https://modus.trimble.com/components/web/chips/styles/). That one is `icon-close`. A possible solution is to add a new optional property where the consumer can decide which they want to use. Possible name: `closeIcon`.
Also, the chip height is different when the icons are visible 
![image](https://github.com/trimble-oss/modus-web-components/assets/48927186/a3a9db45-f4c4-4796-af3e-0a0d127872db)
The padding-top and padding-bottom are 0 if there is no icon. 
`&.no-left-icon.no-right-icon {
    padding: 0 $rem-16px;
  }`
It should be the same always
`padding: $rem-2px $rem-4px;`

### Which npm package?

@trimble-oss/modus-web-components

### Priority

Medium

### What is the product name the feature is requested for?

e-builder

### What is the team name the product belongs to?

e-builder

### What is the division name the team belongs to?

e-builder

**Comment by msankaran0712** [comment]
@egunther39 @soniakaukonen @coliff @enowak1031 
looks like Styleguide is showing two different close icons, is that valid? If yes, we need to make it configurable in the web component.

Styleguide:
![image](https://github.com/trimble-oss/modus-web-components/assets/50131391/2619e365-e1d6-4850-83ce-f7b80685aa1a)

![image](https://github.com/trimble-oss/modus-web-components/assets/50131391/36e8c8d5-dc7e-4be2-8956-81435e9b3674)


cc @yohernandez

**Comment by soniakaukonen** [comment]
Replacing placeholder with x token on Figma and extracting necessary illustrations for stylel guide @msankaran0712 @egunther39  https://github.com/trimble-oss/modus/issues/451
