### ISSUE TITLE
Request for Angular 15 support

### ISSUE THREAD

**Issue by AndreSteynTrimble** [trimble-oss/modus-web-components#1352]
### Prerequisites

- [X] I have [searched](https://github.com/trimble-oss/modus-web-components/issues?q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/trimble-oss/modus-web-components/blob/main/CONTRIBUTING.md)

### Proposal

We have an new web application being written in Angular 15. We are running into the problem below when trying to use the current npm packages:

![image](https://github.com/trimble-oss/modus-web-components/assets/120085924/8b5303c0-04ab-497e-8083-0518e973254a)

Would it be possible to release a new package that is compatible with Angular 15?

### Motivation and context

This change will allow web applications written in Angular 15 to use Modus without effort.

### Which npm package?

@trimble-oss/modus-angular-components

### Priority

High

### What is the product name the feature is requested for?

Trimble Geospatial Scan-Data System (Seurat)

### What is the team name the product belongs to?

Trimble Geospatial Cloud Services

### What is the division name the team belongs to?

Trimble Geospatial

**Comment by coliff** [comment]
I think for this we need to setup [Nx](https://nx.dev/getting-started/intro) as referenced in https://github.com/trimble-oss/modus-web-components/issues/1353. If you have any feedback/suggestions or can help with that please let us know!

**Comment by AndreSteynTrimble** [comment]
We have a [brown bag session](https://www.presentationskills.me/what-is-a-brown-bag-session/) tomorrow. Will raise this topic there.

**Comment by AndreSteynTrimble** [comment]
@coliff So we don't have resource to assist in this unfortunately due to pressures to deliver an MVP before Dimensions. We are however happy to assist in testing and qa.

**Comment by msankaran0712** [comment]
For now, we can do it manually

**Comment by msankaran0712** [comment]
@msankaran0712 check with @coliff

**Comment by msankaran0712** [comment]
This is to reaffirm that Modus has approved the functionality for development.

cc @AndreSteynTrimble 

Note: Modus team tag the approved issues with `modus-approved`

**Comment by msankaran0712** [comment]
@AndreSteynTrimble Angular 15 components now available on npm

**Comment by AndreSteynTrimble** [comment]
> @AndreSteynTrimble Angular 15 components now available on npm https://www.npmjs.com/package/@trimble-oss/modus-angular-components/v/0.1.47-ng15

Thanks!
