### ISSUE TITLE
TP-7020: Focus doesn't stay on modus-modal, Focus doesn't shift to close button on top, escape button doesn't close modal

### ISSUE THREAD

**Issue by kmamidipalli** [trimble-oss/modus-web-components#1367]
### Prerequisites

- [X] I have [searched](https://github.com/trimble-oss/modus-web-components/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have validated any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/trimble-oss/modus-web-components/blob/main/CONTRIBUTING.md)

### Describe the issue

Hello,

While trying to implement accessibility on modus-modal, We have shifted the focus to a modus-text-input on modal. 
We see the below 3 issues.

1. Upon pressing tab few times on keyboard, the focus doesn't stay on modus-modal. It shifts to the back
2. The focus doesn't shif tto close button on top right corner.
3. When pressing escape button on keyboard, it doesn't close the modus-modal.

See below how our Modal looks.
![image](https://github.com/trimble-oss/modus-web-components/assets/40302378/bc08b208-5096-417e-b164-f4658083c7bf)

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome

### Which npm package?

@trimble-oss/modus-web-components

### Priority

High

### What product/project are you using Modus Components for?

e-Builder

### What is your team/division name?

e-Builder

**Comment by msankaran0712** [comment]
@egunther39 @soniakaukonen @enowak1031 @coliff 
We need to decide whether the following use cases are supported, 

- Upon pressing the tab a few times on the keyboard, the focus doesn't stay on the modus-modal. It shifts to the back
- When pressing the escape button on the keyboard, it doesn't close the modus-modal.

**Comment by msankaran0712** [comment]
@kmamidipalli is your team willing to contribute?

**Comment by msankaran0712** [comment]
This is to reaffirm that Modus has approved the functionality for development.

cc @kmamidipalli 

Note: Modus team tag the approved issues with `modus-approved`

**Comment by msankaran0712** [comment]
As confirmed by @kmamidipalli, this issue is blocking his team.

**Comment by msankaran0712** [comment]
@kmamidipalli PR is approved and merged. Please expect the fix in v0.1.48 by EOD.
