### ISSUE TITLE
Radio group -  Label border line is displayed when using a tab key to focus

### ISSUE THREAD

**Issue by HarshithaNous** [trimble-oss/modus-web-components#1396]
### Prerequisites

- [X] I have [searched](https://github.com/trimble-oss/modus-web-components/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/trimble-oss/modus-web-components/blob/main/CONTRIBUTING.md)

### Describe the issue

Radio group -  Label border line is displayed when using a tab key to focus

**Steps to Reproduce:**
1. Access Modus storybook
2. Navigate to Radio group component
3. On Canvas section, click on tab key
4. Verify if the focus is only on the radio button and not on the label

**Expected result:** The focus should be on the radio button and not on the label

**Actual result:** Label border line is displayed when using a tab key to focus

Please refer the below screenshot:
![image](https://github.com/trimble-oss/modus-web-components/assets/129380495/1d5ffb33-b2ff-4fcc-9219-071d5de682e6)

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome, Firefox, Microsoft Edge

### What is the issue regarding ?

@trimble-oss/modus-web-components

### Priority

Medium

### What product/project are you using Modus Components for ?

QA

### What is your team/division name ?

QA

### Are you willing to contribute ?

None

**Comment by coliff** [comment]
Issue resolved.
