### ISSUE TITLE
Add Floating utility bar

### ISSUE THREAD

**Issue by soniakaukonen** [trimble-oss/modus-web-components#1399]
@msankaran0712 I will discuss with David Silcock how they submit

Submission doc:
https://docs.google.com/presentation/d/1EMYcsaDmfrTQ58wVOFlW8XTOduHwtWAKUmbbWfHSOog/edit#slide=id.g18974be1d13_0_0

**Comment by msankaran0712** [comment]
Need more details.

**Comment by soniakaukonen** [comment]
There are four issues separately and this is double. Terminology clash.

Submission for Floating:
- Navbar - Variant
- Side Nav - Variant
- Button (single button) Variant
- Toolbar (container with several buttons, floating). New component.

https://github.com/trimble-oss/modus-web-components/issues/1417
https://github.com/trimble-oss/modus-web-components/issues/1418
https://github.com/trimble-oss/modus-web-components/issues/1419
https://github.com/trimble-oss/modus-web-components/issues/1420

Closing this double.
