### ISSUE TITLE
Modus NavBar - Allow User menu Tooltip to be screen boundary aware

### ISSUE THREAD

**Issue by ElavarasanTrimble** [trimble-oss/modus-web-components#1408]
### Prerequisites

- [X] I have [searched](https://github.com/trimble-oss/modus-web-components/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/trimble-oss/modus-web-components/blob/main/CONTRIBUTING.md)

### Describe the issue

Before test
1. Make sure the user menu tooltip has a long name

Steps to reproduce the issue
1. Just hover on the user menu tooltip

Presently, For a User who has has a long name the tooltip for the user menu extends the page and make the page horizontally scrollable

Allow the tooltip to be screen boundary aware, so it can be shown with the page.

![Screenshot 2023-06-08 200813](https://github.com/trimble-oss/modus-web-components/assets/102205488/c90e8ce5-b819-4a80-a701-45226522eebd)

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome, Firefox, Microsoft Edge

### What is the issue regarding ?

@trimble-oss/modus-web-components

### Priority

Medium

### What product/project are you using Modus Components for ?

e-Builder

### What is your team/division name ?

e-Builder

### Are you willing to contribute ?

None

**Comment by msankaran0712** [comment]
hey @ElavarasanTrimble  are you willing to contribute?

**Comment by msankaran0712** [comment]
This will be fixed when #1445 is completed.

**Comment by msankaran0712** [comment]
@ElavarasanTrimble This issue has been resolved in #1445, kindly wait until the end of this week for the next release.
