### ISSUE TITLE
Angular 16 support

### ISSUE THREAD

**Issue by creichelt-transporeon** [trimble-oss/modus-web-components#1411]
### Prerequisites

- [X] I have [searched](https://github.com/trimble-oss/modus-web-components/issues?q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [Modus style guidelines](https://modus.trimble.com/components/web/introduction/)

### Proposal

We are building a new product, using Angular 16.
There for we need a component lib supporting this.

### What is the issue regarding ?

@trimble-oss/modus-angular-components

### Priority

High

### What product/project are you using Modus Components for ?

Taskflow

### What is your team/division name ?

squad carbon

### Are you willing to contribute ?

None

**Comment by msankaran0712** [comment]
@creichelt-transporeon We now have Angular 16 support for Modus Angular Components. Please download from https://www.npmjs.com/package/@trimble-oss/modus-angular-components?activeTab=versions.

Please let us know if you face any issues with the components.

**Comment by creichelt-transporeon** [comment]
Oh, is it already released?
I didn't saw it in the release notes: https://github.com/trimble-oss/modus-web-components/releases/tag/v0.1.48
However I saw it for Angular 15: https://github.com/trimble-oss/modus-web-components/releases/tag/v0.1.47

**Comment by msankaran0712** [comment]
> Oh, is it already released? I didn't saw it in the release notes: https://github.com/trimble-oss/modus-web-components/releases/tag/v0.1.48 However I saw it for Angular 15: https://github.com/trimble-oss/modus-web-components/releases/tag/v0.1.47 @msankaran0712

Might have been missed by mistake.

**Comment by msankaran0712** [comment]
> > Oh, is it already released? I didn't saw it in the release notes: https://github.com/trimble-oss/modus-web-components/releases/tag/v0.1.48 However I saw it for Angular 15: https://github.com/trimble-oss/modus-web-components/releases/tag/v0.1.47 @msankaran0712
> 
> Oh, sorry for that. It might have been missed by mistake.

Again my bad, just realized that Angular 16 support was added only after Modus Web components v48 was released. Hence it will be part of the next release notes https://github.com/trimble-oss/modus-web-components/releases/tag/untagged-0860d7064bdf9789d64a.
