### ISSUE TITLE
Modus NavBar - Add a Search Overlay  

### ISSUE THREAD

**Issue by msankaran0712** [trimble-oss/modus-web-components#1413]
### Prerequisites

- [X] I have [searched](https://github.com/trimble-oss/modus-web-components/issues?q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [Modus style guidelines](https://modus.trimble.com/components/web/introduction/)

### Proposal

As part of e-Builder’s Navigation Project, we need a search overlay for the Modus Navbar component.

- The user clicks on the search icon, and then an overlay takes over the entire header
- All other elements are hidden, Including Logo and Profile.
- The search input field and the X (close) icon are displayed

More details at https://docs.google.com/document/d/1Ym59OE7XdmaAgE38gAK5sv4EW9G06p16Fa-Q-nU54Pc/edit#heading=h.ec7cpa9qlyh9

### What is the issue regarding ?

@trimble-oss/modus-web-components

### Priority

High

### What product/project are you using Modus Components for ?

AngryNerds

### What is your team/division name ?

e-builder

### Are you willing to contribute ?

None

**Comment by msankaran0712** [comment]
@cjwinsor @soniakaukonen Please feel free to update this issue

**Comment by soniakaukonen** [comment]
Figma: tray for all sizes, component header search (no animation yet)
Style guide: section Styles > Search addressing X-Small size only. Should include any size?

**Comment by msankaran0712** [comment]
@cjwinsor this issue is modus approved and ready to be worked on. Please let us know whom to assign this to
