### ISSUE TITLE
Modus Data Table - Row action menu offset when page has scrolled

### ISSUE THREAD

**Issue by CCurryViewpoint** [trimble-oss/modus-web-components#1416]
### Prerequisites

- [X] I have [searched](https://github.com/trimble-oss/modus-web-components/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/trimble-oss/modus-web-components/blob/main/CONTRIBUTING.md)

### Describe the issue

When a page containing a data table has scrolled down, the row action menu no longer appears next to the button. In the worst cases, the menu no longer appears on the page. 

![modus-data-table-scroll-issue](https://github.com/trimble-oss/modus-web-components/assets/23236193/6ddbfdd6-458a-4116-b63a-f67ebb58948b)

I'm happy to investigate a fix for this issue as I think I know what's causing the issue.

### What is the issue regarding ?

@trimble-oss/modus-web-components

### Priority

Low

### What product/project are you using Modus Components for ?

Viewpoint For Projects [Trimble Connect integration]

### What is your team/division name ?

Viewpoint

### Are you willing to contribute ?

Yes

### Are you using Modus Web Components in production ?

Yes, I'm happy to walk through our implementation if interested.

**Comment by msankaran0712** [comment]
@CCurryViewpoint PR approved and merged 👍🏼 Please expect the fix in the upcoming release, or let us know if you need it urgently.

cc @coliff
