### ISSUE TITLE
Floating UI: Button

### ISSUE THREAD

**Issue by davidtsilcock** [trimble-oss/modus-web-components#1419]
### Prerequisites

- [X] I have [searched](https://github.com/trimble-oss/modus-web-components/issues?q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [Modus style guidelines](https://modus.trimble.com/components/web/introduction/)

### Proposal

This is a ticket outlining the work to be done on the buttons in the floating UI style that has been discussed with the modus team.

This development can be carried out by the Creator/Nexus team.

Original button:
![Screenshot 2023-06-14 102150](https://github.com/trimble-oss/modus-web-components/assets/106724479/ea8579eb-f841-4941-9b47-736110c6d781)

Floating UI button:
![Screenshot 2023-06-14 102205](https://github.com/trimble-oss/modus-web-components/assets/106724479/509a0df9-15b4-4712-9d72-e901f612720c)

Trimble Creator button:
![Screenshot 2023-06-14 102238](https://github.com/trimble-oss/modus-web-components/assets/106724479/dfb62233-85b4-4c23-addc-1db0d0b642a9)
![Screenshot 2023-06-14 102304](https://github.com/trimble-oss/modus-web-components/assets/106724479/6cc54b6a-7b2e-4151-b97d-7cb98338c142)

The button will be used in Trimble Creator to expand side panels, as well as in toolbar

We would like to develop this as a Modus web component, and then contribute it back to Modus.

### Motivation and context

Floating UI is a critical part of a canvas-style application such as Trimble Creator, SketchUp, Maps, and more. This UI allows the user to focus more o the creative space rather than the encompassing UI.

### What is the issue regarding ?

@trimble-oss/modus-web-components

### Priority

Medium

### What product/project are you using Modus Components for ?

Trimble Creator

### What is your team/division name ?

Nexus

### Are you willing to contribute ?

Yes

### Are you using Modus Web Components in production ?

Not yet, this will be one of the first steps on our migration to web-components in Trimble Creator.

**Comment by msankaran0712** [comment]
This is a variant of Floating Toolbar #1420
