### ISSUE TITLE
Floating Toolbar in Web Components

### ISSUE THREAD

**Issue by davidtsilcock** [trimble-oss/modus-web-components#1420]
### Prerequisites

- [X] I have [searched](https://github.com/trimble-oss/modus-web-components/issues?q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [Modus style guidelines](https://modus.trimble.com/components/web/introduction/)

### Proposal

This is a ticket outlining the work to be done on the toolbar in the floating UI style that has been discussed with the modus team.

This development can be carried out by the Creator/Nexus team.

Original toolbar: 
Modus doesn't currently have a toolbar in its library, however, it would look something like this in the current style.
![Screenshot 2023-06-14 102701](https://github.com/trimble-oss/modus-web-components/assets/106724479/2b5a5fb3-7062-4f32-843c-47f639193923)

Floating UI Navbar:
![Screenshot 2023-06-14 102715](https://github.com/trimble-oss/modus-web-components/assets/106724479/32432f73-fdd3-43ad-8671-820593a8f15a)

Trimble Creator Navbar:
![Screenshot 2023-06-14 102304](https://github.com/trimble-oss/modus-web-components/assets/106724479/513e622e-6cf1-43f5-9fa3-d966d9c30de4)

The toolbar would like just be a standard modus button contained in a panel/wrapper of some sort.

We would like to develop this as a Modus web component, and then contribute it back to Modus.

### Motivation and context

Floating UI is a critical part of a canvas-style application such as Trimble Creator, SketchUp, Maps, and more. This UI allows the user to focus more o the creative space rather than the encompassing UI.

### What is the issue regarding ?

@trimble-oss/modus-web-components

### Priority

Medium

### What product/project are you using Modus Components for ?

Trimble Creator

### What is your team/division name ?

Nexus

### Are you willing to contribute ?

Yes

### Are you using Modus Web Components in production ?

Not yet, this will be one of the first steps on our migration to web-components in Trimble Creator.

**Comment by msankaran0712** [comment]
Moving this to backlog until Trimble creator team or someone is available to contribute

**Comment by msankaran0712** [comment]
Maha to add Figma and Styleguide references

**Comment by msankaran0712** [comment]
What is the status of Floating Toolbar, Navbar and Utility panel on Styleguide and figma?

**Comment by msankaran0712** [comment]
@sorina-ocheana Can you please explain the use case for text button? Why can't have a icon button instead?

**Comment by davidtsilcock** [comment]
We could have an icon button, but I imagine there are a lot of use cases where text buttons would be needed in toolbars. Take Trimble Drawing for example:

![Frame 100](https://github.com/trimble-oss/modus-web-components/assets/106724479/7ad0bdfe-0de5-47c9-bfb1-11552e8e84cb)

I feel that it would be more productive for the component to allow any type of button to sit inside it, not just icon only buttons.

**Comment by msankaran0712** [comment]
@enowak1031 @egunther39 any comments on the text buttons inside a Toolbar?

cc @davidtsilcock @sorina-ocheana

**Comment by egunther39** [comment]
@msankaran0712 @davidtsilcock @enowak1031 - I think this is a valid use case and I'm okay with this

**Comment by msankaran0712** [comment]
@davidtsilcock we are good with having text buttons in Toolbar. PLease proceed with the developemnt

**Comment by prashanth-offcl** [comment]
Closing this issue as the changes are already merged
