### ISSUE TITLE
Card, List, Content tree, Modal and Toast(default) components - Background color code in dark theme is not as per the style guide 

### ISSUE THREAD

**Issue by HarshithaNous** [trimble-oss/modus-web-components#1432]
### Prerequisites

- [X] I have [searched](https://github.com/trimble-oss/modus-web-components/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/trimble-oss/modus-web-components/blob/main/CONTRIBUTING.md)

### Describe the issue

Card, List, Content tree, Modal and Toast(default) components - Background color code in dark theme is not as per the style guide

It is expected that the background color code in dark theme for all the above mentioned components to be #171c1e. Currently the background color code in dark theme for all of these components is  #252a2e or #353a40

Please refer the below screenshots:
![image](https://github.com/trimble-oss/modus-web-components/assets/129380495/f26c0371-c7c4-434d-895c-73c3cea84927)
![image](https://github.com/trimble-oss/modus-web-components/assets/129380495/01a6db3f-4edb-4fdc-9558-7f7233971d7c)
![image](https://github.com/trimble-oss/modus-web-components/assets/129380495/bf7e39eb-6d36-4147-b3ec-4dc258e313a3)
![image](https://github.com/trimble-oss/modus-web-components/assets/129380495/b36ab912-e920-4a41-9dc5-f0077baddefa)

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome, Safari, Firefox

### What is the issue regarding ?

@trimble-oss/modus-web-components

### Priority

Medium

### What product/project are you using Modus Components for ?

QA

### What is your team/division name ?

QA

### Are you willing to contribute ?

None

**Comment by rthanga1** [comment]
This is fixed now
