### ISSUE TITLE
Issue Labeler GitHub Action is failing

### ISSUE THREAD

**Issue by coliff** [trimble-oss/modus-web-components#1437]
### Prerequisites

- [X] I have [searched](https://github.com/trimble-oss/modus-web-components/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/trimble-oss/modus-web-components/blob/main/CONTRIBUTING.md)

### Describe the issue

REF: https://github.com/trimble-oss/modus-web-components/actions/runs/5301695315

We use https://github.com/github/issue-labeler for this

### What is the issue regarding ?

Modus Web Components Website (Storybook)

### Priority

Medium

### What product/project are you using Modus Components for ?

Modus

### What is your team/division name ?

Modus

### Are you willing to contribute ?

Yes

**Comment by msankaran0712** [comment]
Fixed
