### ISSUE TITLE
Critical Action Button in Web Components

### ISSUE THREAD

**Issue by enowak1031** [trimble-oss/modus-web-components#1439]

**Comment by ryan-henness-trimble** [comment]
can you add a link to the specs when they are ready? my team may have availability to work on this @enowak1031

**Comment by msankaran0712** [comment]
Hey @ryan-henness-trimble Please refer to https://docs.google.com/document/d/1fdoD60sLyEywfnXk_zpGlCeR5ZAUGKEVS6TU4UR9Xx8/edit for the specs

please correct me if it is not the correct document @enowak1031

**Comment by msankaran0712** [comment]
@ryan-henness-trimble is your team planning to work on this issue?

**Comment by cjwinsor** [comment]
Follow the specs from https://docs.google.com/document/d/1fdoD60sLyEywfnXk_zpGlCeR5ZAUGKEVS6TU4UR9Xx8/edit and the styleguide.

**Comment by ryan-henness-trimble** [comment]
> @ryan-henness-trimble is your team planning to work on this issue?

Our availability is low at the moment - we won't plan on taking this one on

**Comment by cjwinsor** [comment]
@ryan-henness-trimble We are in the process of planning out when we'll tackle it 👍

**Comment by cjwinsor** [comment]
Create a new property on the modus button which adds the press/hold/progress indicator as described for the critical action button.  Just like Danger and Special, we will call out this variant as Critical Action Button, which is specifically a Danger button with this property set to true. We won't implement this property if the color isn't set to danger.  That is something that can be added later if a strong need is brought up. We should make it clear in the writeup that this property only affects danger buttons.

![Image](https://github.com/user-attachments/assets/d1640cdc-e55f-4200-9394-6454c0b14915)

**Comment by coliff** [comment]
Accessibility Report: I raised concern about including this before but this 'hold down button' paradigm is not accessible and I don't think this PR should be merged.
- Right now holding down the button does nothing on an iPad.
- The action is not announced to screen readers
- The long-press action is already in use on Windows with touch screens and works everywhere, including web browsers. The effect of executing custom action on long press can be therefore unpredictable and it could depend on the operating system and/or browser. 

**Unless you have some solid workaround of this problem, you should not ignore this shortcoming, especially when designing web UI, which is expected to be platform independent. Without solid workaround available, I would categorize the severity of this problem as a stopper.**

Long-pressing a button isn't a known action on web for desktops, it simply doesn't exist and you won't see it in other style guides.

Instead, please consider asking the user to confirm the action again. Smashing Magazine posted an excellent article 'How To Manage Dangerous Actions In User Interfaces' last week with ideas:
https://www.smashingmagazine.com/2024/09/how-manage-dangerous-actions-user-interfaces/

**Comment by enowak1031** [comment]
@coliff I think we should add the button and add a warning label both in Storybook and on the style guide that it might not be accessible. I created a separate issue to address this: #2961
