### ISSUE TITLE
Modus Buttons - Add variants to use in Modus Navbar

### ISSUE THREAD

**Issue by msankaran0712** [trimble-oss/modus-web-components#1444]
### Prerequisites

- [X] I have [searched](https://github.com/trimble-oss/modus-web-components/issues?q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [Modus style guidelines](https://modus.trimble.com/components/web/introduction/)

### Proposal

We need icon variants for the Modus Button to be used in the Modus Navbar component in light, dark and blue themes.

We already have light and dark theme buttons. We must create a new variant for Navbar blue theme.

https://www.figma.com/file/wyfVJUHWRMkeCfdB38HFEE/Modus---Web?type=design&node-id=1346-14&mode=design&t=MWAkvciXFp9qjPYR-0

### What is the issue regarding ?

@trimble-oss/modus-web-components

### Priority

High

### What product/project are you using Modus Components for ?

modus

### What is your team/division name ?

modus

### Are you willing to contribute ?

None

**Comment by msankaran0712** [comment]
A variant for blue background

**Comment by msankaran0712** [comment]
@egunther39 

As discussed with @soniakaukonen, I understand that we must use [dark theme secondary colour icon-only( with no outline) button](https://www.figma.com/file/wyfVJUHWRMkeCfdB38HFEE/Modus---Web?node-id=8158%3A33220&mode=dev) for Navbar both on light and dark themes.

**Comment by soniakaukonen** [comment]
Meaning on dark blue nav bar.
One more consideration from components point of view @egunther39 : their states differ (in blue), so should they be maintained separately? Hover and selected are not gray but blue in this case.

**Comment by msankaran0712** [comment]
Figma has the variant added. We do not need an example for this variant to show in Buttons page on storybook but Navbar should be using the button.

**Comment by msankaran0712** [comment]
Styleguide Issue: https://github.com/trimble-oss/website-modus.trimble.com/issues/655

**Comment by cjwinsor** [comment]
Marking done as we currently handle buttons for the blue variant completely
