### ISSUE TITLE
Add React 18 Integration

### ISSUE THREAD

**Issue by leohaughton** [trimble-oss/modus-web-components#1460]
### Prerequisites

- [X] I have [searched](https://github.com/trimble-oss/modus-web-components/issues?q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [Modus style guidelines](https://modus.trimble.com/components/web/introduction/)

### Proposal

This issue is proposing to follow the existing React 17 pattern, and create a new directory and workflow for publishing React 18 components.

Under the `./react-workspace` directory there will be a new react-18 lib which will publish using the existing semver pattern of:

<modus-web-components-version>-<react primary version>

1.0.45-18

### Motivation and context

Allows React 18 applications to use Modus Web Component integration without having to use the node --legacy-peer-deps flag when running npm install.

### What is the issue regarding ?

@trimble-oss/modus-web-components

### Priority

Medium

### What product/project are you using Modus Components for ?

WorksOS, Firmware (Construction)

### What is your team/division name ?

CIS Software

### Are you willing to contribute ?

Yes

### Are you using Modus Web Components in production ?

Yes

**Comment by coliff** [comment]
We’re live! https://www.npmjs.com/package/@trimble-oss/modus-react-components?activeTab=versions
thanks Leo!
