### ISSUE TITLE
Content Tree - Custom Action Bar is invisible in dark theme

### ISSUE THREAD

**Issue by HarshithaNous** [trimble-oss/modus-web-components#1466]
### Prerequisites

- [X] I have [searched](https://github.com/trimble-oss/modus-web-components/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/trimble-oss/modus-web-components/blob/main/CONTRIBUTING.md)

### Describe the issue

Content Tree - Custom Action Bar is invisible in dark theme

**Steps to reproduce:**
1. Access Modus Web components page
2. Navigate to content tree component
3. Select Custom Action Bar
4. Select Dark theme
5. Verify if the Action bar is displayed

**Expected Result:** Custom Action Bar should be displayed in Dark theme

**Actual Result:** Custom Action Bar is not displayed in Dark theme

Please refer the below screenshot:
![image](https://github.com/trimble-oss/modus-web-components/assets/129380495/4113e82b-9099-4cb8-840c-b1dceb51291c)

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome, Firefox, Microsoft Edge

### What is the issue regarding ?

@trimble-oss/modus-web-components

### Priority

High

### What product/project are you using Modus Components for ?

QA

### What is your team/division name ?

QA

### Are you willing to contribute ?

None

**Comment by ElishaSamPeterPrabhu** [comment]
Since we are manually defining the SVGs and the fill color, like this
```
<div style="display: flex; justify-content: end; flex-wrap: wrap; margin-top: 1rem;">
  <modus-button button-style="borderless" aria-label="Add" title="Add" size="small" color="primary" disabled id="add">
    <svg width="24" height="24" viewBox="0 0 24 24">
      <path d="M0,0H24V24H0Z" fill="none" />
      <path d="M19,13H13v6H11V13H5V11h6V5h2v6h6Z" fill="#252a2e" />
    </svg>
   </modus-button>
```
The `fill="#252a2e"` is not handled for dark mode, causing the icon to appear invisible, like this when hovering:

![image](https://github.com/user-attachments/assets/c7fc1d9f-7445-4e98-891b-78f0308fd09c)

Can we replace this with the original Modus buttons and use icon-only? This way, both themes CSS will be properly handled.
