### ISSUE TITLE
Modus Select Component - Add a placeholder text

### ISSUE THREAD

**Issue by msankaran0712** [trimble-oss/modus-web-components#1476]
### Prerequisites

- [X] I have [searched](https://github.com/trimble-oss/modus-web-components/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/trimble-oss/modus-web-components/blob/main/CONTRIBUTING.md)

### Describe the issue

Missed a fix in #559 

For details contact @sarafarhat13

### What is the issue regarding ?

@trimble-oss/modus-web-components

### Priority

High

### What product/project are you using Modus Components for ?

modus

### What is your team/division name ?

modus

### Are you willing to contribute ?

None

**Comment by cjwinsor** [comment]
We can do Please select and allow user to change with a prop
