### ISSUE TITLE
Add a project for Modus Web components

### ISSUE THREAD

**Issue by msankaran0712** [trimble-oss/modus-web-components#1493]
### Prerequisites

- [X] I have [searched](https://github.com/trimble-oss/modus-web-components/issues?q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [Modus style guidelines](https://modus.trimble.com/components/web/introduction/)

### Proposal

We need a way to see the roadmap for Web components like it is shown in https://mui.com/x/react-data-grid/#upcoming-features

### What is the issue regarding ?

@trimble-oss/modus-web-components, Modus Web Components Website (Storybook)

### Priority

High

### What product/project are you using Modus Components for ?

modus

### What is your team/division name ?

modus

### Are you willing to contribute ?

None

**Comment by coliff** [comment]
https://github.com/orgs/trimble-oss/projects/15
It's currently private (not public) but you should have access. We can change this to a Roadmap if you prefer.
![image](https://github.com/trimble-oss/modus-web-components/assets/1212885/fd6ab11d-6fd4-4c72-9831-a99a0330cf6b)
