### ISSUE TITLE
[BUG] Modus Table - When Full width is false - Top panel and pagination is beyond the table

### ISSUE THREAD

**Issue by HarshithaNous** [trimble-oss/modus-web-components#1494]
### Prerequisites

- [X] I have [searched](https://github.com/trimble-oss/modus-web-components/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/trimble-oss/modus-web-components/blob/main/CONTRIBUTING.md)

### Describe the issue

Table component - When Full width is false - Top panel and pagination is beyond the table

Tested on PR: https://github.com/trimble-oss/modus-web-components/pull/1463

When full width is false Top panel and pagination is beyond the table as shown in the below screenshot:
![image](https://github.com/trimble-oss/modus-web-components/assets/129380495/5efe25a6-e48c-4ba5-be78-2c00dfcdfe34)

**Expected Result:** Top panel and Pagination should match the level of the table.

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome, Firefox, Microsoft Edge

### What is the issue regarding ?

@trimble-oss/modus-web-components

### Priority

Medium

### What product/project are you using Modus Components for ?

QA

### What is your team/division name ?

QA

### Are you willing to contribute ?

None

**Comment by msankaran0712** [comment]
Waiting for Tables Tiger team to confirm what is the expected behavior.

**Comment by msankaran0712** [comment]
This will be resolved in #1529
