### ISSUE TITLE
Modus Utility Panel Component - Bare Bones

### ISSUE THREAD

**Issue by enowak1031** [trimble-oss/modus-web-components#1505]
Modus Style guide:
https://modus.trimble.com/components/web/utility-panel/

Figma:
https://github.com/trimble-oss/website-modus.trimble.com/issues/565

**Comment by enowak1031** [comment]
We're waiting for David S. to let us know whether his team can work on this issue.

**Comment by msankaran0712** [comment]
As discussed with David S, Utility panel will be contributed by his team

Utility panel - https://jira.trimble.tools/browse/CREATOR-2003
Toolbar - https://jira.trimble.tools/browse/CREATOR-1736
Navbar - https://jira.trimble.tools/browse/CREATOR-1983
>2 button in web-component modal - https://jira.trimble.tools/browse/CREATOR-1957

**Comment by msankaran0712** [comment]
Moving this to Backlog as David confirmed that they will be able to resume the work only after November

**Comment by enowak1031** [comment]
@apaddock Is your team picking this issue up as part of the e-builder side navigation?

**Comment by cjwinsor** [comment]
- Panel slides out from the right
- Doesn't block or mask existing content
- Initial implementation will overlap content
- Future story to handle push
- Optional Header
    - Slot for Header content
    - Prop for showing close icon (to the right of slot)
- Slot for body content
- Future story for footer slot / buttons
- Future story for left orientation
- Future story for bottom orientation

e-Builder has a implementation already, I can help to share if helpful.
