### ISSUE TITLE
[BUG] Modus Table - Value Formatter - Column header is overlapping 

### ISSUE THREAD

**Issue by HarshithaNous** [trimble-oss/modus-web-components#1511]
### Prerequisites

- [X] I have [searched](https://github.com/trimble-oss/modus-web-components/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/trimble-oss/modus-web-components/blob/main/CONTRIBUTING.md)

### Describe the issue

Modus Table - Value Formatter - Column resized to minimum is not working as expected

When "Amount" column is resized to minimum, sort icon is overlapping on the border line. Please refer the below screenshot:
![image](https://github.com/trimble-oss/modus-web-components/assets/129380495/32df2f25-479f-4b1f-86dd-8ab451127d26)

When "Created At" column is resized to minimum, header comes outside the table border as shown in the below screenshot
![image](https://github.com/trimble-oss/modus-web-components/assets/129380495/c49b96d2-16f7-48f9-9cc5-debaa015e0a7)

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome, Firefox, Microsoft Edge

### What is the issue regarding ?

@trimble-oss/modus-web-components

### Priority

Medium

### What product/project are you using Modus Components for ?

QA

### What is your team/division name ?

QA

### Are you willing to contribute ?

None

**Comment by HarshithaNous** [comment]
Issue still exists:

Current behavior of the issue:
Sort icon is hidden and "Created At" header is not completely visible when the column is resized. Please refer the below screenshot:
![image](https://github.com/trimble-oss/modus-web-components/assets/129380495/b778daa6-0cf7-4143-a8bf-0f207eb34f1c)

Hence the issue is still open

**Comment by rthanga1** [comment]
Issue is fixed in the latest. Closing this one.
