### ISSUE TITLE
[BUG] Modus Table - data is empty on OnSortChanged when direction is reset to 'none'

### ISSUE THREAD

**Issue by aknoll-transporeon** [trimble-oss/modus-web-components#1518]
### Prerequisites

- [X] I have [searched](https://github.com/trimble-oss/modus-web-components/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/trimble-oss/modus-web-components/blob/main/CONTRIBUTING.md)

### Describe the issue

Modus Table - data disappears when ordering is reset to 'none'.

When using redux to store the state of the data that should be displayed in the table the following issue arises:

1. Change ordering of a column three times so it is reset to 'none'
2. On reset to 'none' the data inside the table disappears. Note: It is still part of the redux state

### Reduced test cases

A workaround for this case is to dispatch the loadAction again, albeit an ugly fix.

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome

### What is the issue regarding ?

@trimble-oss/modus-web-components

### What version of npm package are you using ?

0.1.45

### Priority

High

### What product/project are you using Modus Components for ?

Taskflow

### What is your team/division name ?

Squad Carbon / Transporeon

### Are you willing to contribute ?

Maybe

**Comment by msankaran0712** [comment]
@aknoll-transporeon Modus Data Table component will be deprecated very soon and replaced by the Modus Table ([preview](https://icy-ground-0374a1310-1517.centralus.1.azurestaticapps.net/?path=/docs/components-table--default))

**Comment by aknoll-transporeon** [comment]
@msankaran0712 is here a rough ETA when the new version will be available?

**Comment by msankaran0712** [comment]
@aknoll-transporeon We are planning to release the first version of the Modus Table by the end of August with the below functionalities,

- Editable Cells
- HyperLink in Cells
- Row Selection using row click and checkbox
- Filtering Columns
- Save Table Preferences (maybe)
