### ISSUE TITLE
Modus Table - Column Reorder - Summary row is blank

### ISSUE THREAD

**Issue by HarshithaNous** [trimble-oss/modus-web-components#1533]
### Prerequisites

- [X] I have [searched](https://github.com/trimble-oss/modus-web-components/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/trimble-oss/modus-web-components/blob/main/CONTRIBUTING.md)

### Describe the issue

Modus Table - Column Reorder - Summary row is blank

Verified on PR# https://deploy-preview-1485--modus-webcomponents.netlify.app/

Please refer the below screenshot:
![image](https://github.com/trimble-oss/modus-web-components/assets/129380495/e8c14a0f-f9c3-4929-82f9-f54edcf89c8e)

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome, Firefox, Microsoft Edge

### What is the issue regarding ?

@trimble-oss/modus-web-components

### Priority

Medium

### What product/project are you using Modus Components for ?

QA

### What is your team/division name ?

QA

### Are you willing to contribute ?

None

**Comment by Ankur-Koul** [comment]
When we turn on `summary-row`, we need to update the column data for a particular column to set `showTotal` property as `true`. But as of now, we are not able to edit column data in the storybook. This is not a bug.

**Comment by HarshithaNous** [comment]
As confirmed by Ankur this is not an issue and hence closing the defect.
