### ISSUE TITLE
Modus Autocomplete - Add support for Chips

### ISSUE THREAD

**Issue by msankaran0712** [trimble-oss/modus-web-components#1543]
### Prerequisites

- [X] I have [searched](https://github.com/trimble-oss/modus-web-components/issues?q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [Modus style guidelines](https://modus.trimble.com/components/web/introduction/)

### Proposal

We need it for adding column filters for the Modus Table component as mentioned in [Table Discussions](https://docs.google.com/document/d/1GZKc6vobaQDcTNEHMtC6zVyIga5PqkHdDL6abAkUZHs/edit#heading=h.it2rfg8dqbhv)

Prototype:
https://www.figma.com/file/7yC5vYgdbzqaEJDr566xAL/SUBMISSION-V1---Work-in-Progress?type=design&node-id=13-26855&mode=design&t=ff7qNLebZLL6o8Dy-0

### What is the issue regarding ?

@trimble-oss/modus-web-components

### Priority

High

### What product/project are you using Modus Components for ?

modus

### What is your team/division name ?

modus

### Are you willing to contribute ?

None

**Comment by msankaran0712** [comment]
Maha to create an issue for Styleguide and Figma

**Comment by msankaran0712** [comment]
Maha to check with Mike and Ryan if they can help us

**Comment by enowak1031** [comment]
@msankaran0712 Should this be closed?

**Comment by msankaran0712** [comment]
@enowak1031 Development was started by the contract dev team, but it is not completed
