### ISSUE TITLE
[BUG] Modus Table Component - Column Reorder/Visibility - editing panel Options after the first render not working

### ISSUE THREAD

**Issue by HarshithaNous** [trimble-oss/modus-web-components#1555]
### Prerequisites

- [X] I have [searched](https://github.com/trimble-oss/modus-web-components/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/trimble-oss/modus-web-components/blob/main/CONTRIBUTING.md)

### Describe the issue

**Scenario 1:**
Modus Table Component - Column Reorder - Panel Options - If the panel options is added in controls and when tried to remove certain columns on top panel of the canvas section, "Apply" button does not update the changes

Verified on PR: https://github.com/trimble-oss/modus-web-components/pull/1517

Please refer the below screenshot:
![image](https://github.com/trimble-oss/modus-web-components/assets/129380495/96313861-bc73-44df-aa48-79e86aba91bf)

The columns are still present:
![image](https://github.com/trimble-oss/modus-web-components/assets/129380495/d49ac23b-534a-4d6b-b41e-218142201b47)

**Scenario 2**
Modus Table Component - Column Visibility - Panel Options  - If the panel options is cleared on controls section the panel on canvas section should not display the options. 
However, the top panel on canvas section displays with the options, it is expected that the panel should not include any data.

Please refer the below screenshot:
![image](https://github.com/trimble-oss/modus-web-components/assets/129380495/acd3ef8d-4b4c-4dfc-a470-b2561b0e9401)

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome, Firefox, Microsoft Edge

### What is the issue regarding ?

@trimble-oss/modus-web-components

### Priority

Medium

### What product/project are you using Modus Components for ?

QA

### What is your team/division name ?

QA

### Are you willing to contribute ?

None

**Comment by rthanga1** [comment]
Issue doesn't seem to happen now. @rthanga1 to try to duplicate or close the issue

**Comment by jewel-shajan** [comment]
The property 'Panel Options' has been changed to 'Toolbar Options,' and this issue is not reproduced in the current storybook.
