### ISSUE TITLE
Add buttons group component

### ISSUE THREAD

**Issue by msankaran0712** [trimble-oss/modus-web-components#1558]
### Prerequisites

- [X] I have [searched](https://github.com/trimble-oss/modus-web-components/issues?q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [Modus style guidelines](https://modus.trimble.com/components/web/introduction/)

### Proposal

Created from https://github.com/trimble-oss/website-modus.trimble.com/issues/656

### What is the issue regarding ?

@trimble-oss/modus-web-components

### Priority

Medium

### What product/project are you using Modus Components for ?

modus

### What is your team/division name ?

modus

### Are you willing to contribute ?

None

**Comment by msankaran0712** [comment]
Wait for Styleguide and Figma

**Comment by msankaran0712** [comment]
@Gnirps00 can you please share with us the details about your division name and team/product name?

**Comment by Gnirps00** [comment]
Hi, I'm in Structures division and in SuDO team in Finland.

**Comment by msankaran0712** [comment]
> Hi, I'm in Structures division and in SuDO team in Finland.

Thank you @Gnirps00

**Comment by msankaran0712** [comment]
Assign this to Sprint 71

**Comment by enowak1031** [comment]
@soniakaukonen Do we have a submission for a toggle button? Your links show a button group--different.

**Comment by soniakaukonen** [comment]
@enowak1031 - we renamed it together at some point as button group when looking up the term on Bootstrap.

**Comment by msankaran0712** [comment]
Planned for 2024 Q1

**Comment by msankaran0712** [comment]
Guidelines for the component has to be present on Modus Styleguide and Figma before starting the work on Web components

cc @ElishaSamPeterPrabhu @rthanga1

**Comment by rthanga1** [comment]
@enowak1031 Please attach the figma link here

**Comment by enowak1031** [comment]
https://www.figma.com/file/wyfVJUHWRMkeCfdB38HFEE/Modus---Web?type=design&node-id=24902-8726&mode=design&t=BfJFiRI1DNz59y4q-0
