### ISSUE TITLE
[BUG] Modus Table - Scrolling PR - horizontal scroll appearing unnecessarily

### ISSUE THREAD

**Issue by HarshithaNous** [trimble-oss/modus-web-components#1561]
### Prerequisites

- [X] I have [searched](https://github.com/trimble-oss/modus-web-components/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/trimble-oss/modus-web-components/blob/main/CONTRIBUTING.md)

### Describe the issue

Modus Table - Scrolling PR - Horizontal scroll is not working as expected
Horizontal scroll appears even when the parent and table width are the same 850px

PR# - https://deploy-preview-1538--modus-webcomponents.netlify.app/

Please refer the below screenshot:
![image](https://github.com/trimble-oss/modus-web-components/assets/129380495/92473235-8e4f-4f0e-a11f-5bb898b8854c)

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome, Firefox, Microsoft Edge

### What is the issue regarding ?

@trimble-oss/modus-web-components

### Priority

Medium

### What product/project are you using Modus Components for ?

QA

### What is your team/division name ?

QA

### Are you willing to contribute ?

None

**Comment by rthanga1** [comment]
I can reproduce this in codepen https://codepen.io/ramaraj-trimble/pen/PoLYYPG

**Comment by rthanga1** [comment]
This is a bug and needs to be fixed.

**Comment by jewel-shajan** [comment]
The issue has been tested and was not reproduced in the current storybook.
![table-scrollbarhorizontal](https://github.com/user-attachments/assets/3e58e039-a86e-4dd4-8631-0dd54a417d2e)
