### ISSUE TITLE
Modus components inside an angular web app is too small

### ISSUE THREAD

**Issue by roaldjap** [trimble-oss/modus-web-components#1569]
### Describe the issue

Hi guys,

I was trying to test this modus web components design framework and checking the compatibility within some of our software products. For my case, I am using this on Angular 15 (and would go for Angular 16 soon)

The components are working but it seems that it was too zoomed out (or too small) for a reason. check below.

![image](https://github.com/trimble-oss/website-modus.trimble.com/assets/1312938/0edcf05d-d255-418f-bacd-86908ff6cda5)

is there a way to override some of the css classes here? I have seen that the `#shadow-root` stops me to do some things.

![image](https://github.com/trimble-oss/website-modus.trimble.com/assets/1312938/a3976272-6616-46e3-8515-57deb99f5cd8)

Thanks

PS.
I have also added `size=large` seems too small. (has computed height size of `30px`) 

![image](https://github.com/trimble-oss/website-modus.trimble.com/assets/1312938/ede3ef7c-c94f-4b9b-8379-0c45079a40c1)

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome

**Comment by msankaran0712** [comment]
Thank you for submitting the issue @roaldjap We are working on it.

**Comment by msankaran0712** [comment]
@roaldjap can you please share with us the details about your division name and team/product name?

**Comment by msankaran0712** [comment]
Will wait for @egunther39 to comment

**Comment by msankaran0712** [comment]
Maha to check with Eric and Randall

**Comment by cjwinsor** [comment]
@roaldjap Is it possible to give us a reproduction, otherwise this ticket may be closed.

**Comment by roaldjap** [comment]
@cjwinsor I tried to use it with angular material - followed through the documentation.

on anycase, I decided to revert it back to angular material (and use its own built in chips and autocomplete). I guess this creates new reset and isolate it that is why it is small and not worth to use it on our current projects.

IMO, I think modus would be perfectly fine if we need to recreate our new apps initially with it and not on current projects.

I came from Geospatial (MapViewer UI) NZ division - maybe, its worth closing this thread now.

**Comment by ElishaSamPeterPrabhu** [comment]
The autocomplete depends on the width of the container its inside
![Image](https://github.com/user-attachments/assets/7320e2c4-115a-4245-b4f1-154807669f58)

https://stackblitz.com/edit/angular-exprqa?file=src%2Findex.html
So closing the issue
