### ISSUE TITLE
modus-chip's close button does not work on windows but works on mac

### ISSUE THREAD

**Issue by roaldjap** [trimble-oss/modus-web-components#1570]
### Describe the issue

https://modus-web-components.trimble.com/?path=/docs/components-chip--default - on this documentation close button & checkmark small  does not work on windows but works on mac for some reason.

![2023-07-24 15-07-41](https://github.com/trimble-oss/website-modus.trimble.com/assets/1312938/72cd3fa1-eddc-4aa5-b0c7-87b39e58ff07)

and also, I have added this component on our angular app, `show-close` works but it does not do any close action if close button is clicked.

```html
<div class="modus-wrapper">
      <modus-chip
         class="mb-1"
         [chip-style]="solid"
         value="Bryan Smith"
         show-close="true"
       />
        ...
 </div>
```

on my app, I have this sample static component. the chip won't do close action.

![2023-07-24 15-16-44](https://github.com/trimble-oss/website-modus.trimble.com/assets/1312938/3c068d30-b533-41c1-84fd-57c25069544b)

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

All browsers

**Comment by msankaran0712** [comment]
Thank you for submitting the issue @roaldjap 
The current behaviour for Chips is it exposes an event `closeClick` when the close icon is clicked, so the users can decide whether to hide the chip.

**Comment by msankaran0712** [comment]
@roaldjap Please feel free to reopen the issue if it is not resolved.
