### ISSUE TITLE
[BUG] Modus Table - Scrolling - Keyboard navigation - When user hit on tab to resize a column, the header border line in blue is thin

### ISSUE THREAD

**Issue by HarshithaNous** [trimble-oss/modus-web-components#1578]
### Prerequisites

- [X] I have [searched](https://github.com/trimble-oss/modus-web-components/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/trimble-oss/modus-web-components/blob/main/CONTRIBUTING.md)

### Describe the issue

Modus Table - Scrolling - Keyboard navigation - When user hit on tab to resize a column, the header border line in blue is thin 

Tested on PR - https://deploy-preview-1538--modus-webcomponents.netlify.app/

Please refer the below screenshot:
<img width="953" alt="image" src="https://github.com/trimble-oss/modus-web-components/assets/129380495/d20067cf-a75d-4b44-9908-de5b85e874f3">

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome, Firefox, Microsoft Edge

### What is the issue regarding ?

@trimble-oss/modus-web-components

### Priority

Medium

### What product/project are you using Modus Components for ?

QA

### What is your team/division name ?

QA

### Are you willing to contribute ?

None

**Comment by msankaran0712** [comment]
Not happening any more
