### ISSUE TITLE
[BUG] Modus Table - Controls not syncing immediately

### ISSUE THREAD

**Issue by HarshithaNous** [trimble-oss/modus-web-components#1580]
### Prerequisites

- [X] I have [searched](https://github.com/trimble-oss/modus-web-components/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/trimble-oss/modus-web-components/blob/main/CONTRIBUTING.md)

### Describe the issue

Modus Table - Controls not syncing immediately 

Tested on PR - https://deploy-preview-1576--modus-webcomponents.netlify.app/

Pagination: In the controls section if Pagination control is set to "True", the changed is not applied immediately. Only after the web page is refreshed changes is reflected
![2023-07-26_21h47_23](https://github.com/trimble-oss/modus-web-components/assets/129380495/92336879-2a55-4cb7-af42-e9cb0accd1e6)

Rows-expandable: In the controls section if Rows-expandable control is set to "False", the changes is not applied immediately. Only after the web page is refreshed the changes is reflected
![2023-07-26_22h06_24](https://github.com/trimble-oss/modus-web-components/assets/129380495/dc2dbc74-fe56-4c28-94b2-43fd3734e181)

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome, Firefox, Microsoft Edge

### What is the issue regarding ?

@trimble-oss/modus-web-components

### Priority

Medium

### What product/project are you using Modus Components for ?

QA

### What is your team/division name ?

QA

### Are you willing to contribute ?

None

**Comment by rthanga1** [comment]
This is working fine now. To be closed

**Comment by rthanga1** [comment]
Reopen if anybody faces this issue.
