### ISSUE TITLE
Modus Alert component - Responsiveness - Alert - with Link - Text is not appropriate when the canvas width is reduced

### ISSUE THREAD

**Issue by HarshithaNous** [trimble-oss/modus-web-components#1581]
### Prerequisites

- [X] I have [searched](https://github.com/trimble-oss/modus-web-components/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/trimble-oss/modus-web-components/blob/main/CONTRIBUTING.md)

### Describe the issue

Modus Alert component - Responsiveness - Alert-with Link - Text is not appropriate when the canvas width is reduced

Please refer the below screeshot:
<img width="925" alt="image" src="https://github.com/trimble-oss/modus-web-components/assets/129380495/0cd1a4c8-cb4a-418d-a629-64a9c39014a2">

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome, Firefox, Microsoft Edge

### What is the issue regarding ?

@trimble-oss/modus-web-components

### Priority

Low

### What product/project are you using Modus Components for ?

QA

### What is your team/division name ?

QA

### Are you willing to contribute ?

None

**Comment by rthanga1** [comment]
Cannot reproduce now
https://codepen.io/ramaraj-trimble/pen/zYbOYPB

**Comment by rthanga1** [comment]
This is a bug and it needs to be fixed. Even though we have a guideline to not have more than 5-10 words, the alert should technically accomodate longer sentences as well. The height of the alert should grow as the text.
