### ISSUE TITLE
Angular npm Publish GH Action fails

### ISSUE THREAD

**Issue by coliff** [trimble-oss/modus-web-components#1588]
### Prerequisites

- [X] I have [searched](https://github.com/trimble-oss/modus-web-components/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/trimble-oss/modus-web-components/blob/main/CONTRIBUTING.md)

### Describe the issue

Error:
`Cannot find module '@trimble-oss/modus-web-components' or its corresponding type declarations.`

See logs here:
https://github.com/trimble-oss/modus-web-components/actions/workflows/publish-angular.yml

I don't know how to fix right now, but something to do with relative paths or something?
https://stackoverflow.com/questions/37548734/tsc-throws-ts2307-cannot-find-module-for-a-local-file

For now we need to publish manually via the CLI until this is fixed.

**Comment by cjwinsor** [comment]
@cjwinsor Take a look for short and long term solution
