### ISSUE TITLE
[BUG] Modus Table - Summary row border line is thick

### ISSUE THREAD

**Issue by HarshithaNous** [trimble-oss/modus-web-components#1589]
### Prerequisites

- [X] I have [searched](https://github.com/trimble-oss/modus-web-components/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/trimble-oss/modus-web-components/blob/main/CONTRIBUTING.md)

### Describe the issue

Modus Table - Summary row border line is thick compared to header row border line

Tested on PR#: https://deploy-preview-1517--modus-webcomponents.netlify.app/

Please refer the below screenshot:
<img width="954" alt="image" src="https://github.com/trimble-oss/modus-web-components/assets/129380495/edd8b4cc-86fb-42b2-951a-32ce70535d68">

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome, Firefox, Microsoft Edge

### What is the issue regarding ?

@trimble-oss/modus-web-components

### Priority

Medium

### What product/project are you using Modus Components for ?

QA

### What is your team/division name ?

QA

### Are you willing to contribute ?

None

**Comment by rthanga1** [comment]
It seems to be working fine now. Closing this one
