### ISSUE TITLE
Modus Content tree - No enough space between the tree view indicator line and drag and drop icon

### ISSUE THREAD

**Issue by HarshithaNous** [trimble-oss/modus-web-components#1596]
### Prerequisites

- [X] I have [searched](https://github.com/trimble-oss/modus-web-components/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/trimble-oss/modus-web-components/blob/main/CONTRIBUTING.md)

### Describe the issue

Modus Content tree - No enough space between the tree view indicator line and drag and drop icon

Please refer the below screenshot:
<img width="598" alt="image" src="https://github.com/trimble-oss/modus-web-components/assets/129380495/3a68cc6f-21f2-4607-847f-c70a126f188c">

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome, Firefox, Microsoft Edge

### What is the issue regarding ?

@trimble-oss/modus-web-components

### Priority

Medium

### What product/project are you using Modus Components for ?

QA

### What is your team/division name ?

QA

### Are you willing to contribute ?

None

**Comment by msankaran0712** [comment]
@soniakaukonen to link the Figma issue

**Comment by soniakaukonen** [comment]
@msankaran0712  https://github.com/trimble-oss/modus/issues/473

**Comment by rthanga1** [comment]
@enowak1031 @egunther39 Can you provide guidelines? The figma has an example with drag handle and another one with highlighter. But it doesn't have an example with both. Please advise.

https://www.figma.com/file/wyfVJUHWRMkeCfdB38HFEE/Modus---Web?type=design&node-id=5350-22364&mode=design&t=psa94OESLQgkDfVw-11

**Comment by cjwinsor** [comment]
https://github.com/trimble-oss/modus/issues/542
