### ISSUE TITLE
Modus Content tree - Custom Action Bar - Keyboard navigation is not there for Drag and drop option

### ISSUE THREAD

**Issue by HarshithaNous** [trimble-oss/modus-web-components#1597]
### Prerequisites

- [X] I have [searched](https://github.com/trimble-oss/modus-web-components/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/trimble-oss/modus-web-components/blob/main/CONTRIBUTING.md)

### Describe the issue

Modus Content tree - Custom Action Bar - Keyboard navigation is not there for Drag and drop option

<img width="666" alt="image" src="https://github.com/trimble-oss/modus-web-components/assets/129380495/82b23d68-24e9-4978-869d-8bc8405dffa1">

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome, Firefox, Microsoft Edge

### What is the issue regarding ?

@trimble-oss/modus-web-components

### Priority

Medium

### What product/project are you using Modus Components for ?

QA

### What is your team/division name ?

QA

### Are you willing to contribute ?

None

**Comment by cjwinsor** [comment]
Behavior should be similar to the table header moving.

**Comment by cjwinsor** [comment]
The focus border will be handled with #2162 

Goal of this ticket is to allow the reorder icon to be tabbed into.  On enter or space, it "pops out" and with the up and down arrows it will move the blue placement border and on space or enter will commit the location and move the item.
