### ISSUE TITLE
Button still in pressed state after click/action is done

### ISSUE THREAD

**Issue by adinc-transporeon** [trimble-oss/modus-web-components#1604]
### Prerequisites

- [X] I have [searched](https://github.com/trimble-oss/modus-web-components/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/trimble-oss/modus-web-components/blob/main/CONTRIBUTING.md)

### Describe the issue

-button goes from default state to hover state (/)
-button goes from hover to pressed state (/)
-after button clicked --> button goes not from pressed state back to default/hover (x)
 --> you have to select something else (or click somewhere else) to set it back to default 

On questions, please ask  --> mailto:Hannah.Boose@transporeon.com (UX)

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome, Safari, Firefox

### What is the issue regarding ?

@trimble-oss/modus-angular-components

### Priority

Low

### What product/project are you using Modus Components for ?

Taskflow

### What is your team/division name ?

Squad Carbon

### Are you willing to contribute ?

None

### Are you using Modus Web Components in production ?

not yet

**Comment by msankaran0712** [comment]
Hey @adinc-transporeon, any updates?

**Comment by adinc-transporeon** [comment]
Hi, @msankaran0712 I contacted Hannah today, your mail to Hannah get lost. She will provide today via email more information about the defect. Its not about hovering state, its about the selected state (for me focus and selected is the same).

**Comment by msankaran0712** [comment]
@adinc-transporeon From the last email conversation, I see there are no more questions/issues to address. Please feel free to reopen the issue if it is not resolved.
