### ISSUE TITLE
Remove unused variants from icon-only buttons

### ISSUE THREAD

**Issue by soniakaukonen** [trimble-oss/modus-web-components#1626]
Icon-only buttons were originally set up on Figma to 32-40-48-56. 
56px has been removed as it is Mobile specific
40px is not supported format and is removed.

We need a small variant button 24 px with 16 px icon placeholder. 
32 px with 24 px is a default variant.

Figma:
https://github.com/trimble-oss/modus/issues/475

**Comment by soniakaukonen** [comment]
@msankaran0712 as discussed. Sorry for the mishap.

**Comment by msankaran0712** [comment]
Assign this to Sprint 71

**Comment by soniakaukonen** [comment]
Christian working on updating Modus Bootstrap styles first - lots of problems spotted. The icon-only buttons don't have box shadow and they should when focused.

**Comment by msankaran0712** [comment]
@egunther39 Can you please tell us which variant should be removed?

**Comment by msankaran0712** [comment]
@ElishaSamPeterPrabhu To check the Modus Buttons(Icon-only variant) component on Figma and spot the differences

**Comment by cjwinsor** [comment]
Lets audit the icon only button completely to ensure complete match to style guide.  List out any changes made in PR that bring it into alignment.
