### ISSUE TITLE
Modus AutoComplete - Enable Multi-Selection

### ISSUE THREAD

**Issue by msankaran0712** [trimble-oss/modus-web-components#1627]
### Prerequisites

- [X] I have [searched](https://github.com/trimble-oss/modus-web-components/issues?q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [Modus style guidelines](https://modus.trimble.com/components/web/introduction/)

### Proposal

We need some guidelines for how to perform multi-selection on Autocomplete dropdown with chips so that it can be used as a column filter for Table component.

Related to #1543 

Example:
https://mui.com/material-ui/react-autocomplete/#multiple-values
https://mui.com/material-ui/react-autocomplete/#playground
https://mui.com/material-ui/react-autocomplete/#limit-tags

### Motivation and context

Modus Table component filters.

### What is the issue regarding ?

@trimble-oss/modus-web-components

### Priority

High

### What product/project are you using Modus Components for ?

modus

### What is your team/division name ?

modus

### Are you willing to contribute ?

None

**Comment by msankaran0712** [comment]
Add this to styleguide and figma

**Comment by msankaran0712** [comment]
use the below for reference,

https://mui.com/material-ui/react-autocomplete/#multiple-values
https://mui.com/material-ui/react-autocomplete/#limit-tags

**Comment by prashanth-offcl** [comment]
Closing this issue as the changes are already merged
