### ISSUE TITLE
Toast: show pointer cursor on close icon hover

### ISSUE THREAD

**Issue by yohernandez** [trimble-oss/modus-web-components#1629]
### Prerequisites

- [X] I have [searched](https://github.com/trimble-oss/modus-web-components/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/trimble-oss/modus-web-components/blob/main/CONTRIBUTING.md)

### Describe the issue

The pointer cursor should show when hovering on the close icon in the Toast component.
Modus Style Guide:
![image](https://github.com/trimble-oss/modus-web-components/assets/48927186/e063f9fd-f084-43f9-9959-62698be902e9)
Modus Web Components:
![image](https://github.com/trimble-oss/modus-web-components/assets/48927186/cca3ec60-d9c4-4ed6-a3d3-eae990b6c173)

### What is the issue regarding ?

@trimble-oss/modus-web-components

### What version of npm package are you using ?

0.1.49

### Priority

Low

### What product/project are you using Modus Components for ?

e-builder

### What is your team/division name ?

e-builder

### Are you willing to contribute ?

Yes

**Comment by msankaran0712** [comment]
@enowak1031 Approving the issue because it is a valid bug

**Comment by msankaran0712** [comment]
@yohernandez Please check with @coliff for when to expect the next release
