### ISSUE TITLE
Misalignment of date picker calendar with actual calendar days

### ISSUE THREAD

**Issue by rumeskg** [trimble-oss/modus-web-components#1662]
### Describe the issue

I want to report an issue with the date picker. The problem is that the calendar dates and days shown don't match the actual calendar. Every month, the first date is set as Sunday, which is incorrect. This could confuse users who rely on accurate dates. Please look into this and fix it. Thank you.

![image](https://github.com/trimble-oss/website-modus.trimble.com/assets/142714679/35c57c4f-be10-4ca8-af00-a794566064c6)

### What operating system(s) are you seeing the problem on?

Linux

### What browser(s) are you seeing the problem on?

Chrome

**Comment by msankaran0712** [comment]
@rumeskg Thank you for submitting the issue. Can you please let us know your team details? Project/team name and division name.

**Comment by msankaran0712** [comment]
Also @rumeskg Could you kindly let us know if your team is interested in fixing the issue ?

**Comment by rumeskg** [comment]
> @rumeskg Thank you for submitting the issue. Can you please let us know your team details? Project/team name and division name.

Product: FleetCockpit
Module: Document Management System (redesign using Modus)
Team Name: Fleetworks
Division Name: TTM EU
