### ISSUE TITLE
Issue with Manual Entry of Dates in Date Picker Field

### ISSUE THREAD

**Issue by rumeskg** [trimble-oss/modus-web-components#1667]
### Prerequisites

- [X] I have [searched](https://github.com/trimble-oss/modus-web-components/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/trimble-oss/modus-web-components/blob/main/CONTRIBUTING.md)

### Describe the issue

I'd like to bring attention to a specific issue related to manually entering dates in the date picker field, rather than selecting them from the calendar. In such cases, I've observed the following problems:

**Incorrect Handling of Invalid Dates:** When entering an invalid date like "31-09-2023," the calendar interprets it as "01-09-2023." This behaviour is inaccurate, and it would be more appropriate to implement validation that highlights or notifies users about such errors.

**Handling of Invalid Dates like 30-02-2023:** Similarly, when inputting an invalid date like "30-02-2023," the calendar interprets it as "02-03-2023." and it would be beneficial to implement validation that either highlights the error or prevents the entry of such invalid dates during manual input.

I believe addressing these issues would improve the accuracy and reliability of the date picker's manual input functionality. Thank you for your attention to this matter.

### What operating system(s) are you seeing the problem on?

Linux

### What browser(s) are you seeing the problem on?

Chrome

### What is the issue regarding ?

@trimble-oss/modus-web-components

### Priority

High

### What product/project are you using Modus Components for ?

Document Management System (redesign using Modus)

### What is your team/division name ?

Team: Fleetworks, Division: TTM EU

### Are you willing to contribute ?

No

### Are you using Modus Web Components in production ?

We are about to use for our upcoming release

**Comment by msankaran0712** [comment]
Confirmed with Srinivasan Chandrasekaran, his team will be able to contribute by Jan 2024

**Comment by cjwinsor** [comment]
@cjwinsor Check what work was done since this ticket was opened to establish if this is still an issue  or what needs to be done to correct if not.

**Comment by cjwinsor** [comment]
Goal is to verify 100% that this is no longer an issue so this ticket can be closed.  The assumption is that a past ticket may have resolve this by handling formatting.

**Comment by ElishaSamPeterPrabhu** [comment]
> Goal is to verify 100% that this is no longer an issue so this ticket can be closed. The assumption is that a past ticket may have resolve this by handling formatting.

@cjwinsor 
The issue doesn't exist in the latest version ,validation is handled .


https://github.com/trimble-oss/modus-web-components/assets/122255626/e91a008d-b50c-421a-bdfe-d663171ec38d


Verified in storybook
