### ISSUE TITLE
Modus List - Missing a borderless variant  

### ISSUE THREAD

**Issue by msankaran0712** [trimble-oss/modus-web-components#1668]
### Prerequisites

- [X] I have [searched](https://github.com/trimble-oss/modus-web-components/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/trimble-oss/modus-web-components/blob/main/CONTRIBUTING.md)

### Describe the issue

Why only Modus Bootstrap has a borderless list ?

https://modus-bootstrap.trimble.com/components/lists/?q=list#borderless-lists

### What is the issue regarding ?

@trimble-oss/modus-web-components

### Priority

Medium

### What product/project are you using Modus Components for ?

modus

### What is your team/division name ?

modus

### Are you willing to contribute ?

None

**Comment by enowak1031** [comment]
@egunther39 or @soniakaukonen Do we have this in Figma and Style Guide?

**Comment by egunther39** [comment]
@enowak1031 - Borderless list items are missing in both style guide & Figma

**Comment by msankaran0712** [comment]
Completed in https://github.com/trimble-oss/modus-web-components/issues/1770
