### ISSUE TITLE
Icon Map copy icon not working

### ISSUE THREAD

**Issue by acomsto** [trimble-oss/modus-web-components#1680]
### Prerequisites

- [X] I have [searched](https://github.com/trimble-oss/modus-web-components/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/trimble-oss/modus-web-components/blob/main/CONTRIBUTING.md)

### Describe the issue

Copy icon from the IconMap when used in a data table row action renders as a square
![image](https://github.com/trimble-oss/modus-web-components/assets/107583407/8e2889d6-52f1-486f-927e-06fd8babfaf5)

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome

### What is the issue regarding ?

@trimble-oss/modus-web-components

### What version of npm package are you using ?

0.1.52

### Priority

Medium

### What product/project are you using Modus Components for ?

Work Center

### What is your team/division name ?

Trimble Viewpoint

### Are you willing to contribute ?

None

**Comment by ElishaSamPeterPrabhu** [comment]
The copy icon is appearing testing it in the latest version (0.5.1)

**Comment by ElishaSamPeterPrabhu** [comment]
The copy icon is appearing testing it in the latest version (0.5.1)
