### ISSUE TITLE
Sun Icon includes incorrect class name `icon-moon`

### ISSUE THREAD

**Issue by ryan-henness-trimble** [trimble-oss/modus-web-components#1681]
### Prerequisites

- [X] I have [searched](https://github.com/trimble-oss/modus-web-components/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/trimble-oss/modus-web-components/blob/main/CONTRIBUTING.md)

### Describe the issue

The class name for the sun icon is `icon-moon`

### What operating system(s) are you seeing the problem on?

Windows, macOS, Android, iOS, Linux

### What browser(s) are you seeing the problem on?

Chrome, Safari, Firefox, Microsoft Edge, Opera

### What is the issue regarding ?

@trimble-oss/modus-web-components

### What version of npm package are you using ?

v0.1.52

### Priority

Medium

### What product/project are you using Modus Components for ?

Work Center

### What is your team/division name ?

Trimble Viewpoint

### Are you willing to contribute ?

None

**Comment by HarieshPugazhendhi** [comment]
The issue was addressed by verifying the class name for the sun icon, which was found to be correctly named as "icon-sun" and not "icon-moon". Therefore, no changes were required, and the class name remains as "icon-sun".
