### ISSUE TITLE
ModusButton with 'borderless' style ignores color mode

### ISSUE THREAD

**Issue by leosole-trimble** [trimble-oss/modus-web-components#1693]
### Prerequisites

- [X] I have [searched](https://github.com/trimble-oss/modus-web-components/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/trimble-oss/modus-web-components/blob/main/CONTRIBUTING.md)

### Describe the issue

When using `ModusButton` with a `borderless` style, the color mode is ignored and the primary color is always applied.

### What is the issue regarding ?

@trimble-oss/modus-web-components

### What version of npm package are you using ?

0.1.52-react18

### Priority

Low

### What product/project are you using Modus Components for ?

Trimble DVIR

### What is your team/division name ?

Camaleão/Transportation

### Are you willing to contribute ?

Maybe

### Are you using Modus Web Components in production ?

no

**Comment by msankaran0712** [comment]
Hey @leosole-trimble if you meant a borderless text button, it supports only a primary color
![image](https://github.com/trimble-oss/modus-web-components/assets/50131391/5c3cf6a7-d031-4dd0-8fd5-fe9461a7c111)

**Comment by leosole-trimble** [comment]
Oh, sorry. I didn't see this. I'm closing this one than.
