### ISSUE TITLE
Using a secondary / danger color modus-button doesn't display correctly

### ISSUE THREAD

**Issue by coliff** [trimble-oss/modus-web-components#1694]
### Prerequisites

- [X] I have [searched](https://github.com/trimble-oss/modus-web-components/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/trimble-oss/modus-web-components/blob/main/CONTRIBUTING.md)

### Describe the issue

Using a secondary color modus-button doesn't appear to work correctly.

```html
<modus-button color="secondary">Secondary</modus-button>
```

### Reduced test cases

1. Go to: https://coliff.github.io/modus-web-components-example/#buttons
2. Check the button to the right of the first Primary button
3. If you hover over it it shows the hover state.

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Microsoft Edge

### What is the issue regarding ?

@trimble-oss/modus-web-components

### What version of npm package are you using ?

Latest

### Priority

Medium

### What product/project are you using Modus Components for ?

Modus

### What is your team/division name ?

Modus

### Are you willing to contribute ?

Yes

**Comment by coliff** [comment]
Primary button has this:
![image](https://github.com/trimble-oss/modus-web-components/assets/1212885/edb9facc-c107-445b-a2f2-6f8243a55faf)

Secondary button has this:
![image](https://github.com/trimble-oss/modus-web-components/assets/1212885/f8e2f343-a59a-4744-9f8c-e36908ad72f1)

SO I'll add those fallback values to fix this issue.

**Comment by coliff** [comment]
This is also an issue with the danger button as reported by Olivia Dendinger on Google Chat.

**Comment by msankaran0712** [comment]
It seems that the issue occurs when the theme file located at "./node_modules/@trimble-oss/modus-web-components/dist/modus-web-components/modus-web-components.css" is not referenced, as the fallback colors appear to be missing.

**Comment by msankaran0712** [comment]
@enowak1031 @coliff I fixed the issue because while investigating I was also able to fix it.
