### ISSUE TITLE
Modus Table - Table should resize to accommodate side panels

### ISSUE THREAD

**Issue by msankaran0712** [trimble-oss/modus-web-components#1703]
### Prerequisites

- [X] I have [searched](https://github.com/trimble-oss/modus-web-components/issues?q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [Modus style guidelines](https://modus.trimble.com/components/web/introduction/)

### Proposal

![image](https://github.com/trimble-oss/modus-web-components/assets/50131391/82cd4073-d408-4e9d-b6ee-ce6fa2784b7f)

### What is the issue regarding ?

@trimble-oss/modus-web-components

### Priority

Medium

### What product/project are you using Modus Components for ?

modus

### What is your team/division name ?

modus

### Are you willing to contribute ?

None

**Comment by enowak1031** [comment]
This option is already available. The Utility Panel properties can be set to push.
