### ISSUE TITLE
Update Modus date picker to accept inputs in different formats

### ISSUE THREAD

**Issue by yevhenkravets** [trimble-oss/modus-web-components#1709]
### Prerequisites

- [X] I have [searched](https://github.com/trimble-oss/modus-web-components/issues?q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [Modus style guidelines](https://modus.trimble.com/components/web/introduction/)

### Proposal

Update Modus date picker to accept inputs in different formats:

1. input with 2 digit year:   01.02.20 = view: Jan 2, 2020 
2. input with alpha, no symbols:   Jan 02 2020 = view: Jan 2, 2020
3. input with dash/dot/slash separators: 01-02-2020, 01.02.20, 01/02/2020 = view: Jan 2, 2020
4. input full month alpha: January 2, 2020 = view: Jan 2, 2020

All Inputs should be properly converted to the correct format specified on the “format“ attribute.

### What is the issue regarding ?

@trimble-oss/modus-web-components

### Priority

Medium

### What product/project are you using Modus Components for ?

e-Builder

### What is your team/division name ?

e-Builder

### Are you willing to contribute ?

Yes

**Comment by msankaran0712** [comment]
Maha to check with Carlos and @yevhenkravets

**Comment by msankaran0712** [comment]
Related to https://github.com/trimble-oss/modus/issues/486

**Comment by msankaran0712** [comment]
Modus Approved and the issue is ready to be worked on by anyone
