### ISSUE TITLE
Date Picker year up and down arrow aria-labels are incorrect

### ISSUE THREAD

**Issue by acomsto** [trimble-oss/modus-web-components#1718]
### Prerequisites

- [X] I have [searched](https://github.com/trimble-oss/modus-web-components/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/trimble-oss/modus-web-components/blob/main/CONTRIBUTING.md)

### Describe the issue

The area labels attached to the up and down arrows for the year are reversed. The arrow that increases the year is labeled "Previous Year" and the arrow that decreases the year is labeled "Next Year". 

It also looks like both arrow icons have the class icon-triangle-down

### What operating system(s) are you seeing the problem on?

Windows, macOS, Android, iOS, Linux

### What browser(s) are you seeing the problem on?

Chrome, Safari, Firefox, Microsoft Edge, Opera

### What is the issue regarding ?

@trimble-oss/modus-web-components

### What version of npm package are you using ?

v0.1.52

### Priority

Low

### What product/project are you using Modus Components for ?

Work Center

### What is your team/division name ?

Trimble Viewpoint

### Are you willing to contribute ?

Yes

**Comment by msankaran0712** [comment]
hey @acomsto your PR is approved and merged. Thank you for the contribution.
