### ISSUE TITLE
ModusTable : Buttons and Icons can be inside the cell

### ISSUE THREAD

**Issue by Jayanthbalakrishnan** [trimble-oss/modus-web-components#1724]
### Prerequisites

- [X] I have [searched](https://github.com/trimble-oss/modus-web-components/issues?q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [Modus style guidelines](https://modus.trimble.com/components/web/introduction/)

### Proposal

**Use Case :** 
- Table cell can have button/icon for rich user experience

![image](https://github.com/trimble-oss/modus-web-components/assets/129956254/e3eefe78-8bdf-41a7-9ede-52c3f1b2ba0b)

### What is the issue regarding ?

@trimble-oss/modus-web-components

### Priority

Medium

### What product/project are you using Modus Components for ?

Trimble Construction Cloud

### What is your team/division name ?

Industry Clouds

### Are you willing to contribute ?

Maybe

### Are you using Modus Web Components in production ?

yes, https://console.construction.cloud/#/workflow

**Comment by msankaran0712** [comment]
Check with Djenifer if her team can contribute or wait for top priority items to be finished first for the table component

**Comment by msankaran0712** [comment]
hey @Jayanthbalakrishnan in the screenshot, do both the icons perform some action ? Also can you please confirm if the issue https://github.com/trimble-oss/modus-web-components/issues/1729 is what your team needs too ?

**Comment by Jayanthbalakrishnan** [comment]
![image](https://github.com/trimble-oss/modus-web-components/assets/129956254/bcb62f18-5380-415a-b8de-47ee9ebc99fe)


**Our use case**  : 
This page is basically displaying list of users belongs to the accounts, 
When customer is clicking on, 
**info icon**, page should be redirected to different page / dialog box - that should have more information about the user.
**more icon**, page should be displayed with small pop up like **menus** to add further more actions like **edit / delete button**

**Comment by cjwinsor** [comment]
This use case can be handled with Row Actions #1729
