### ISSUE TITLE
Request for third button in modal window

### ISSUE THREAD

**Issue by palakchaudhary18** [trimble-oss/modus-web-components#1728]
### Prerequisites

- [X] I have [searched](https://github.com/trimble-oss/modus-web-components/issues?q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [Modus style guidelines](https://modus.trimble.com/components/web/introduction/)

### Proposal

The current modus to two buttons options primary and secondary. For our use case we need three buttons  'Close', 'Watch later' and 'Request quote'.

Attaching the mockup screenshot
![image](https://github.com/trimble-oss/modus-web-components/assets/145763175/3a0f7c8e-13b4-4985-9be2-42f5129385d3)

### Motivation and context

The requirement is to show a banner/video. The user is given three options to select 'Close', 'Watch later' and 'Request quote'.
Close : To closes the dialog and user will not be shown this popup again (this means that user does not want to see this popup again).
Watch later :  The user does not want to see it now but would like to see after some time. 
Request quote : The user has seen the video and wants us to connect the team. 

checkbox : To get the user consent.

### What is the issue regarding ?

@trimble-oss/modus-web-components,@trimble-oss/modus-angular-components

### Priority

High, Medium

### What product/project are you using Modus Components for ?

Transporeon TPW home page 

### What is your team/division name ?

Transporeon, Platform Services, Squad Coffee

### Are you willing to contribute ?

yes

### Are you using Modus Web Components in production ?

yes

**Comment by msankaran0712** [comment]
As discussed with @egunther39 @soniakaukonen @enowak1031 users should be able to add only the buttons from  [Structural progression](https://modus.trimble.com/components/web/buttons/?q=button#structural-progressio) and [Color progression](https://modus.trimble.com/components/web/buttons/?q=button#color-progression) in the same order. And users cannot mix and match the buttons.

**Comment by msankaran0712** [comment]
We are having a challenge in setting up the configuration to accept buttons for the Modal component that follows Structural progression/Color Progression. 

If we keep it flexible by having a simple array of buttons, technically will be able to place any button at any position.

**Comment by enowak1031** [comment]
@msankaran0712 Does this need work to make the modals configurable?

**Comment by msankaran0712** [comment]
This was a contribution from Palak Chaudhary Transporeon team
