### ISSUE TITLE
Modus Table - Add row actions 

### ISSUE THREAD

**Issue by msankaran0712** [trimble-oss/modus-web-components#1729]
### Prerequisites

- [X] I have [searched](https://github.com/trimble-oss/modus-web-components/issues?q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [Modus style guidelines](https://modus.trimble.com/components/web/introduction/)

### Proposal

We need row actions for Modus Table component as shown below, and the Figma prototype can be found in this [link](https://www.figma.com/file/7yC5vYgdbzqaEJDr566xAL/SUBMISSION-V1---Work-in-Progress?node-id=0%3A1&mode=dev)

![image](https://github.com/trimble-oss/modus-web-components/assets/50131391/046ef19c-bcef-449e-bb65-1c07510be986)

### What is the issue regarding ?

@trimble-oss/modus-web-components

### Priority

High

### What product/project are you using Modus Components for ?

modus

### What is your team/division name ?

modus

### Are you willing to contribute ?

None

**Comment by msankaran0712** [comment]
Maha to check with Matt and Modus team to revise the guidelines for row actions in Modus Styleguide

**Comment by msankaran0712** [comment]
From a discussion with Matt Brinkman of the Tables Tiger team, it was decided that the new Table component should display an overflow icon in the first cell of each row for row actions, prototype can be found in this [Figma link](https://www.figma.com/file/7yC5vYgdbzqaEJDr566xAL/SUBMISSION-V1---Work-in-Progress?node-id=0%3A1&mode=dev)
![image](https://github.com/trimble-oss/modus-web-components/assets/50131391/1dc84d12-01a4-468d-b38f-ef866a50cb68)

cc @enowak1031 @egunther39

**Comment by msankaran0712** [comment]
Leonardo Rodrigues is working on this issue

**Comment by enowak1031** [comment]
@msankaran0712 Moving to Sprint 73. Let's get an update.
