### ISSUE TITLE
Modus File Upload Dropzone - Add support for customizing the messages

### ISSUE THREAD

**Issue by laurenceSkoropinskiTrimble** [trimble-oss/modus-web-components#1741]
### Prerequisites

- [X] I have [searched](https://github.com/trimble-oss/modus-web-components/issues?q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [Modus style guidelines](https://modus.trimble.com/components/web/introduction/)

### Proposal

Modus FileDropZone: This component has hard coded English text, so cannot be used if internationalization is required. Any plans to add props for the messages within the drop zone. Not sure how you handle the link text.

### Motivation and context

Viewpoint for Projects is about to start a UI upgrade to modus, and this a multi language app.

### What is the issue regarding ?

@trimble-oss/modus-web-components

### Priority

Medium

### What product/project are you using Modus Components for ?

Viewpoint for Projects

### What is your team/division name ?

Newcastle, White Team

### Are you willing to contribute ?

Yes

### Are you using Modus Web Components in production ?

Yes

**Comment by msankaran0712** [comment]
Maha to check with Christian and get back if any questions

**Comment by rthanga1** [comment]
@laurenceSkoropinskiTrimble will you be able to contribute to this?
