### ISSUE TITLE
Date Picker state setDate method is not ISO 8601 compliant

### ISSUE THREAD

**Issue by DonavanPrinsTrimble** [trimble-oss/modus-web-components#1753]
### Prerequisites

- [X] I have [searched](https://github.com/trimble-oss/modus-web-components/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/trimble-oss/modus-web-components/blob/main/CONTRIBUTING.md)

### Describe the issue

Month and date values less than 10 are not left padded with zero, resulting in a non compliant ISO 8601 date format. 

This causes unexpected behavior when constructing a date from the element value, for example '2023-1-1'.

### What is the issue regarding ?

@trimble-oss/modus-web-components

### Priority

High

### What product/project are you using Modus Components for ?

Seurat

### What is your team/division name ?

Geospatial

### Are you willing to contribute ?

Yes

**Comment by DonavanPrinsTrimble** [comment]
My proposed fix is to add padStart to the month and date variables before setting the element value, see below.

I will create a PR if I have access to contribute.

```
export default class ModusDatePickerState {
  ...

  setDate(val: Date): void {
    // Converting to ISO8601 'yyyy-mm-dd' format
    if (Number(val)) {
      const year = val.getFullYear();
      const month = (val.getMonth() + 1).toString().padStart(2, '0'); // Zero based number system for months
      const date = val.getDate().toString().padStart(2, '0');

      this.element.value = `${year}-${month}-${date}`;
      this.element.focusInput();
      this.date = val;
    }
  }
}
```

**Comment by msankaran0712** [comment]
Hey @DonavanPrinsTrimble, thank you for reporting the issue and expressing interest in submitting a PR. Your efforts are highly appreciated. Please let us know if you have any challenges creating a PR.

**Comment by msankaran0712** [comment]
@DonavanPrinsTrimble  FYI

**Comment by msankaran0712** [comment]
Please look out for the next release, we are planning to do it on Friday
