### ISSUE TITLE
MWC- Prepare a writeup for PR review process and Release

### ISSUE THREAD

**Issue by msankaran0712** [trimble-oss/modus-web-components#1757]
### Prerequisites

- [X] I have [searched](https://github.com/trimble-oss/modus-web-components/issues?q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [Modus style guidelines](https://modus.trimble.com/components/web/introduction/)

### Proposal

If possible add a flowchart

### What is the issue regarding ?

Modus Web Components Website (Storybook)

### Priority

High

### What product/project are you using Modus Components for ?

modus

### What is your team/division name ?

modus

### Are you willing to contribute ?

None

**Comment by prashanth-offcl** [comment]
Chris already updated the wiki for release and PR template also exists now so closing this.
