### ISSUE TITLE
ModusToast : Auto dismiss

### ISSUE THREAD

**Issue by Jayanthbalakrishnan** [trimble-oss/modus-web-components#1762]
### Prerequisites

- [X] I have [searched](https://github.com/trimble-oss/modus-web-components/issues?q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [Modus style guidelines](https://modus.trimble.com/components/web/introduction/)

### Proposal

Toast should be dismissed after some configurable time. 

### Motivation and context

**Case :** 
If user is doing multiple actions on single page, we will notify toast for every actions. we don't want our user to close this toast everytime.

**Our case :** 
please go through the image,
In our case, we will list number of users in this page, he might click resend button for some users, for every clicks, we will send out an invitation in the background and notify by toast. 
**for an eg :** 
if he is clicking resend button for 4 users, we need to send 4 invitations and 4 toast messages. we don't want user to close 4 toast messages.

![image](https://github.com/trimble-oss/modus-web-components/assets/129956254/c6736174-4aec-4d5f-82dc-4aee30287fcf)

 

### What is the issue regarding ?

@trimble-oss/modus-web-components

### Priority

High

### What product/project are you using Modus Components for ?

ConnectX

### What is your team/division name ?

Industry Clouds

### Are you willing to contribute ?

Maybe

### Are you using Modus Web Components in production ?

yes, https://console.construction.cloud/#/workflow

**Comment by cjwinsor** [comment]
Update toast to auto dismiss at 15 seconds, allow user to override with a `delay` prop.

**Comment by cjwinsor** [comment]
@ElishaSamPeterPrabhu Updated Requirements:

* When `delay` is set to a number > 0
  * the toast will remove itself using `this.element.remove()`
  * the toast will emit its `dismissClick` event
* If `delay` is not > 0, the toast is not automatically dismissed
* On `click` of dismiss button
  * the toast will remove itself using `this.element.remove()`
  * the toast will emit its `dismissClick` event

This could be considered a breaking change so I will announce it leading up to its eventual release.
