### ISSUE TITLE
Navbar profile menu link item icons

### ISSUE THREAD

**Issue by acomsto** [trimble-oss/modus-web-components#1770]
### Prerequisites

- [X] I have [searched](https://github.com/trimble-oss/modus-web-components/issues?q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [Modus style guidelines](https://modus.trimble.com/components/web/introduction/)

### Proposal

We would like the navbar profile menu items to have the ability to add an optional icon to the left of each profile menu link item. This would mean adding icon fields to the `ModusProfileMenuOptions` interface.

Use case: Our UX requested that these options were added

here's a picture of the requested change:
![image](https://github.com/trimble-oss/modus-web-components/assets/107583407/495d7980-f58b-4ac8-9bba-694e95a26f78)

### Motivation and context

We want the ability to add icons next to each item in the profile menu if needed.

### What is the issue regarding ?

@trimble-oss/modus-web-components

### Priority

Medium

### What product/project are you using Modus Components for ?

Work Center

### What is your team/division name ?

Trimble Viewpoint

### Are you willing to contribute ?

Yes

**Comment by msankaran0712** [comment]
if possible kindly please provide some screenshots too @acomsto

**Comment by acomsto** [comment]
> @acomsto what is the use case and what icons needed?

Both of these have been added to the original post

**Comment by enowak1031** [comment]
@acomsto We were looking for icons NEXT to the profile menu :/ But you are referring to the icons in the menu itself next to My Profile and Support. These are approved. But the correct color is Trimble Gray.

**Comment by ryan-henness-trimble** [comment]
Ewa and I had a discussion about this issue, it looks like there was a misunderstanding about where these icons would be. In the provided image, the new icons are those next to the "My Profile" and "Support" links

This one has been Modus approved with one adjustment to the provided mock - the icon colors should use Trimble Gray

**Comment by msankaran0712** [comment]
@ryan-henness-trimble @acomsto my bad, I did not check the code. I did not know that the Navbar component had support for links inside the profile menu pop-up other than the sign-out link.

**Comment by msankaran0712** [comment]
@acomsto @ryan-henness-trimble Kindly pause the work on the PR, @egunther39 will be providing your the mockup for the profile menu pop-up

**Comment by msankaran0712** [comment]
@acomsto We have an update on the mockup. 

- Avatar and the email address should always be centred
- The list should be a borderless Modus List items
- Padding from the top, padding between the email address and list items, and the padding between list and the footer section, all should be 16px

![image](https://github.com/trimble-oss/modus-web-components/assets/50131391/6ad0c8b2-ce01-4b57-ae69-b9834f67b7ae)

**Comment by enowak1031** [comment]
@acomsto or @msankaran0712 What's the status on this? Let's add to sprint.

**Comment by acomsto** [comment]
@enowak1031 Looks like I'm waiting for dark mode mocks

**Comment by egunther39** [comment]
@enowak1031 @acomsto - I already provided it to @msankaran0712 .  Here it is
![image](https://github.com/trimble-oss/modus-web-components/assets/98049598/8cbaa1ce-c953-46ce-b7f6-b55d63e4790e)

**Comment by msankaran0712** [comment]
@enowak1031 there are some PR comments yet to be resolved, https://github.com/trimble-oss/modus-web-components/pull/1776

**Comment by msankaran0712** [comment]
@acomsto Please wait till Friday this week for the next release, if urgent kindly let us know.
