### ISSUE TITLE
Chip does not handle line overflow

### ISSUE THREAD

**Issue by DonavanPrinsTrimble** [trimble-oss/modus-web-components#1771]
### Prerequisites

- [X] I have [searched](https://github.com/trimble-oss/modus-web-components/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/trimble-oss/modus-web-components/blob/main/CONTRIBUTING.md)

### Describe the issue

When the chip text wraps to a new line it breaks out of the chip container and scales the close button smaller

To Reproduce:
[https://modus-web-components.trimble.com/?path=/story/components-chip--default](https://modus-web-components.trimble.com/?path=/story/components-chip--default&args=imageUrl:;showClose:true;size:small;value:Extra+long+text+to+test+chip+line+breaks+and+overflow+value+handling+Extra+long+text+to+test+chip+line+breaks+and+overflow+value+handling+Extra+long+text+to+test+chip+line+breaks+and+overflow+value+handling+Extra+long+text+to+test+chip+line+breaks+and+overflow+value+handling+Extra+long+text+to+test+chip+line+breaks+and+overflow+value+handling+Extra+long+text+to+test+chip+line+breaks+and+overflow+value+handling&globals=backgrounds.grid:false)

![image](https://github.com/trimble-oss/modus-web-components/assets/127373877/729f1c64-5295-4441-82c9-6921dafd94e1)

### Reduced test cases

Expected Behavior:
Close button size to remain constant.
The chip container should grow to the filled text or an option to clip the overflow text with an ellipsis.

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome

### What is the issue regarding ?

@trimble-oss/modus-web-components

### What version of npm package are you using ?

0.1.55

### Priority

Medium

### What product/project are you using Modus Components for ?

Seurat

### What is your team/division name ?

Geospatial

### Are you willing to contribute ?

Yes

**Comment by msankaran0712** [comment]
hey @DonavanPrinsTrimble I don't think Chips are intended to have longer text and the Chip component seems to resize based on the screen size which I think is enough.

Correct me if am wrong @egunther39 @soniakaukonen @coliff @enowak1031

**Comment by DonavanPrinsTrimble** [comment]
I agree my example is excessive for what a chip is meant for, however please see below our actual usage where we are displaying tags in a table column.

![image](https://github.com/trimble-oss/modus-web-components/assets/127373877/3f50028c-faff-4604-af5a-8925b034964e)

**Comment by msankaran0712** [comment]
@DonavanPrinsTrimble Thank you for the screenshot, we will get back to you 👍🏼

**Comment by msankaran0712** [comment]
We can show ellipsis.

**Comment by coliff** [comment]
We could fix this with a few CSS rules - screenshot here:
![image](https://github.com/trimble-oss/modus-web-components/assets/1212885/f3065f19-fbfa-403e-914e-8c1a87266f58)

Stackblitz demo:
https://stackblitz.com/edit/modus-chip-max-length?file=index.html

**Comment by msankaran0712** [comment]
Hey @DonavanPrinsTrimble, 
We've addressed the text-overflow issue by adding a `max-width` property with an ellipsis. The fix is scheduled to be released at the end of this week. 
Since the PR has been merged, I'm closing this issue. However, if the issue persists or you have any further requests, please feel free to reopen the issue or submit a new request.
