### ISSUE TITLE
Modus Table - Add support for Autocomplete and Date picker cell editors 

### ISSUE THREAD

**Issue by msankaran0712** [trimble-oss/modus-web-components#1773]
### Prerequisites

- [X] I have [searched](https://github.com/trimble-oss/modus-web-components/issues?q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [Modus style guidelines](https://modus.trimble.com/components/web/introduction/)

### Proposal

Users should be able to edit the cell content using Autocomplete and date picker controls.

### What is the issue regarding ?

@trimble-oss/modus-web-components

### Priority

Medium

### What product/project are you using Modus Components for ?

modus

### What is your team/division name ?

modus

### Are you willing to contribute ?

None

**Comment by prashanth-offcl** [comment]
Looks like this is already done
