### ISSUE TITLE
Make User Profile optional in Navbar

### ISSUE THREAD

**Issue by msankaran0712** [trimble-oss/modus-web-components#1782]
### Prerequisites

- [X] I have [searched](https://github.com/trimble-oss/modus-web-components/issues?q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [Modus style guidelines](https://modus.trimble.com/components/web/introduction/)

### Proposal

For more details, https://github.com/trimble-oss/website-modus.trimble.com/issues/714

### What is the issue regarding ?

@trimble-oss/modus-web-components

### Priority

Medium

### What product/project are you using Modus Components for ?

modus

### What is your team/division name ?

modus

### Are you willing to contribute ?

None

**Comment by cjwinsor** [comment]
Handled by #2128
