### ISSUE TITLE
Expose some properties to override the pagination behavior internally.

### ISSUE THREAD

**Issue by rjavier-trimbler** [trimble-oss/modus-web-components#1783]
### Prerequisites

- [X] I have [searched](https://github.com/trimble-oss/modus-web-components/issues?q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [Modus style guidelines](https://modus.trimble.com/components/web/introduction/)

### Proposal

Expose some properties to override the pagination behavior internally.

In order to be able to control the pagination from the server side we must make the table not to perform any action when clicking on any page number and have no effect on the table 
so this can be handled via the "Pagination" event.

### What is the issue regarding ?

@trimble-oss/modus-web-components, Modus Web Components Website (Storybook)

### Priority

High

### What product/project are you using Modus Components for ?

Navigators

### What is your team/division name ?

Navigators

### Are you willing to contribute ?

Yes

**Comment by msankaran0712** [comment]
@rjavier-trimbler There is an existing issue with server-side pagination on the table,  https://github.com/trimble-oss/modus-web-components/issues/1153. Modus Table internally uses the tanstack open-source library for state management, hence we should be trying out https://tanstack.com/table/v8/docs/api/features/pagination#manualpagination first before making any other changes.

**Comment by msankaran0712** [comment]
@rjavier-trimbler Kindly please close the issue if it is related to the manual pagination which was closed recently.
