### ISSUE TITLE
Add Shield Icon

### ISSUE THREAD

**Issue by oliviadendinger** [trimble-oss/modus-web-components#1788]
### Prerequisites

- [X] I have [searched](https://github.com/trimble-oss/modus-web-components/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/trimble-oss/modus-web-components/blob/main/CONTRIBUTING.md)

### Describe the issue

need to add shield icon so that it can be used in modus-icon component 

### What is the issue regarding ?

@trimble-oss/modus-web-components

### Priority

Low

### What product/project are you using Modus Components for ?

hrm

### What is your team/division name ?

hff/hris

### Are you willing to contribute ?

Yes

**Comment by msankaran0712** [comment]
@oliviadendinger For feature additions, you need to choose the feature request template for creating the GitHub issue.
![image](https://github.com/trimble-oss/modus-web-components/assets/50131391/dd174e23-6d84-480a-aea4-cca94d736ada)

**Comment by msankaran0712** [comment]
@enowak1031 I have marked the issue "modus-approved" because it is just an icon addition.

**Comment by msankaran0712** [comment]
@oliviadendinger  The PR is merged and please expect your changes in the next version which is planned on every Friday.
