### ISSUE TITLE
Add Generated Files to `.gitignore`

### ISSUE THREAD

**Issue by ryan-henness-trimble** [trimble-oss/modus-web-components#1819]
### Prerequisites

- [X] I have [searched](https://github.com/trimble-oss/modus-web-components/issues?q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [Modus style guidelines](https://modus.trimble.com/components/web/introduction/)

### Proposal

To maintain clarity and simplicity in our PRs, I recommend adding applicable generated files to the `.gitignore` file. This will result in a more streamlined code review process

### What is the issue regarding ?

@trimble-oss/modus-web-components

### Priority

Low

### What product/project are you using Modus Components for ?

Work Center

### What is your team/division name ?

Trimble Viewpoint

### Are you willing to contribute ?

Maybe

### Are you using Modus Web Components in production ?

Yes

**Comment by coliff** [comment]
I agree! Could you make a PR for this Ryan?

**Comment by ryan-henness-trimble** [comment]
Yep, I can give this a shot If I can find some time here soon
