### ISSUE TITLE
Uncaught TypeError: Cannot read properties of null when date picker has no value set

### ISSUE THREAD

**Issue by DonavanPrinsTrimble** [trimble-oss/modus-web-components#1834]
### Prerequisites

- [X] I have [searched](https://github.com/trimble-oss/modus-web-components/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/trimble-oss/modus-web-components/blob/main/CONTRIBUTING.md)

### Describe the issue

Error is raised when you use the date picker and have no value set.

### Reduced test cases

Navigate to https://modus-web-components.trimble.com/?path=/story/user-inputs-date-picker--default-with-picker&args=value:

Observe the console error: 
```javascript
Uncaught TypeError: Cannot read properties of null (reading 'trim')
    at ModusDateInput.updateDateFromAltFormats (39.a42672c3.iframe.bundle.js:2:22447)
    at ModusDateInput.handleBlur (39.a42672c3.iframe.bundle.js:2:21408)
    at HTMLInputElement.onBlur (39.a42672c3.iframe.bundle.js:2:24956)
```

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome

### What is the issue regarding ?

@trimble-oss/modus-web-components, Modus Web Components Website (Storybook)

### What version of npm package are you using ?

Storybook 6.5.16

### Priority

Medium

### What product/project are you using Modus Components for ?

Seurat

### What is your team/division name ?

Geospatial

### Are you willing to contribute ?

None

**Comment by msankaran0712** [comment]
@DonavanPrinsTrimble Thanks for your PR and it is merged. Kindly wait till the end of this week for the next release, if it is urgent let us know.
