### ISSUE TITLE
Modus Dropdown - Add support for 2-line

### ISSUE THREAD

**Issue by msankaran0712** [trimble-oss/modus-web-components#1838]
### Prerequisites

- [X] I have [searched](https://github.com/trimble-oss/modus-web-components/issues?q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [Modus style guidelines](https://modus.trimble.com/components/web/introduction/)

### Proposal

https://github.com/trimble-oss/modus/issues/531
https://github.com/trimble-oss/website-modus.trimble.com/issues/741

Mockup:
https://www.figma.com/file/Bfpyk5rbSsmwfIacqzg9HS/Modus---Mobile?node-id=1229%3A14167&mode=dev#599979095

### What is the issue regarding ?

@trimble-oss/modus-web-components

### Priority

Medium

### What product/project are you using Modus Components for ?

Submitted by E-Builder team

### What is your team/division name ?

Submitted by E-Builder team

### Are you willing to contribute ?

None

**Comment by apaddock** [comment]
I'd like to ask that this be an enhancement to the modus list control since that is what is used for the dropdown content

**Comment by cjwinsor** [comment]
This was resolved with #1957
