### ISSUE TITLE
Modus List - Add the height corrections

### ISSUE THREAD

**Issue by msankaran0712** [trimble-oss/modus-web-components#1842]
### Prerequisites

- [X] I have [searched](https://github.com/trimble-oss/modus-web-components/issues?q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [Modus style guidelines](https://modus.trimble.com/components/web/introduction/)

### Proposal

As confirmed by @egunther39  and the MoAB,

- We need a variant for Large list item height 48px icon size 24x24
- Make sure the default height is 40px icon size 24x24 
- Make sure the condensed list item height is 32px and the icon size is 16x16

### What is the issue regarding ?

@trimble-oss/modus-web-components

### Priority

Medium

### What product/project are you using Modus Components for ?

modus

### What is your team/division name ?

modus

### Are you willing to contribute ?

None

**Comment by cjwinsor** [comment]
Closed, our `modus-list` supports the 3 size levels
