### ISSUE TITLE
Modus side navigation item the tooltip is aligned to the center of the side nav item icon

### ISSUE THREAD

**Issue by VinoSakthiv** [trimble-oss/modus-web-components#1850]
### Prerequisites

- [X] I have [searched](https://github.com/trimble-oss/modus-web-components/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/trimble-oss/modus-web-components/blob/main/CONTRIBUTING.md)

### Describe the issue

Modus side navigation item the tooltip is aligned to the center of the side nav item icon.
Expected : it should be aligned to whole item. so when focusing over the item tooltip should be displayed

### What is the issue regarding ?

@trimble-oss/modus-web-components

### What version of npm package are you using ?

0.4.1-react17

### Priority

Medium

### What product/project are you using Modus Components for ?

Trimble Construction Cloud

### What is your team/division name ?

Industry Clouds

### Are you willing to contribute ?

Yes

### Are you using Modus Web Components in production ?

Yes

**Comment by rthanga1** [comment]
@VinoSakthiv This is fixed now. Can you verify in the latest package?
