### ISSUE TITLE
Delay in Hamburger icon button click and animation causing inconsistent side menu expansion

### ISSUE THREAD

**Issue by VinoSakthiv** [trimble-oss/modus-web-components#1851]
### Prerequisites

- [X] I have [searched](https://github.com/trimble-oss/modus-web-components/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/trimble-oss/modus-web-components/blob/main/CONTRIBUTING.md)

### Describe the issue

Continuously clicking on hamburger icon is causing the menu option are not getting display properly or menu options are displaying only with icons with expanded view
<img width="959" alt="image" src="https://github.com/trimble-oss/modus-web-components/assets/133335850/33879638-66ef-4112-b81e-68b40a70955d">

### What is the issue regarding ?

@trimble-oss/modus-web-components

### What version of npm package are you using ?

0.4.1-react17

### Priority

Medium

### What product/project are you using Modus Components for ?

Trimble Construction Cloud

### What is your team/division name ?

Industry Clouds

### Are you willing to contribute ?

Maybe

### Are you using Modus Web Components in production ?

Yes

**Comment by ElishaSamPeterPrabhu** [comment]
I am not able to reproduce the issue in the current main branch
@VinoSakthiv Can you verify it?

https://github.com/trimble-oss/modus-web-components/assets/122255626/0ea46447-189b-461f-a17c-516bf7a15dce

**Comment by cjwinsor** [comment]
Unable to reproduce, and had no additional feedback from @VinoSakthiv .
