### ISSUE TITLE
Add all modus icons

### ISSUE THREAD

**Issue by AlexRaynerTrimble** [trimble-oss/modus-web-components#1860]
### Prerequisites

- [X] I have [searched](https://github.com/trimble-oss/modus-web-components/issues?q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [Modus style guidelines](https://modus.trimble.com/components/web/introduction/)

### Proposal

The modus icon set includes hundreds of icons out of the box, however it looks like the vast majority of them are not available in modus web components. Whilst I understand that people have requested icons on a case-by-case basis, it doesn't make sense to me that these are added ad-hoc. In my opinion, if Modus WCs support modus icons, then all icons should be available for use. 

I can see in the source code that you are using the svg's directly and have individual components for each, which probably explains why all the icons have not yet been implemented, however an alternative approach might be to use the modus icons font as this would support all icons out of the box and any future changes to modus icons would be very easy to update to.

### Motivation and context

A lot of the icons we use in our products are not currently in Modus WCs. We are currently starting work to transition from our own Modus-based UI library to using Modus WCs

### What is the issue regarding ?

@trimble-oss/modus-web-components

### Priority

Low

### What product/project are you using Modus Components for ?

Predesign, AddLocation, Spaces

### What is your team/division name ?

Habitat/SketchUp

### Are you willing to contribute ?

Yes

**Comment by msankaran0712** [comment]
@AlexRaynerTrimble Thank you for highlighting the issue. We have an issue for adding support for all the icons in Modus Icons library, #1098

**Comment by msankaran0712** [comment]
@AlexRaynerTrimble I have closed the #1098 to avoid confusions. It is not advisable to use the Modus icons font instead of SVGs due to certain issues. @coliff Can you please confirm?

**Comment by cjwinsor** [comment]
All icons should now be available to be used.
