### ISSUE TITLE
Add small size for Radios and add the hover effect

### ISSUE THREAD

**Issue by rthanga1** [trimble-oss/modus-web-components#1877]
See Figma update 1.2.19 dated 9/25/2023. New selected focus and hover states, label size adjustments etc.

https://www.figma.com/file/wyfVJUHWRMkeCfdB38HFEE/Modus---Web?type=design&node-id=1346-8&mode=design&t=nzN2vrAJlzLd2XLh-0

**Comment by msankaran0712** [comment]
@coliff We need to add Ramaraj and Sam in all the GitHub workflows, so that external request tag will not be assigned to the issues that Ram and Sam are creating.

**Comment by msankaran0712** [comment]
@rthanga1 We need to add a description for the issues. Adding a comment also will link it to the original issue: https://github.com/trimble-oss/modus-web-components/issues/1734

**Comment by rthanga1** [comment]
@ElishaSamPeterPrabhu Is this done?
