### ISSUE TITLE
AutoComplete - add control to allow open on focus

### ISSUE THREAD

**Issue by apaddock** [trimble-oss/modus-web-components#1887]
### Prerequisites

- [X] I have [searched](https://github.com/trimble-oss/modus-web-components/issues?q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [Modus style guidelines](https://modus.trimble.com/components/web/introduction/)

### Proposal

Submission approved and final version of Figma available https://app.clickup.com/t/8684uve2r

### Motivation and context

https://docs.google.com/document/d/1juSdxo5G6jmB_8MrrpZL3WdtVzOvzEL1S3MbuxNkc8M/edit

### What is the issue regarding ?

@trimble-oss/modus-web-components

### Priority

Medium

### What product/project are you using Modus Components for ?

e-Builder

### What is your team/division name ?

e-Builder

### Are you willing to contribute ?

Yes

### Are you using Modus Web Components in production ?

yes

**Comment by msankaran0712** [comment]
Related to https://github.com/trimble-oss/modus/issues/488

**Comment by apaddock** [comment]
https://mui.com/material-ui/react-autocomplete/#asynchronous-requests 

Plan is to implement the behavior for "Load on open"

**Comment by msankaran0712** [comment]
@msankaran0712 To create an issue for updating the Modus styleguide

**Comment by msankaran0712** [comment]
@acomsto The request has been approved by Modus, and everything is now set for development.
