### ISSUE TITLE
Default icon color inconsistencies

### ISSUE THREAD

**Issue by rhenness** [trimble-oss/modus-web-components#1889]
### Prerequisites

- [X] I have [searched](https://github.com/trimble-oss/modus-web-components/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/trimble-oss/modus-web-components/blob/main/CONTRIBUTING.md)

### Describe the issue

There are some inconsistencies in the default icon colors that have made it harder to keep behavior consistent across all icons.
The inconsistencies are:
1. Which elements the fill color property values are set on. Some set the fill on the `svg`, and others on the `path` elements.
2. Which colors are used as the default values for those properties. Some use `'currentColor'`, others use `#6A6976` or `#252a2e`

To resolve these issue and improve icon consistency, I suggest a few changes:
1. Use the `fill` property on the `svg` elements inside of the icon components, rather than the `path` elements
2. Default the `fill` property value to `'currentColor'` - which means that the fill color of that path will be the same as the color property of the element or its parent element (see example: https://jsfiddle.net/s4c1e2nu/1/)
3. Use a constant value for the icon default size of `16`

### What is the issue regarding ?

@trimble-oss/modus-web-components

### What version of npm package are you using ?

Latest

### Priority

Medium

### What product/project are you using Modus Components for ?

Work Center

### What is your team/division name ?

Trimble Viewpoint

### Are you willing to contribute ?

Yes

**Comment by ryan-henness-trimble** [comment]
@msankaran0712 Any thoughts on this one?

**Comment by ryan-henness-trimble** [comment]
@coliff @msankaran0712 one quick question about the review process - will one of you reach out once this issue has been reviewed by your team?

**Comment by coliff** [comment]
some rules/changes I have in mind:

- Remove `data-test-id` attribute on any SVGs
- SVG should have have `fill={props.color ?? 'currentColor'}`
- Remove any unnecessary groups `<g>`
- Maybe alphabetize the SVG attributes for consistency
- Set icon name as the class if no class name there already
- Remove any 'empty squares' (`<path d="M0,0H24V24H0Z" fill="none" />`)

**Comment by rthanga1** [comment]
@coliff/ @ryan-henness-trimble  Can you confirm if this is fixed by Ryan's latest PR?

**Comment by prashanth-offcl** [comment]
Closing this based on the status.
