### ISSUE TITLE
Add pin icon

### ISSUE THREAD

**Issue by gicaguguitrimble** [trimble-oss/modus-web-components#1897]
### Prerequisites

- [X] I have [searched](https://github.com/trimble-oss/modus-web-components/issues?q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [Modus style guidelines](https://modus.trimble.com/components/web/introduction/)

### Proposal

The Pin icon should be added, so it can be used in the library.

### Motivation and context

Needed to be used in different other components from the library.

### What is the issue regarding ?

@trimble-oss/modus-web-components

### Priority

Low

### What product/project are you using Modus Components for ?

ADMS

### What is your team/division name ?

ADMS Utilities

### Are you willing to contribute ?

Yes

**Comment by msankaran0712** [comment]
@gicaguguitrimble  Thank you for the PR, it is approved and merged now. Please expect the changes to be published in the next version by next week.
