### ISSUE TITLE
Modus Angular - Build error on `TableContext`

### ISSUE THREAD

**Issue by msankaran0712** [trimble-oss/modus-web-components#1898]
### Prerequisites

- [X] I have [searched](https://github.com/trimble-oss/modus-web-components/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/trimble-oss/modus-web-components/blob/main/CONTRIBUTING.md)

### Describe the issue

Reported by Roopesh Reddy, 
![image](https://github.com/trimble-oss/modus-web-components/assets/50131391/3199d157-6f67-4881-8ae9-1b9b2608607d)

### What is the issue regarding ?

@trimble-oss/modus-web-components

### What version of npm package are you using ?

v0.6.0

### Priority

High

### What product/project are you using Modus Components for ?

modus

### What is your team/division name ?

modus

### Are you willing to contribute ?

None

**Comment by AdelaDuna** [comment]
The same error appears for ToolTipPlacement in the same package version.

![image](https://github.com/trimble-oss/modus-web-components/assets/98012598/b67bfe47-b587-4e58-8531-188878adc460)
