### ISSUE TITLE
Ability to render Table with pre selected rows

### ISSUE THREAD

**Issue by leosole-trimble** [trimble-oss/modus-web-components#1900]
### Prerequisites

- [X] I have [searched](https://github.com/trimble-oss/modus-web-components/issues?q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [Modus style guidelines](https://modus.trimble.com/components/web/introduction/)

### Proposal

The old Data Table had the option to load the table with some rows already selected. The Table component should have the same behaviour

### Motivation and context

This is important for use cases that enable editing a selection of elements from a list. If the table can't load with the previous selected elements, the user needs to select everything again when editing a selection

### What is the issue regarding ?

@trimble-oss/modus-web-components

### Priority

High

### What product/project are you using Modus Components for ?

Trimble Inspections

### What is your team/division name ?

Camaleão/Transportation

### Are you willing to contribute ?

Yes

### Are you using Modus Web Components in production ?

no

**Comment by rthanga1** [comment]
Hello @leosole-trimble / @msankaran0712  Is this done already?

**Comment by leosole-trimble** [comment]
@rthanga1 yes
