### ISSUE TITLE
Table: Manual pagination issue when the initial state is undefined

### ISSUE THREAD

**Issue by yohernandez** [trimble-oss/modus-web-components#1908]
### Prerequisites

- [X] I have [searched](https://github.com/trimble-oss/modus-web-components/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/trimble-oss/modus-web-components/blob/main/CONTRIBUTING.md)

### Describe the issue

Setting _manualPaginationOptions_ throws an error when the previous state is undefined.

`@Prop() manualPaginationOptions: ModusTableManualPaginationOptions;
  @Watch('manualPaginationOptions') onManualPaginationOptionsChange(
    newVal: ModusTableManualPaginationOptions,
    oldVal: ModusTableManualPaginationOptions
  ) {
    if (
      newVal.pageCount !== oldVal.pageCount ||
      newVal.currentPageIndex !== oldVal.currentPageIndex ||
      newVal.currentPageSize !== oldVal.currentPageSize
    ) {
      this.tableCore.setOptions('pageCount', newVal.pageCount);
      this.manualPaginationOptions = { ...newVal };
    }
  }`

Also, there is an issue with manual pagination. It's not showing the right data range for the current page index.

![image](https://github.com/trimble-oss/modus-web-components/assets/48927186/0e1a3b38-3854-44f2-9e41-4562f6bb0d3d)

### What is the issue regarding ?

@trimble-oss/modus-web-components

### Priority

Medium

### What product/project are you using Modus Components for ?

e-builder

### What is your team/division name ?

e-builder

### Are you willing to contribute ?

Yes

**Comment by rthanga1** [comment]
@yohernandez Can we close this one? Looks like the PR got merged?

**Comment by yohernandez** [comment]
> @yohernandez Can we close this one? Looks like the PR got merged?

Yes, we can.
