### ISSUE TITLE
Modus Side Navigation Blue Theme Example is not working

### ISSUE THREAD

**Issue by coliff** [trimble-oss/modus-web-components#1911]
### Prerequisites

- [X] I have [searched](https://github.com/trimble-oss/modus-web-components/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/trimble-oss/modus-web-components/blob/main/CONTRIBUTING.md)

### Describe the issue

On this page the 'Enable Push Side Navigation' doesn't appear to work and the text in the main panel is getting cut off.

![image](https://github.com/trimble-oss/modus-web-components/assets/1212885/e4f40fd5-826c-47fd-bbd0-d97b2fbb090e)

### Reduced test cases

Example here:
https://modus-web-components.trimble.com/?path=/docs/components-side-navigation--side-navigation-with-data#modus-side-navigation-blue-theme

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Microsoft Edge

### What is the issue regarding ?

Modus Web Components Website (Storybook)

### Priority

Medium

### What product/project are you using Modus Components for ?

Modus

### What is your team/division name ?

Modus

### Are you willing to contribute ?

Maybe

**Comment by ElishaSamPeterPrabhu** [comment]
This issue doesnt occur locally 
![image](https://github.com/trimble-oss/modus-web-components/assets/122255626/27519973-2e79-496f-814d-ec2c910adce8)
and am not able to push date in storybook docs irrespective of whether it blue themed or not but in canvas am able to do it ,
Maybe its a storybook docs error

**Comment by ElishaSamPeterPrabhu** [comment]
https://github.com/trimble-oss/modus-web-components/assets/122255626/5af73a4f-f390-4265-8df6-df04a1896bd9

The issue doesn't occur in storybook as well.
@coliff  Can we close this?

**Comment by coliff** [comment]
yep - fixed now - thanks!
