### ISSUE TITLE
Minimize/ Maximize Modal

### ISSUE THREAD

**Issue by enowak1031** [trimble-oss/modus-web-components#1925]
https://docs.google.com/document/d/1oP7aMWRoAqKq60Ws24BtIUnwtkk1edHilal44Cq5fVk/edit

https://www.figma.com/file/vgqWcofGbZNh6wBrsXnzq6/Modus-Submissions?type=design&node-id=1-4&mode=design&t=xziDxcTq1mOpjKsz-0

**Comment by rthanga1** [comment]
This is a separate component
 - Write guidelines
 - Rename the control as it confuses the Modal Dialoge that we have (Non-Modal?)
 -

**Comment by prashanth-offcl** [comment]
Closing this issue as it is fixed in #2766 & #2686
