### ISSUE TITLE
Cards by default have no border-radius

### ISSUE THREAD

**Issue by coliff** [trimble-oss/modus-web-components#1928]
### Prerequisites

- [X] I have [searched](https://github.com/trimble-oss/modus-web-components/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/trimble-oss/modus-web-components/blob/main/CONTRIBUTING.md)

### Describe the issue

I think that by default cards have no border radius. I think the default should be 2px and set automatically unless a different value is specified.

### Reduced test cases

https://modus-web-components.trimble.com/?path=/story/components-card--default

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Microsoft Edge

### What is the issue regarding ?

@trimble-oss/modus-web-components

### Priority

Low

### What product/project are you using Modus Components for ?

Modus

### What is your team/division name ?

Modus

### Are you willing to contribute ?

Yes

### Are you using Modus Web Components in production ?

https://modus-web-components.trimble.com/

**Comment by rthanga1** [comment]
There seems to be a corner radius but @coliff to check this again and update here if the value is right
