### ISSUE TITLE
Implement "Density" control on modus table

### ISSUE THREAD

**Issue by apaddock** [trimble-oss/modus-web-components#1930]
### Prerequisites

- [X] I have [searched](https://github.com/trimble-oss/modus-web-components/issues?q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [Modus style guidelines](https://modus.trimble.com/components/web/introduction/)

### Proposal

Relaxed = Default size: 48px/3rem in height
![Relaxed](https://github.com/trimble-oss/modus-web-components/assets/4574058/45eff661-5be4-401b-821c-14868241fc8f)

Comfortable = Condensed (Medium) size: 32px/2rem in height
![Comfortable](https://github.com/trimble-oss/modus-web-components/assets/4574058/5d7a1bc7-a1c7-445c-a469-fb28f87c70fd)

Compact = Small size: 24px/1.5 rem in height
![Compact](https://github.com/trimble-oss/modus-web-components/assets/4574058/946d432e-e2d8-4747-8b01-da307acd7f2f)

### What is the issue regarding ?

@trimble-oss/modus-web-components

### Priority

Medium

### What product/project are you using Modus Components for ?

e-Builder

### What is your team/division name ?

e-Builder

### Are you willing to contribute ?

Yes

### Are you using Modus Web Components in production ?

yes

**Comment by apaddock** [comment]
https://app.clickup.com/t/868690163 

![image](https://github.com/trimble-oss/modus-web-components/assets/4574058/967955ff-e47e-483c-9f03-942cc9e67729)

**Comment by rthanga1** [comment]
I hope this is done now. Good to close @yohernandez ?

**Comment by yohernandez** [comment]
> I hope this is done now. Good to close @yohernandez ?

Yes, it can be closed.
