### ISSUE TITLE
Add support for the File Bar Graph and Accessibility Circle icons in the NavBar.

### ISSUE THREAD

**Issue by jcabrera87** [trimble-oss/modus-web-components#1931]
### Prerequisites

- [X] I have [searched](https://github.com/trimble-oss/modus-web-components/issues?q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [Modus style guidelines](https://modus.trimble.com/components/web/introduction/)

### Proposal

Add support for the [File Bar Graph](https://modus-icons.trimble.com/modus-solid/file-bar-graph/) and [Accessibility Circle](https://modus-icons.trimble.com/modus-solid/accessibility-circle/) icons in the NavBar.

### Motivation and context

We have our Branding solution using the Modus NavBar. We need to add some functionality via the button options in the navbar. For that functionality, we need the File Bar Graph and Accessibility Circle Icons to be available in the NavBar component.
Right now, those icons are not supported. We need them added so that we can reference it when adding the buttons to the bar. 

### What is the issue regarding ?

@trimble-oss/modus-web-components

### Priority

High

### What product/project are you using Modus Components for ?

E-Builder/Branding 

### What is your team/division name ?

E-Builder/DarkKnights

### Are you willing to contribute ?

Yes

**Comment by rthanga1** [comment]
Seems like this is implemented now. Good to close @jcabrera87 ?

**Comment by jcabrera87** [comment]
> Seems like this is implemented now. Good to close @jcabrera87 ?

Yes @rthanga1 we can close it. Thanks
