### ISSUE TITLE
Modus Navbar - Tabnavigation not working on Help Icon button

### ISSUE THREAD

**Issue by hsoni177** [trimble-oss/modus-web-components#1945]
### Prerequisites

- [X] I have [searched](https://github.com/trimble-oss/modus-web-components/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/trimble-oss/modus-web-components/blob/main/CONTRIBUTING.md)

### Describe the issue

Tab navigation does not work on the help icon button. The tabindex is missing in the help icon as in other icons.

### Reduced test cases

https://modus-web-components.trimble.com/?path=/story/components-navbar--blue-navbar

### What is the issue regarding ?

@trimble-oss/modus-web-components

### Priority

High

### What product/project are you using Modus Components for ?

e-builder

### What is your team/division name ?

e-builder

### Are you willing to contribute ?

Yes

**Comment by rthanga1** [comment]
I am able to duplicate the issue.
https://codepen.io/ramaraj-trimble/pen/qBvWWLO

**Comment by rthanga1** [comment]
This is a bug which needs to be addressed.
