### ISSUE TITLE
Enhance List Item Component to support adding sub-text

### ISSUE THREAD

**Issue by Sanket8793** [trimble-oss/modus-web-components#1957]
### Prerequisites

- [X] I have [searched](https://github.com/trimble-oss/modus-web-components/issues?q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [Modus style guidelines](https://modus.trimble.com/components/web/introduction/)

### Proposal

The scope of this change would be to add a sub-text under the slot in the Modus List Item. We will use that to show the user details in user delegation below username within e-Builder

<img width="202" alt="image" src="https://github.com/trimble-oss/modus-web-components/assets/98008242/fdde2e00-33dc-4ac0-939f-47e325dc7901">

### Motivation and context

We have a user delegation feature in e-builder which requires the company name to appear below the username. In order to maintain that feature and use the Modus NavBar, we need to add sub-text below the slot in the Modus-List-Item component. By adding support for sub-text, we can easily show a two-line dropdown using the Modus-List-Item component.

### What is the issue regarding ?

@trimble-oss/modus-web-components

### Priority

Medium

### What product/project are you using Modus Components for ?

E-Builder/Branding

### What is your team/division name ?

E-Builder/DarkKnights

### Are you willing to contribute ?

Yes

**Comment by rthanga1** [comment]
@egunther39 / @enowak1031 Can you update the guidelines fo this.
 We have like 3 different size of the list items ("condensed", "large", "standard"). We need to know the padding and the font size of sub title

**Comment by rthanga1** [comment]
@cjwinsor to fill up these details

Title will always be in single line
Subtitle can be wrapped in multiple lines
Regular:
Padding:
Min height
Title font size:
Subtitle font size:

Large:
Padding:
Min height
Title font size:
Subtitle font size:

Condensed:
Padding:
Min height
Title font size:
Subtitle font size:
