### ISSUE TITLE
Navbar Apps & User Menu Issues

### ISSUE THREAD

**Issue by ryan-henness-trimble** [trimble-oss/modus-web-components#1959]
### Prerequisites

- [X] I have [searched](https://github.com/trimble-oss/modus-web-components/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/trimble-oss/modus-web-components/blob/main/CONTRIBUTING.md)

### Describe the issue

The Apps and User menus seem to have some issues after recent updates.
I also observed an issue with buttons that do not use menus in the navbar, they display a bottom border color when the menu would have been open if it used one (see the moon button in the example images below).

Apps Menu:
- Menu padding incorrect
- Section line separator color incorrect

User Menu:
- Long username and emails incorrectly centered

Navbar Buttons with hidden menus:
- Shows bottom border line

See below after and before screenshots:

![image](https://github.com/trimble-oss/modus-web-components/assets/84749026/c9bd830a-ccb9-4634-8fce-5f22042846fa)
![image](https://github.com/trimble-oss/modus-web-components/assets/84749026/829be5dc-395b-4558-8649-a7bd7ec6e7f2)
![image](https://github.com/trimble-oss/modus-web-components/assets/84749026/35f39422-091e-4c2f-bfc6-0123299682c4)

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome

### What is the issue regarding ?

@trimble-oss/modus-web-components

### What version of npm package are you using ?

v0.9.0

### Priority

High

### What product/project are you using Modus Components for ?

Work Center

### What is your team/division name ?

Trimble Viewpoint

### Are you willing to contribute ?

Maybe

**Comment by rthanga1** [comment]
The 8 pixel was removed as part of the issue #1841. 

1. We wanted the ability have the focus/selected states in the menu to expand to the full width of the container.
2. Wanted to give the flexiblity to the user to have menu with zero border

So the recommended approach is, you can add the necessary padding in your app. Let us know if you have questions.
+ @enowak1031

**Comment by ryan-henness-trimble** [comment]
Hey @rthanga1, I think removing the padding from the customizable menus makes sense, but AFAI there's no way for the consuming devs to update the padding for the apps menu. The Navbar reads in the array of apps and has full control over the rendering for that menu unlike the menus that render slot values

@enowak1031 Any thoughts on this one? I think it's likely consumers will want some padding for the apps in this menu. It looks a bit off without any padding to me
![image](https://github.com/trimble-oss/modus-web-components/assets/84749026/3309d61f-2279-4478-af3a-831f5c78656c)

**Comment by rthanga1** [comment]
By default, we should add the 8px padding.
For the menus and for custom container, we have to set the padding to 0 px.
