### ISSUE TITLE
Add GroupRight slot to Modus Content Tree items

### ISSUE THREAD

**Issue by yohernandez** [trimble-oss/modus-web-components#1963]
### Prerequisites

- [X] I have [searched](https://github.com/trimble-oss/modus-web-components/issues?q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [Modus style guidelines](https://modus.trimble.com/components/web/introduction/)

### Proposal

Currently, the modus content tree component offers only a single slot for the label of the content tree items. 
This epic is to update the content tree to offer a slots - “groupRight” slot (similar to the slots for the modus table) 

![image](https://github.com/trimble-oss/modus-web-components/assets/48927186/b5cc7b1c-0b3c-4588-b5e8-38031f8e7e17)

This would allow the label slot to be used when only a label is needed but support actions on content where needed. 

### What is the issue regarding ?

@trimble-oss/modus-web-components

### Priority

Medium

### What product/project are you using Modus Components for ?

e-builder

### What is your team/division name ?

e-builder

### Are you willing to contribute ?

Yes

**Comment by rthanga1** [comment]
@cjwinsor To understand the requirement and the need

**Comment by cjwinsor** [comment]
@Roliver-Javier @yohernandez Before I dive into this review I have a few questions:

 - What is the purpose of the `groupLeft` slot. What is the use case for its addition?
 - What is the intended goal of `groupRight` slot. What is the use case for this addition?
 
 I want to make sure we aren't over complicating without cause.

**Comment by rjavier-trimbler** [comment]
Hi @cjwinsor 

the purpose for each group is to have content in both sides, currently we only have room to place a label and that slot has an specific role for this. The group-left slot would be for components with its own role in order to not generate confusion with the screen reader if we use the label slot as a content on the left

**Comment by apaddock** [comment]
<img width="781" alt="image" src="https://github.com/trimble-oss/modus-web-components/assets/4574058/a9c799c6-b44b-47d8-9f44-ca0026cad899">
