### ISSUE TITLE
Modus Table: Update RowSelection options with checkbox properties

### ISSUE THREAD

**Issue by yohernandez** [trimble-oss/modus-web-components#1964]
### Prerequisites

- [X] I have [searched](https://github.com/trimble-oss/modus-web-components/issues?q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [Modus style guidelines](https://modus.trimble.com/components/web/introduction/)

### Proposal

We need the checkbox component to support different sizes within the Table component. 
Within the storybook site, we need to be able to set the various properties of the modus-checkbox component for the “row selection” feature. 

rowSelectionOptions is likely the best place

### What is the issue regarding ?

@trimble-oss/modus-web-components

### Priority

Medium

### What product/project are you using Modus Components for ?

e-builder

### What is your team/division name ?

e-builder

### Are you willing to contribute ?

Yes

**Comment by rthanga1** [comment]
@cjwinsor to talk to Eric regarding this. 
Should the checkbox size depend on the table density? Or should we expose the option to the user (like in this PR)?

**Comment by prashanth-offcl** [comment]
The changes are already done hence closing this issue
