### ISSUE TITLE
Modus Table: footer/summary row should honor the density property

### ISSUE THREAD

**Issue by yohernandez** [trimble-oss/modus-web-components#1969]
### Prerequisites

- [X] I have [searched](https://github.com/trimble-oss/modus-web-components/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/trimble-oss/modus-web-components/blob/main/CONTRIBUTING.md)

### Describe the issue

The footer/summary row should honor the density property.

For comfortable
![image](https://github.com/trimble-oss/modus-web-components/assets/48927186/26fbd2be-33aa-44c9-8340-40c256485bc9)

And for compact
![image](https://github.com/trimble-oss/modus-web-components/assets/48927186/cefd820c-8a33-4d20-9b04-3e0a542a2cf1)

### What is the issue regarding ?

@trimble-oss/modus-web-components

### Priority

Medium

### What product/project are you using Modus Components for ?

e-builder

### What is your team/division name ?

e-builder

### Are you willing to contribute ?

Yes

**Comment by rthanga1** [comment]
This is approved by the modus team. But we have to do the same for the header row too.
And the padding between the pagination and the table should also decrease a litte bit

**Comment by rthanga1** [comment]
@apaddock Do you know which UX team member submitted this? I think they must have missed to mention the header. The header and the footer should be the same height.
