### ISSUE TITLE
Default column sorting for the Table component

### ISSUE THREAD

**Issue by leosole-trimble** [trimble-oss/modus-web-components#1975]
### Prerequisites

- [X] I have [searched](https://github.com/trimble-oss/modus-web-components/issues?q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [Modus style guidelines](https://modus.trimble.com/components/web/introduction/)

### Proposal

Expose a property to set a default column to be used to sort the data

### What is the issue regarding ?

@trimble-oss/modus-web-components

### Priority

Low

### What product/project are you using Modus Components for ?

Trimble Inspections

### What is your team/division name ?

Camaleão/Transportation

### Are you willing to contribute ?

Yes

**Comment by rthanga1** [comment]
Pr Merged. Closing
