### ISSUE TITLE
Autocomplete: missing Watch decorator for property 'value'

### ISSUE THREAD

**Issue by yohernandez** [trimble-oss/modus-web-components#1982]
### Prerequisites

- [X] I have [searched](https://github.com/trimble-oss/modus-web-components/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/trimble-oss/modus-web-components/blob/main/CONTRIBUTING.md)

### Describe the issue

Changing the value of the autocomplete property "value" using javascript is not being honored. The options are filtered by the previous value. The property "value" has no @Watch decorator. 

### What is the issue regarding ?

@trimble-oss/modus-web-components

### Priority

Medium

### What product/project are you using Modus Components for ?

e-builder

### What is your team/division name ?

e-builder

### Are you willing to contribute ?

Yes

**Comment by rthanga1** [comment]
Closing this one as the PR is merged.
