### ISSUE TITLE
Autocomplete: Disable browser autocomplete.

### ISSUE THREAD

**Issue by yohernandez** [trimble-oss/modus-web-components#1985]
### Prerequisites

- [X] I have [searched](https://github.com/trimble-oss/modus-web-components/issues?q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [Modus style guidelines](https://modus.trimble.com/components/web/introduction/)

### Proposal

Add a new property to allow users to disable the browser autocomplete in the input. 
`<input type="text" autocomplete="off">`

### What is the issue regarding ?

@trimble-oss/modus-web-components

### Priority

Medium

### What product/project are you using Modus Components for ?

e-builder

### What is your team/division name ?

e-builder

### Are you willing to contribute ?

Yes

**Comment by rthanga1** [comment]
Looks like you have exposed a 'autocomplete' property to the AutoCompleteInput. Trying to understand the issue here. Does this mean, the user can have a AutoComplete component with the 'autocomplete' property disabled?

**Comment by yohernandez** [comment]
@rthanga1 We want to disable the browser autocomplete/autofill behavior in the input element inside the modus-autocomplete. 
![image](https://github.com/trimble-oss/modus-web-components/assets/48927186/d90e92ec-7e91-40e3-8983-d8d7b97254d4)

**Comment by cjwinsor** [comment]
@yohernandez I don't think the autocomplete should have the option for setting this, but I can see potential value in the setting for the textbox.  So the autocomplete would just set it manually to false without giving the user a choice.  I will need to check a few other libraries to see how they handle this.
