### ISSUE TITLE
Table: Add support for wrapping text

### ISSUE THREAD

**Issue by cjwinsor** [trimble-oss/modus-web-components#1998]
### Prerequisites

- [X] I have [searched](https://github.com/trimble-oss/modus-web-components/issues?q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [Modus style guidelines](https://modus.trimble.com/components/web/introduction/)

### Proposal

The table should allow for the text to wrap, instead of being truncated.  Since the current table is setup to truncate by default, we should leave that.  My suggestion is to add a `wrap-text` property that defaults to `false`.  When enabled, it will remove the css that currently causes the body text to be truncated with ellipsis.  I do not expect this setting to affect the header or the footer.

Additionally, padding needs to be maintained.  Currently, the `<tr>` has its height set relative to its `density`.  Each column type should ensure that it's effective padding is maintained between wrapping and non-wrapping configurations.

Currently looks like this:
![image](https://github.com/trimble-oss/modus-web-components/assets/1130129/e82e1d1b-c11b-484c-9647-9bc3d435e6c6)

After changes, it could look like this:
![image](https://github.com/trimble-oss/modus-web-components/assets/1130129/b7dd3400-ce8b-4b3d-a405-3d8c51eec5fd)

### Motivation and context

Currently columns are displayed which can show a large block of text.  Since this text is truncated, users cannot scan or otherwise search for a specific row based on the value of the cell.  By adding back text wrapping, the table can function the same as a standard table and gives us the control on whether its more valuable to have fixed and predictable row heights, or all the text in the cells being displayed with irregular row heights.

### What is the issue regarding ?

@trimble-oss/modus-web-components

### Priority

Medium

### What product/project are you using Modus Components for ?

e-Builder

### What is your team/division name ?

e-Builder

### Are you willing to contribute ?

None

**Comment by apaddock** [comment]
Approved design submission to modus: https://modus.ideas.aha.io/ideas/MOD-I-19

**Comment by rthanga1** [comment]
Ewa has mentioned in the Aha that we expose a property to support wrap line to the table.
But I think the property should go to the column rather than the table itself. 
I am thinking exporting these properties to each columns

1. noWrap - Default false, when set to true the text goes to next line when the size goes beyond the width of the cell
2. maxHeight  - by default it will be set to 0. When a value is set (say for ex 50px), then the row can expand upto the set height

**Comment by apaddock** [comment]
@cjwinsor and @rthanga1 can we please clarify if this is a table level setting or a column level setting?

**Comment by cjwinsor** [comment]
> @cjwinsor and @rthanga1 can we please clarify if this is a table level setting or a column level setting?

Table Level

**Comment by rthanga1** [comment]
@cjwinsor Do you remember what we agreed on in terms of height? I mean, do we have to set a maxRowHeight to the table as well? Otherwise when wrapped, for longer texts, it can wrap to so many lines

**Comment by rthanga1** [comment]
> @cjwinsor Do you remember what we agreed on in terms of height? I mean, do we have to set a maxRowHeight to the table as well? Otherwise when wrapped, for longer texts, it can wrap to so many lines

**Chris's reply**
We don't set the height. We start with just letting it wrap. That's the minimum need. Once you introduce a fixed height, there is no telling if the exposed text has enough value to justify the wrapping or being cut off where it was.

**Comment by cjwinsor** [comment]
Should still honor #1173

**Comment by apaddock** [comment]
Questions from QA: 
What would be the behavior for the badges?

For column resize, if fullWidth is set to true, resizing one column could cause other columns to automatically adjust and their text to potentially wrap at the same time?

Is the expectation for checkboxes to stay centered vertically?

What should be the padding between wrapped lines?

Is the wrapping separating words between lines? or a word that would be broken move to the next line?

How is it expected to work for single words that are longer than the min width?

**Comment by apaddock** [comment]
@cjwinsor the answers from UX are the following, can you please review?: 

What would be the behavior for the badges?

Badges won’t wrap. They truncate in same line.

For column resize, if fullWidth is set to true, resizing one column could cause other columns to automatically adjust and their text to potentially wrap at the same time?

No, changing one column shouldn’t change the adjacent columns. 

However, the right most column will take up the free space to fill the width of the table {as if it is floated right}. Refer the image below


Is the expectation for checkboxes to stay centered?

Checkboxes are aligned vertically to the TOP.

The column should be non-resizable.

What should be the padding between wrapped lines?

Is it padding or the line height?

It should be line height and match the line height as per the guidelines for regular text. [21 Line height]

Is the wrapping separating words between lines? or a word that would be broken move to the next line?

Words don't break. They go to next line.

How is it expected to work for single words that are longer than the min width?

The single words will sit in the first line and truncate just like tags.

**Comment by rthanga1** [comment]
Guidelines are updated in the Aha
https://modus.ideas.aha.io/ideas/MOD-I-19

**Comment by cjwinsor** [comment]
> @cjwinsor the answers from UX are the following, can you please review?:
> 
> > What would be the behavior for the badges?
> 
> Badges won’t wrap. They truncate in same line.
> 
> > For column resize, if fullWidth is set to true, resizing one column could cause other columns to automatically adjust and their text to potentially wrap at the same time?
> 
> No, changing one column shouldn’t change the adjacent columns.
> 
> However, the right most column will take up the free space to fill the width of the table {as if it is floated right}. Refer the image below
> 
> > Is the expectation for checkboxes to stay centered?
> 
> Checkboxes are aligned vertically to the TOP.
> 
> The column should be non-resizable.
> 
> > What should be the padding between wrapped lines?
> 
> Is it padding or the line height?
> 
> It should be line height and match the line height as per the guidelines for regular text. [21 Line height]
> 
> > Is the wrapping separating words between lines? or a word that would be broken move to the next line?
> 
> Words don't break. They go to next line.
> 
> > How is it expected to work for single words that are longer than the min width?
> 
> The single words will sit in the first line and truncate just like tags.

This all seems good, but I don't know of a way in css that would accomplish the last part.  I don't know of both wrapping and truncating at the same time like that.

Overall, I am expecting the following styles unless testing files a better alternative or there is an issue found with this suggestion.
```css
  word-break: break-word;
  overflow-wrap: break-word;
```

And here is the relevant article: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_text/Wrapping_breaking_text
