### ISSUE TITLE
ModusFileDropzone: at the moment it doesnt support "accept" parameter to avoid users to upload any kind of files. 

### ISSUE THREAD

**Issue by jmecosta** [trimble-oss/modus-web-components#2003]
### Prerequisites

- [X] I have [searched](https://github.com/trimble-oss/modus-web-components/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/trimble-oss/modus-web-components/blob/main/CONTRIBUTING.md)

### Describe the issue

users are able to upload any kind of files causing problems in many difference scenarions.

### What is the issue regarding ?

@trimble-oss/modus-web-components

### Priority

High

### What product/project are you using Modus Components for ?

Tekla Structures Launcher

### What is your team/division name ?

Structures

### Are you willing to contribute ?

No

**Comment by coliff** [comment]
Good suggestion. I'd imagine this would be relatively straight-forward to add too.

REF: https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/accept

**Comment by cjwinsor** [comment]
Add an `accept` prop to the file upload component.
