### ISSUE TITLE
Storybook keyboard shortcuts should not be honored when experimenting with components in canvas 

### ISSUE THREAD

**Issue by apaddock** [trimble-oss/modus-web-components#2034]
### Prerequisites

- [X] I have [searched](https://github.com/trimble-oss/modus-web-components/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/trimble-oss/modus-web-components/blob/main/CONTRIBUTING.md)

### Describe the issue

in various components (autocomplete is the one I can think of) when typing "a" or "s" into the autocomplete component the storybook site hides the controls window or side navigation. This should not happen. 

### What operating system(s) are you seeing the problem on?

Windows, macOS

### What browser(s) are you seeing the problem on?

Chrome

### What is the issue regarding ?

@trimble-oss/modus-web-components

### What version of npm package are you using ?

latest

### Priority

Medium

### What product/project are you using Modus Components for ?

e-Builder

### What is your team/division name ?

e-Builder

### Are you willing to contribute ?

Yes

### Are you using Modus Web Components in production ?

yes

**Comment by ElishaSamPeterPrabhu** [comment]
The shortcuts are disabled and am not able to reproduce 

@jewel-shajan Can you confirm?

**Comment by jewel-shajan** [comment]
> The shortcuts are disabled and am not able to reproduce
> 
> [@jewel-shajan](https://github.com/jewel-shajan) Can you confirm?

The issue could not be reproduced, therefore it is being closed.
