### ISSUE TITLE
Add Active/Pressed State to Navbar Buttons

### ISSUE THREAD

**Issue by Sanket8793** [trimble-oss/modus-web-components#2035]
### Prerequisites

- [X] I have [searched](https://github.com/trimble-oss/modus-web-components/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/trimble-oss/modus-web-components/blob/main/CONTRIBUTING.md)

### Describe the issue

Currently all navbar buttons have no add active/pressed state so they need to be added on button click.

### What is the issue regarding ?

@trimble-oss/modus-web-components

### Priority

Medium

### What product/project are you using Modus Components for ?

E-Builder/Branding

### What is your team/division name ?

E-Builder/DarkKnights

### Are you willing to contribute ?

Yes

**Comment by cjwinsor** [comment]
This ticket was discussed in a meeting with the two teams.  I'm waiting to hear if they need technical help to resolve their need here after they check their options with gainsight.
