### ISSUE TITLE
Modus Icon: Event Name is `iconClick`, not `onClick` as shown in Storybook and clicking causes error

### ISSUE THREAD

**Issue by cjwinsor** [trimble-oss/modus-web-components#2058]
### Prerequisites

- [X] I have [searched](https://github.com/trimble-oss/modus-web-components/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/trimble-oss/modus-web-components/blob/main/CONTRIBUTING.md)

### Describe the issue

Component creates `iconClick` event
```tsx
  @Event() iconClick?: EventEmitter;
```
But Storybook shows it has having an `onClick` event that is emitted
![image](https://github.com/trimble-oss/modus-web-components/assets/1130129/790dda79-14a1-4c09-a986-bdd381d0b20d)

And when the icon is clicked it produces an error
```
Uncaught TypeError: Cannot read properties of undefined (reading 'emit')
    at Object.onClick (25.cf0f1bcf.iframe.bundle.js:1:2565)
    at IconSun.Object.onClick (0.fb127b46.iframe.bundle.js:1:421530)
```

This is caused by the icons onClick being set as
```html
<IconMap ... onClick={this.onClick} ... />
```
when it should be this at minimum to maintain the `this` context.  
```html
<IconMap ... onClick={() => this.onClick()} ... />
```

Otherwise the context will be the icon from the icon map, not the modus-icon.

I am creating this ticket so I can work on it later.

### Reduced test cases

In Storybook for MWC, navigate to the Icon component and click on the icon. Observer the javascript error in the dev console.

### What is the issue regarding ?

@trimble-oss/modus-web-components

### What version of npm package are you using ?

v0.13.0

### Priority

Medium

### What product/project are you using Modus Components for ?

Modus

### What is your team/division name ?

Modus

### Are you willing to contribute ?

Maybe

**Comment by ElishaSamPeterPrabhu** [comment]
Closing this issue as it is fixed in #2201
