### ISSUE TITLE
Navbar: Responsive Profile Menu link text (wrap)

### ISSUE THREAD

**Issue by ryan-henness-trimble** [trimble-oss/modus-web-components#2085]
### Prerequisites

- [X] I have [searched](https://github.com/trimble-oss/modus-web-components/issues?q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [Modus style guidelines](https://modus.trimble.com/components/web/introduction/)

### Proposal

The Modus Navbar's link items should have responsive text so that they do not overflow the menu's width.

![image](https://github.com/trimble-oss/modus-web-components/assets/84749026/09802fe1-4c7d-44d9-8a80-1762ada46c66)

### What is the issue regarding ?

@trimble-oss/modus-web-components

### Priority

Medium

### What product/project are you using Modus Components for ?

Work Center

### What is your team/division name ?

Trimble Viewpoint

### Are you willing to contribute ?

Yes

**Comment by enowak1031** [comment]
Approved: https://trimble-arch.aha.io/ideas/ideas/MOD-I-86

Our recommendation is to use 1-2 words for list items in the profile menu. If it must be longer, you should truncate; However, wrapping is allowed as long as the line height between the list items is larger than the line height between the wrapped lines.

**Comment by prashanth-offcl** [comment]
We decided wrapping the text to next line is better than truncating it so closing this issue. @ryan-henness-trimble if you have any other suggestion please add your comment.
