### ISSUE TITLE
[Modus-Table] Allow translated strings for pagination and sorting.

### ISSUE THREAD

**Issue by janwiebe-glasbergen** [trimble-oss/modus-web-components#2108]
### Prerequisites

- [X] I have [searched](https://github.com/trimble-oss/modus-web-components/issues?q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [Modus style guidelines](https://modus.trimble.com/components/web/introduction/)

### Proposal

The modus-table component contains some hardcoded English strings. As shown in the below screenshot:
![image](https://github.com/trimble-oss/modus-web-components/assets/116563683/23f0eef2-764b-4476-9343-d08c64c07383)

As a developer I would like to be able to provide custom values for these strings, so that I can support multiple languages.

### Motivation and context

We are planning to release a UI component, that uses the modus-table, which will be used in a multi-language product.

### What is the issue regarding ?

@trimble-oss/modus-web-components

### Priority

High

### What product/project are you using Modus Components for ?

Nova / Construction calculation platform UI

### What is your team/division name ?

ACDC

### Are you willing to contribute ?

Maybe

**Comment by prashanth-offcl** [comment]
@prashanth-offcl to check and decide on the approach for translation.

**Comment by janwiebe-glasbergen** [comment]
@prashanth-offcl Any updates on this issue?

**Comment by enowak1031** [comment]
We think we should support French, Finnish, Spanish, German, and Italian to begin with. But would like to start with the requester's language. It appears to be French. Could you @janwiebe-glasbergen provide appropriate translations and confirm the language?

**Comment by enowak1031** [comment]
Prashanth talked to the requester. He needs French and German and later Dutch.
