### ISSUE TITLE
[Modus-Table] Pagination is not working when enabled without refreshing

### ISSUE THREAD

**Issue by janwiebe-glasbergen** [trimble-oss/modus-web-components#2109]
### Prerequisites

- [X] I have [searched](https://github.com/trimble-oss/modus-web-components/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/trimble-oss/modus-web-components/blob/main/CONTRIBUTING.md)

### Describe the issue

The pagination of the modus-table is not working correctly when it get's enabled after the page loaded. 
It looks like the 'showing result' and pages are rendered correctly, but the data in the table is never updated.

After a refresh of the web-page the pagination works like expected.

### Reduced test cases

Steps to reproduce in storyboard canvas:
- Open the default modus-table
- Set the pageSizeList prop to `[2,3,5]`
- Set the pagination prop to `true`
- Pagination is shown, but not working correctly:
  - Before showing the pagination there is a short period in when it shows:  'Showing result NaN - NaN of 5' (see image).
 ![image](https://github.com/trimble-oss/modus-web-components/assets/116563683/8a6573a5-ae15-4e75-9c41-c437de9521d3)
  - Total count shows 'showing result 1 - 2 of 5', but table shows all 5 results.
  - Switching the page doesn't affect the result in the table
  - Switching the page view doesn't affect the result in the table

![invalid table](https://github.com/trimble-oss/modus-web-components/assets/116563683/e3f0f43e-1cdd-45ba-8e1b-7a2b8b0bd3b9)

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome

### What is the issue regarding ?

@trimble-oss/modus-web-components

### Priority

High

### What product/project are you using Modus Components for ?

Nova / Construction calculation platform UI

### What is your team/division name ?

ACDC

### Are you willing to contribute ?

Maybe

**Comment by cjwinsor** [comment]
@cjwinsor Check if this is resolved with latest release

**Comment by cjwinsor** [comment]
@janwiebe-glasbergen As of v22 this seems to be resolved. If you are still experiencing this issue, let me know and we can reopen the ticket and re-investigate.
