### ISSUE TITLE
Autocomplete: Tab "X" icon in the autocomplete field is part of the tabbing sequence

### ISSUE THREAD

**Issue by mltejada** [trimble-oss/modus-web-components#2132]
### Prerequisites

- [X] I have [searched](https://github.com/trimble-oss/modus-web-components/issues?q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [Modus style guidelines](https://modus.trimble.com/components/web/introduction/)

### Proposal

Tab: "X" icon in the autocomplete field is part of the tabbing sequence

This is a part of the approved Modus submission: https://modus.ideas.aha.io/ideas/MOD-I-14

### Motivation and context

Related to https://github.com/trimble-oss/modus-web-components/issues/979

### What is the issue regarding ?

@trimble-oss/modus-web-components

### Priority

Medium

### What product/project are you using Modus Components for ?

e-builder

### What is your team/division name ?

e-builder

### Are you willing to contribute ?

Yes

**Comment by yevhenkravets** [comment]
@cjwinsor Can you close this issue as well, please?
