### ISSUE TITLE
Tabel: Icon not found for the row actions when more then four actions are added

### ISSUE THREAD

**Issue by sorina-ocheana** [trimble-oss/modus-web-components#2145]
### Prerequisites

- [X] I have [searched](https://github.com/trimble-oss/modus-web-components/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/trimble-oss/modus-web-components/blob/main/CONTRIBUTING.md)

### Describe the issue

When more than four row actions are added the icon for the overflow menu button is not found.
![chrome_9Gz5eRIozQ](https://github.com/trimble-oss/modus-web-components/assets/99886593/7bd6f92c-c253-4a4f-a59d-68af2d4fff27)

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome

### What is the issue regarding ?

@trimble-oss/modus-web-components

### What version of npm package are you using ?

v0.16.0

### Priority

Medium

### What product/project are you using Modus Components for ?

ADMS

### What is your team/division name ?

ADMS - team Red

### Are you willing to contribute ?

Yes

**Comment by ElishaSamPeterPrabhu** [comment]
The issue exists with cancel icon in row actions column
![image](https://github.com/user-attachments/assets/420e69b6-a611-418d-9106-fb751850246f)
