### ISSUE TITLE
Navbar: Logo doesn't appear in storybook examples

### ISSUE THREAD

**Issue by cjwinsor** [trimble-oss/modus-web-components#2206]
### Prerequisites

- [X] I have [searched](https://github.com/trimble-oss/modus-web-components/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/trimble-oss/modus-web-components/blob/main/CONTRIBUTING.md)

### Describe the issue

Examples in storybook aren't showing the Trimble logo

### Reduced test cases

View storybook for navbar.  Incorrectly using `logo` prop instead of `logoOptions` prop.

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome

### What is the issue regarding ?

@trimble-oss/modus-web-components

### What version of npm package are you using ?

v0.18.0

### Priority

Medium

### What product/project are you using Modus Components for ?

Modus

### What is your team/division name ?

Modus

### Are you willing to contribute ?

Yes

**Comment by coliff** [comment]
Fixed with: #2207
