### ISSUE TITLE
Radio Group: What is a name?

### ISSUE THREAD

**Issue by kuhnboy** [trimble-oss/modus-web-components#2213]
### Prerequisites

- [X] I have [searched](https://github.com/trimble-oss/modus-web-components/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/trimble-oss/modus-web-components/blob/main/CONTRIBUTING.md)

### Describe the issue

When reviewing the radio group documentation (https://modus-web-components.trimble.com/?path=/docs/user-inputs-radio-group) there is a name attribute. What purpose does the name attribute serve? It is not a label, and is not an ID otherwise, I would assume it would be named Id.

### What is the issue regarding ?

@trimble-oss/modus-web-components

### What version of npm package are you using ?

0.16.0

### Priority

Low

### What product/project are you using Modus Components for ?

ModusBlazor

### What is your team/division name ?

AECO

### Are you willing to contribute ?

None

**Comment by austinoneil** [comment]
`name` (see [this](https://github.com/trimble-oss/modus-web-components/blob/main/stencil-workspace/src/components/modus-radio-group/modus-radio-button.tsx#L31)) corresponds to the `name` attribute on the `input` element.  This [StackOverflow response](https://stackoverflow.com/questions/26061651/what-is-the-purpose-of-the-html-name-attribute) answers the question pretty well. tl;dr it's related to forms.

**Comment by coliff** [comment]
thanks @austinoneil  - the production site will update when there is a new release (expected Thursday 4th)
