### ISSUE TITLE
Tree View With Item Action Bar Not Rendering As Expected.

### ISSUE THREAD

**Issue by kuhnboy** [trimble-oss/modus-web-components#2219]
### Prerequisites

- [X] I have [searched](https://github.com/trimble-oss/modus-web-components/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/trimble-oss/modus-web-components/blob/main/CONTRIBUTING.md)

### Describe the issue

I am having an issue running an example that shows an item with action bar:

<img width="809" alt="image" src="https://github.com/trimble-oss/modus-web-components/assets/1281472/d944c805-1cf6-40aa-8f16-db3e6c97e452">

With the same exact code, I am rendering this:

<img width="343" alt="image" src="https://github.com/trimble-oss/modus-web-components/assets/1281472/beb45b30-e1f5-4f61-a9c9-a959c07c5128">

Expectation: Icons should render.

Sample Code:
```html
<div>
        <modus-tree-view style="width:400px;" checkbox-selection="false" checked-items="false" expanded-items="false"
            multi-checkbox-selection="false" multi-selection="false" selected-items="false" size="" class="hydrated">
            <modus-tree-view-item node-id="1" label="Inbox" class="hydrated"></modus-tree-view-item>
        </modus-tree-view>
    </div>
    <script>
        function loadActions() {
            document.querySelector('[node-id="1"]').actions = [
                { id: 'export', icon: 'export', label: 'Export' },
                { id: 'history', icon: 'history', label: 'History' },
                { id: 'edit', icon: 'pencil', label: 'Edit' },
            ];
        }
        loadActions();
    </script>
```

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Microsoft Edge

### What is the issue regarding ?

@trimble-oss/modus-web-components

### What version of npm package are you using ?

0.16.0

### Priority

Medium

### What product/project are you using Modus Components for ?

ModusBlazor

### What is your team/division name ?

AECO

### Are you willing to contribute ?

None

**Comment by cjwinsor** [comment]
@kuhnboy Action items were added to the content tree in version 17. I see on your ticket you are using version 16. Can you verify on latest version?
https://codepen.io/cjwinsor/pen/xxeKPrW

**Comment by kuhnboy** [comment]
You're right. Sorry about that!.
