### ISSUE TITLE
Pagination Documentation Size Enumeration

### ISSUE THREAD

**Issue by kuhnboy** [trimble-oss/modus-web-components#2228]
### Prerequisites

- [X] I have [searched](https://github.com/trimble-oss/modus-web-components/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/trimble-oss/modus-web-components/blob/main/CONTRIBUTING.md)

### Describe the issue

The pagination size 'size' column overflwos the table and it's hard to tell that the default is 'medium'.

<img width="852" alt="image" src="https://github.com/trimble-oss/modus-web-components/assets/1281472/a2c926d3-1e60-42f4-8bd3-5e381d6697ac">

### What browser(s) are you seeing the problem on?

Microsoft Edge

### What is the issue regarding ?

Modus Web Components Website (Storybook)

### What version of npm package are you using ?

0.16.0

### Priority

Low

### What product/project are you using Modus Components for ?

ModusBlazor

### What is your team/division name ?

AECO

### Are you willing to contribute ?

None

**Comment by prashanth-offcl** [comment]
@kuhnboy Thanks for raising this issue, the default is medium. The documentation issue is fixed now. 
![image](https://github.com/user-attachments/assets/7760b174-5405-4356-8d04-d1ea929e0dfd)
