### ISSUE TITLE
Create new Toolbar component

### ISSUE THREAD

**Issue by cjwinsor** [trimble-oss/modus-web-components#2238]
### Prerequisites

- [X] I have [searched](https://github.com/trimble-oss/modus-web-components/issues?q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [Modus style guidelines](https://modus.trimble.com/components/web/introduction/)

### Proposal

Breaking down #1420 

Implement the toolbar to match existing guidelines.

### What is the issue regarding ?

@trimble-oss/modus-web-components

### Priority

Medium

### What product/project are you using Modus Components for ?

Modus

### What is your team/division name ?

Modus

### Are you willing to contribute ?

Yes

**Comment by ElishaSamPeterPrabhu** [comment]
![image](https://github.com/trimble-oss/modus-web-components/assets/122255626/faeb8b72-f399-4fe6-894d-372b8c40143d)

- Should the buttons have a selected state?

- Existing borderless buttons can be used, can we use those?

-  Are borderless black icon or text buttons only allowed?

https://github.com/trimble-oss/modus-web-components/assets/122255626/8d5e827b-a9ff-4080-ae00-020c0a17706d

**Comment by cjwinsor** [comment]
This is what we are thinking is how a user would construct

```jsx
<modus-toolbar>
  <modus-button>Submit</modus-button>
  <modus-button icon-only="pencil"></modus-button>
  <modus-button icon-only="delete"></modus-button>
  <modus-divider></modus-divider>
  <modus-button icon-only="close"></modus-button>
</modus-toolbar>
```

Borderless and Secondary Color
