### ISSUE TITLE
Accordions should allow for custom icon on left-side

### ISSUE THREAD

**Issue by coliff** [trimble-oss/modus-web-components#2258]
Example:
![309766826-e5cdf973-1988-4725-9cce-ff4ea13f35bb](https://github.com/trimble-oss/modus-web-components/assets/1212885/a96e548f-9954-46f9-b3a6-bc2a42860083)

**Comment by cjwinsor** [comment]
add property for `icon` and use the `ModusIconMap`.  Test for it being set and not being set work correctly.
