### ISSUE TITLE
Autocomplete: value of valueChange event is empty string "" even though there's some options selected

### ISSUE THREAD

**Issue by Gnirps00** [trimble-oss/modus-web-components#2275]
### Prerequisites

- [X] I have [searched](https://github.com/trimble-oss/modus-web-components/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/trimble-oss/modus-web-components/blob/main/CONTRIBUTING.md)

### Describe the issue

Currently when some option is selected, both optionSelected and valueChange events are triggered. 
When some option is unselected using chips, only valueChange event is triggered. 
When the string in input area changes, only valueChange event is triggered in this case too.

Value of target/datail of event is "" after erasing the last letter in input, even though there's some options selected. 
Value of target/datail of event is "" after closing the last chip.

So now, we cannot differentiate if the last chip is closed or the last letter of string is erased from input, as both triggers same valueChange event, where eventIn.detail = "" in both cases.

Thus we either need another event for closing chips or value should NOT be "" if there's still some options selected. 

### What browser(s) are you seeing the problem on?

Chrome

### What is the issue regarding ?

@trimble-oss/modus-web-components

### What version of npm package are you using ?

v.0.20.0

### Priority

High

### What product/project are you using Modus Components for ?

Tekla Structures Launcher

### What is your team/division name ?

Structures SuDO team

### Are you willing to contribute ?

No

**Comment by cjwinsor** [comment]
Review event handling, make sure that events are firing meaningful information for both adding and removing the selection on items.  Make sure multiple mode is handled as well. Investigate a better way to get the multiple values selected as a comma separated list is not idea as the options themselves could have commas in them.  Investigate array.

**Comment by ElishaSamPeterPrabhu** [comment]
> Review event handling, make sure that events are firing meaningful information for both adding and removing the selection on items. Make sure multiple mode is handled as well. Investigate a better way to get the multiple values selected as a comma separated list is not idea as the options themselves could have commas in them. Investigate array. See [#2585](https://github.com/trimble-oss/modus-web-components/issues/2585) for value stuff.

This [P.R](https://github.com/trimble-oss/modus-web-components/issues/2585#2586) the selectionsChanged event is added to emit event after selecting and deselecting values, , which are not comma separated rather an array is set with the selected values.
