### ISSUE TITLE
Localization for Numbers

### ISSUE THREAD

**Issue by enowak1031** [trimble-oss/modus-web-components#2280]
1. Numerical inputs add a selectable pattern in a global context with option for "." and ","  
allow depending on localisation: 123456789,12345
allow depending on localisation: 123456789.12345 
2. Include option of spaces as a divider. This way users are not confused by multiple "." or "," ( e.g. 123.456.789,12 or 123,456,789.12)
allow depending on localisation: 123 456 789,12345
allow depending on localisation: 123 456 789.12345
3. Add the ability to limit the number of characters before and after a "." or ",". This would ensure that people only enter valid numbers, and would reduce errors.
e.g. 9 characters before and 2 after "." or "," 
allow depending on localisation: 123456789,12
allow depending on localisation: 123456789.12

**Comment by austinoneil** [comment]
I think this can be achieved using [autoNumeric](https://github.com/autoNumeric/autoNumeric).

**Comment by ElishaSamPeterPrabhu** [comment]
@enowak1031 @coliff Some pattern to be followed for the currency part ?(Initial Release)
