### ISSUE TITLE
Revise Input Field Formatting

### ISSUE THREAD

**Issue by enowak1031** [trimble-oss/modus-web-components#2281]
- Add a stronger border all around input fields (like in Mobile)
- Do not recommend/ remove placeholder

https://trimble-arch.aha.io/ideas/ideas/MOD-I-10

Related Issue: #2517

**Comment by cjwinsor** [comment]
https://www.figma.com/design/wyfVJUHWRMkeCfdB38HFEE/Modus---Web?node-id=1346-5&t=Jo4Qe8SbWNVY43O5-0

This figma shows the updated styling for inputs, this ticket is to apply to all inputs accordingly.
