### ISSUE TITLE
Autocomplete Behavior

### ISSUE THREAD

**Issue by enowak1031** [trimble-oss/modus-web-components#2282]
https://trimble-arch.aha.io/ideas/ideas/MOD-I-35

1.) New flavor of autocomplete that shows all items when opened (rather than only showing items based on user input). I believe this needs to be a flavor only for the use cases when the list within the autocomplete is way too long. a.) it would confuse the user why everything is showing without knowing any context, and b,) it could take forever to load a potenially irrelevant list. 

2.) Scroll the list to the selected item (to assure user of their selection): once the user selects something from the autocomplete list, and reopens the autocomplete, they should see their selection within the context of the list. The already selected item item shows with a checkmark on the right and is the second one from the bottom of the list. 

**This is going to be addressed in a separate issue:** 
3.) If this is a multliselect autocomplete: show chips ABOVE the input field (not inside). When chips are created, and the field is reopened, the first selection in alphabetical order should be visible as the second from the bottom (unless it's the first one in the list or the last one in the list). 

https://github.com/trimble-oss/modus-web-components/issues/2446

**Comment by apaddock** [comment]
@cjwinsor or @enowak1031 when will this be approved for engineering?

**Comment by enowak1031** [comment]
@apaddock This is approved and ready to be worked on! I broke the story up to exclude #3 on the list. But you can break it up further, if need be.

**Comment by cjwinsor** [comment]
@apaddock Discussed with team, and these requirements are approved to be implemented.
