### ISSUE TITLE
Table: Autocomplete Cell Picker

### ISSUE THREAD

**Issue by cjwinsor** [trimble-oss/modus-web-components#2311]
### Prerequisites

- [X] I have [searched](https://github.com/trimble-oss/modus-web-components/issues?q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [Modus style guidelines](https://modus.trimble.com/components/web/introduction/)

### Proposal

We should support using the modus-autocomplete as a `cellEditorType`.  The scope of this is on edit, show autocomplete and on item select to set the value of the cell.  Make sure it works with text, badge, and hyperlink columns.

### What is the issue regarding ?

@trimble-oss/modus-web-components

### Priority

Medium

### What product/project are you using Modus Components for ?

Modus

### What is your team/division name ?

Modus

### Are you willing to contribute ?

None

**Comment by ElishaSamPeterPrabhu** [comment]
![Image](https://github.com/trimble-oss/modus-web-components/assets/122255626/ba160d03-6b2b-4f6c-970e-d865a76fa1fa)

The support of autocomplete is present, any more modifications required?
