### ISSUE TITLE
Storybook - Update Storybook (when available) to fix security vulnerabilities

### ISSUE THREAD

**Issue by ryan-henness-trimble** [trimble-oss/modus-web-components#242]
We have 2 security vulnerabilities (dependencies `immer`, and `trim`) caused by the current version of Storybook packages. Make sure these packages are upgraded when released.

**Comment by coliff** [comment]
I think this issue can be closed now? I don't think the 2 security vulnerabilities (dependencies immer, and trim) are no longer an issue as we've since merged many PRs updating dev deps.
