### ISSUE TITLE
Dropdown: Border of dropdown list fix

### ISSUE THREAD

**Issue by bradley-eb** [trimble-oss/modus-web-components#2426]
### Prerequisites

- [X] I have [searched](https://github.com/trimble-oss/modus-web-components/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/trimble-oss/modus-web-components/blob/main/CONTRIBUTING.md)

### Describe the issue

<img width="389" alt="image" src="https://github.com/trimble-oss/modus-web-components/assets/135632243/695f22e7-e28f-4e64-adcb-65f293641f91">

We recently created a dropdown with action buttons in microfrontends using modus-react-components. But we noticed that the border of dropdown is partially hidden when the list is opened.
```html
<ModusDropdown
      toggleElementId={toggleElementId}
      customPlacement={{ right: 5 }}
    >
      <ModusButton
        id={toggleElementId}
        ariaLabel="more options"
        buttonStyle="borderless"
        color="secondary"
        iconOnly="more_vertical"
        slot="dropdownToggle"
      />
      <ModusList slot="dropdownList">
        {options?.map((option) => (
          <ModusListItem
            key={option.id}
            size="condensed"
            borderless
            onClick={option.onClick}
          >
            {option.label}
          </ModusListItem>
        ))}
      </ModusList>
    </ModusDropdown>
```

### What operating system(s) are you seeing the problem on?

macOS

### What browser(s) are you seeing the problem on?

Chrome

### What is the issue regarding ?

@trimble-oss/modus-web-components

### What version of npm package are you using ?

"@trimble-oss/modus-react-components": "^0.23.0-react18"

### Priority

Medium

### What product/project are you using Modus Components for ?

e-Builder

### What is your team/division name ?

Navigators

### Are you willing to contribute ?

None

**Comment by cjwinsor** [comment]
Looks like the drop down is supposed to scroll at 200px and its popping out of that block instead.  Solution would be to get it to scroll properly.

**Comment by J-Ruiz1** [comment]
Validated in the [preview environment](https://deploy-preview-2482--moduswebcomponents.netlify.app/), working as expected.
https://e-builderinc.atlassian.net/browse/NAV-606

Scenario 1: Validate that the dropdown list shows all items correctly when the number of items to show is of 6 or less

![Untitled](https://github.com/trimble-oss/modus-web-components/assets/152913830/fcb795e9-7422-440b-afb8-31d5d719a3da)


Scenario 2: Validate that the dropdown list shows a scrollbar when the number of items to show if of 7 or greater

![Untitled](https://github.com/trimble-oss/modus-web-components/assets/152913830/cf14fa6b-b323-4c91-b1b7-238ba1d354e6)

![Untitled](https://github.com/trimble-oss/modus-web-components/assets/152913830/74d5fc7e-aed6-413c-8be0-46c22c9f326f)
