### ISSUE TITLE
Toast: dismiss/close button is incorrect color on iOS

### ISSUE THREAD

**Issue by coliff** [trimble-oss/modus-web-components#2463]
### Prerequisites

- [X] I have [searched](https://github.com/trimble-oss/modus-web-components/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/trimble-oss/modus-web-components/blob/main/CONTRIBUTING.md)

### Describe the issue

Toast: dismiss/close button is incorrect color on iOS

### Reduced test cases

Open: https://moduswebcomponents.netlify.app/?path=/story/components-toast--default&args=dismissible:true or https://coliff.github.io/modus-web-components-example/#toast on an iPad or iPhone.
Observe that the dismiss button is blue. 

### What operating system(s) are you seeing the problem on?

iOS

### What browser(s) are you seeing the problem on?

Safari

### What is the issue regarding ?

Modus Web Components Website (Storybook)

### What version of npm package are you using ?

v0.26.1

### Priority

Medium

### What product/project are you using Modus Components for ?

Modus

### What is your team/division name ?

Modus

### Are you willing to contribute ?

Yes

### Are you using Modus Web Components in production ?

https://modus-web-components.trimble.com/

**Comment by ElishaSamPeterPrabhu** [comment]
@coliff 
The issue cannot be reproduced in the latest version 0.41.1

![image](https://github.com/user-attachments/assets/b8557b0b-6c31-4e50-b98f-42625a5bb02b)
![image](https://github.com/user-attachments/assets/8fe32670-9795-4aef-9664-26d843eff214)
![image](https://github.com/user-attachments/assets/86673b4c-46be-48fe-a820-f3168dedf349)

Can you confirm this?

**Comment by coliff** [comment]
thanks for checking. Feel free to close this then.
