### ISSUE TITLE
SPIKE: Add custom HTML to table cell

### ISSUE THREAD

**Issue by enowak1031** [trimble-oss/modus-web-components#2488]
Related to #1923

**Comment by ElishaSamPeterPrabhu** [comment]
Tanstack API list  consists of this flexRender which renders cell content
https://tanstack.com/table/v8/docs/api/core/cell
Status (so far): Unable to the api in our imported "table-core" , it is specfically available in "react-table"

We can do something similar to table-cell-formatter.tsx to flexRenderer
where the code is taken from - https://github.com/TanStack/table/blob/main/packages/react-table/src/index.tsx 
FlexRenderer code available in - https://github.com/TanStack/table/blob/main/packages/angular-table/src/flex-render.ts

or we can stick to the current InnerHtml approach
