### ISSUE TITLE
SPIKE: Add custom sorting function to table columns

### ISSUE THREAD

**Issue by cjwinsor** [trimble-oss/modus-web-components#2505]
References: #1602
https://tanstack.com/table/latest/docs/guide/sorting

Define what the function needs to be that is passed to `sortingFn` such that the end user can define their own custom sorting functions.  Ideally they would pass a function like `(a, b) = > { // implementation }`. 

Document the shape of the expected function and if we need or want to simplify it.

**Comment by prashanthr6383** [comment]
@cjwinsor This is an example of custom sorting function the users can use prop  `sortingFn : sortStatusFn` and define 
`const sortStatusFn: SortingFn<Person> = (rowA, rowB, _columnId) => {
  const statusA = rowA.original.status
  const statusB = rowB.original.status
  const statusOrder = ['single', 'complicated', 'relationship']
  return statusOrder.indexOf(statusA) - statusOrder.indexOf(statusB)
}`

**Comment by cjwinsor** [comment]
Based on this, we are good to create a story to add examples into the storybook.

**Comment by prashanthr6383** [comment]
@cjwinsor Added the detailed documentation for custom sorting

[Modus table - Custom sorting.docx](https://github.com/trimble-oss/modus-web-components/files/15454031/Modus.table.-.Custom.sorting.docx)
