### ISSUE TITLE
[Modus-table] tableCore is called before it's initialized

### ISSUE THREAD

**Issue by janwiebe-glasbergen** [trimble-oss/modus-web-components#2507]
### Prerequisites

- [X] I have [searched](https://github.com/trimble-oss/modus-web-components/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/trimble-oss/modus-web-components/blob/main/CONTRIBUTING.md)

### Describe the issue

When using the modus table component an error occurs in the console:
```
TypeError: Cannot read properties of undefined (reading 'setState')
    at ModusTable.onDataChange (modus-table.entry.js:3931:24)
    at index-8e730124.js:1811:54
    at Array.map (<anonymous>)
    at setValue (index-8e730124.js:1808:34)
    at HostElement.set [as data] (index-8e730124.js:1859:25)
    at NoneEncapsulationDomRenderer.setProperty (platform-browser.mjs:645:17)
    at elementPropertyInternal (core.mjs:10980:18)
    at Module.ɵɵproperty (core.mjs:21752:9)
```

This seems to occur because the `tableCore` of the modus-table is used before it's intialized. 

### Reduced test cases

The issue is reproducible by going to https://modus-web-components.trimble.com/?path=/story/components-table--default and switch to the hover option
![Bug](https://github.com/trimble-oss/modus-web-components/assets/116563683/ae158406-67bf-40d4-aab3-21505f793d7d)

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome

### What is the issue regarding ?

@trimble-oss/modus-web-components

### What version of npm package are you using ?

0.22.0

### Priority

Medium

### What product/project are you using Modus Components for ?

Nova / Construction calculation platform UI

### What is your team/division name ?

ACDC

### Are you willing to contribute ?

No

**Comment by sami-raboun** [comment]
@cjwinsor Any updates on this? We are also running into this.
