### ISSUE TITLE
Yellow Trimble Button

### ISSUE THREAD

**Issue by enowak1031** [trimble-oss/modus-web-components#2518]
Based on a submission: https://trimble-arch.aha.io/ideas/ideas/MOD-I-74

Waiting on Figma updates: https://jira.trimble.tools/browse/MODUS-48

**Comment by enowak1031** [comment]
Ready to be worked on as soon as it's added to Figma: https://jira.trimble.tools/browse/MODUS-48

**Comment by cjwinsor** [comment]
Here is the current figma: https://www.figma.com/design/wyfVJUHWRMkeCfdB38HFEE/branch/HhwBPZMduSiJxnXcaxjmrJ/Modus---Web?node-id=1346-14&t=Zwp6r13IIibED8mU-0

Create a new section as the last section for "Special Button" which will showcase the yellow variant of the button.  The color will be set as  "special" for the prop.  Use similar text as shown below from the figma that this is a special case button.  Highlight that it doesn't have a borderless or an outline variant.  

Do the same for "Danger Button", remove it from the overall examples and isolate it to its own section, with the same callouts for not having a borderless or outline variant.

Update any place that calls out special handling for Danger and make sure the same is done for Special.  Use best judgement on wording given that we are breaking up these sections

![Image](https://github.com/user-attachments/assets/20bdece3-5232-47ce-8c3f-2065e704389d)
