### ISSUE TITLE
Full Screen Modal

### ISSUE THREAD

**Issue by enowak1031** [trimble-oss/modus-web-components#2521]
Based on the submission: https://trimble-arch.aha.io/ideas/ideas/MOD-I-71

To be added to Figma by Dafnee Z.

**Comment by cjwinsor** [comment]
Pending merging of final design into figma.  Open questions are:
* Will it have expand collapse at this phase or have it come later
* Assuming we will have a `fullscreen` prop to control initial state

**Comment by cjwinsor** [comment]
Initial work was done to add a method/prop to set the modal as fullscreen.  Additional work is still required to add an icon to toggle between the normal and full screen states


![Image](https://github.com/user-attachments/assets/b7186aec-3bd2-4f2c-aa33-7f5dc7ca03e8)
