### ISSUE TITLE
Autocomplete: Multiple values unrecognized from option list

### ISSUE THREAD

**Issue by anaith1903** [trimble-oss/modus-web-components#2528]
### Prerequisites

- [X] I have [searched](https://github.com/trimble-oss/modus-web-components/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/trimble-oss/modus-web-components/blob/main/CONTRIBUTING.md)

### Describe the issue

When using Modus autocomplete with multi-select, the component behaves inconsistently based on initialization. If initialized with a single option, it recognizes  the value from list of options, allowing further selections. With no initial value, users can select options from the list, which are styled as chips. 
However, if initialized with multiple options (as a comma-separated list), the component fails to recognize them, displays a "no results found" message, and prevents further selections. Ideally, the autocomplete should recognize comma-separated values from the list, display them as chips, and allow additional selections.

### Reduced test cases

https://codepen.io/Anaith-A/pen/KKLdLjO?editors=1010

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome

### What is the issue regarding ?

@trimble-oss/modus-web-components

### What version of npm package are you using ?

v0.28.0

### Priority

High

### What product/project are you using Modus Components for ?

Sector portal

### What is your team/division name ?

Maps

### Are you willing to contribute ?

None

**Comment by cjwinsor** [comment]
Need to make sure that setting the value properly adds the chips. (Also, chip styling is weird)
