### ISSUE TITLE
Multi-select render issue in autocomplete

### ISSUE THREAD

**Issue by anaith1903** [trimble-oss/modus-web-components#2529]
### Prerequisites

- [X] I have [searched](https://github.com/trimble-oss/modus-web-components/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/trimble-oss/modus-web-components/blob/main/CONTRIBUTING.md)

### Describe the issue

Without an assigned value, multiselect chips display correctly. Yet, when a state variable is assigned to value the chips duplicate alongside the assigned string of the same value. 
![image](https://github.com/trimble-oss/modus-web-components/assets/124675224/468556d3-cf2f-4441-a77c-d5ebbd57594f)

### Reduced test cases

https://codesandbox.io/p/sandbox/autocomplete-lrpc5c

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome

### What is the issue regarding ?

@trimble-oss/modus-web-components

### What version of npm package are you using ?

v0.28.0

### Priority

High

### What product/project are you using Modus Components for ?

Sector portal

### What is your team/division name ?

Maps

### Are you willing to contribute ?

None

**Comment by cjwinsor** [comment]
Review example as it shows bug clearly.
