### ISSUE TITLE
Table: API to select cell to place into edit mode

### ISSUE THREAD

**Issue by cjwinsor** [trimble-oss/modus-web-components#2541]
Provide an api on the table that takes a `columnID` and `rowIndex` and is able to switch the cell to or from its "edit mode".  The function can be called something like `editCell(columnID, rowID)`

**Comment by prashanthr6383** [comment]
@cjwinsor Added the Api and the documentation. can be accessed using

`document.querySelector('modus-table').getCellEditable("2","last-name")`
