### ISSUE TITLE
Pagination bug - Cannot read properties of undefined (reading 'setState')

### ISSUE THREAD

**Issue by CSantosTrimble** [trimble-oss/modus-web-components#2560]
### Prerequisites

- [X] I have [searched](https://github.com/trimble-oss/modus-web-components/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/trimble-oss/modus-web-components/blob/main/CONTRIBUTING.md)

### Describe the issue

using modus table in react stuffs is not working the pagination for me after updated to last modus react version (^0.29.0-react18)

When selected other page (2 and foward) back to the page 1 and appears this error in console (manual pagination)

![image](https://github.com/trimble-oss/modus-web-components/assets/85499482/9afd7519-88cb-4459-99e3-57ebb51ac566)

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome

### What is the issue regarding ?

@trimble-oss/modus-web-components

### What version of npm package are you using ?

^0.29.0-react18

### Priority

High

### What product/project are you using Modus Components for ?

Trimble Inspections Portal

### What is your team/division name ?

Inspections team

### Are you willing to contribute ?

None

**Comment by ElishaSamPeterPrabhu** [comment]
This issue cannot be reporduced in the latest version 0.41.1 @CSantosTrimble 
Can you confirm this?

**Comment by jewel-shajan** [comment]
The issue has been tested and was not reproduced in the current version of Storybook.
