### ISSUE TITLE
Modus 0.31.1 changes the default icon color to transparent

### ISSUE THREAD

**Issue by janwiebe-glasbergen** [trimble-oss/modus-web-components#2614]
### Prerequisites

- [X] I have [searched](https://github.com/trimble-oss/modus-web-components/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/trimble-oss/modus-web-components/blob/main/CONTRIBUTING.md)

### Describe the issue

After upgrading to @trimbleinc/modus-bootstrap@0.31.1 I encountered that the icons that are loaded through the modus-button are transparent.

![image](https://github.com/trimble-oss/modus-web-components/assets/116563683/7c2d07c3-8a20-425b-89f6-551403c09390)

It looks like the import of the modus.min.css is now required to set the default colors, which wasn't the case in older versions.

My current workaround is to load the css from `@trimble-oss/modus-web-components/dist/modus-web-components/modus-web-components.css` manually.

### Reduced test cases

**Steps to reproduce:**
- Create a project without loading the modus-web-components.css
- Add: `<modus-button button-style="borderless" color="secondary" icon-only="pencil" />`
- The button is shown, but is fully transparent untill the user hovers over it.

**Example repo:**
The issue is reproducible in https://github.com/janwiebe-glasbergen/modus-button-bug

The main.component uses two modus components, modus-icon and modus-button.

If you run a `npm install` and `ng serve` in this repo you will see that the fill of the modus-button is set to transparent.

It will work fine when you do either one of these workarounds:
- Downgrade to 0.30.0 it is working fine.
- Extend the styles array in angular.json with:  `./node_modules/@trimble-oss/modus-web-components/dist/modus-web-components/modus-web-components.css`

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome

### What is the issue regarding ?

@trimble-oss/modus-web-components

### What version of npm package are you using ?

0.31.1

### Priority

Medium

### What product/project are you using Modus Components for ?

Nova / Construction calculation platform UI

### What is your team/division name ?

ACDC

### Are you willing to contribute ?

No

**Comment by coliff** [comment]
Thanks for reporting this! We found a bug and will make a release with a fix later today.

(On: `https://github.com/trimble-oss/modus-web-components/blob/main/stencil-workspace/src/components/modus-button/modus-button.vars.scss#L50` - the `#0000` should be `#000`.
