### ISSUE TITLE
Button Group: By default the first button should be selected 

### ISSUE THREAD

**Issue by anwishaZ** [trimble-oss/modus-web-components#2642]
### Prerequisites

- [x] I have [searched](https://github.com/trimble-oss/modus-web-components/issues?q=is%3Aissue) for duplicate or closed feature requests
- [x] I have read the [Modus style guidelines](https://modus.trimble.com/components/web/introduction/)

### Proposal

This is how the first button should be selected by default on starting the application and then later the select can be changed onclick of other buttons.
![buttongroup](https://github.com/trimble-oss/modus-web-components/assets/164128344/0f41c7ae-8abb-41d2-b300-0feb9ee6a21e)

### Motivation and context

When the user opens the application, no button is selected by default. As a result, the user has to manually select a button each time they enter. To enhance the UI, it is better to have a default button selected. This way, the user can still choose to select other buttons if needed, but they won't have to make an initial selection every time they open the application.

### What is the issue regarding ?

Modus Web Components Website (Storybook)

### Priority

Medium

### What product/project are you using Modus Components for ?

TRIMBLE FORESTRY 

### What is your team/division name ?

Central Product development

### Are you willing to contribute ?

No

### Are you using Modus Web Components in production ?

Yes

**Comment by coliff** [comment]
Hi @anwishaZ- the style guide needs to be updated. Button groups aren't **just** for toggle groups, they can also be used for a group of related buttons but not necessarily toggleable.

I understand that you'd like an option pre-selected for the 'single-selection' option (https://modus-web-components.trimble.com/?path=/docs/components-button-group--default#single-selection). I would suggest that this could be an option (opt-in), but not on by default. maybe something like:

```html
<modus-button-group selection-type="single">
  <modus-button selected>Button 1</modus-button>
  <modus-button>Button 2</modus-button>
  <modus-button>Button 3</modus-button>
</modus-button-group>
```
