### ISSUE TITLE
Modus Text Input ignores 'c' when typed

### ISSUE THREAD

**Issue by natanbcpc** [trimble-oss/modus-web-components#2646]
### Prerequisites

- [X] I have [searched](https://github.com/trimble-oss/modus-web-components/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/trimble-oss/modus-web-components/blob/main/CONTRIBUTING.md)

### Describe the issue

When entering text into ModusTextInput, the letter 'c' is ignored if not typed within a small timeframe from the last letter or in uppercase. Copying and pasting 'c' seems to work fine though.

### What operating system(s) are you seeing the problem on?

Linux

### What browser(s) are you seeing the problem on?

Chrome

### What is the issue regarding ?

@trimble-oss/modus-web-components

### What version of npm package are you using ?

v0.29.0-react18 (also present in v0.32.0-react18)

### Priority

High

### What product/project are you using Modus Components for ?

CX Support

### What is your team/division name ?

Skyris

### Are you willing to contribute ?

Yes

### Are you using Modus Web Components in production ?

https://cxsupport-qa.connectedfleet.io/#/integrations/types/create (not production)

**Comment by coliff** [comment]
Did you observe this issue on Storybook or on your own site? Reason i ask is that I know that Storybook has many of their own built-in keyboard shortcuts which make testing some Modus Web Components on storybook a little tricky.

Can you reproduce the issue on this simple HTML test page I created?
https://coliff.github.io/modus-web-components-example/#text-inputs

I wasn't able to reproduce it. If you can please can you record a video or let us know which words/characters you entered?

**Comment by cjwinsor** [comment]
@natanbcpc is it possible to provide more context or sample code that reproduces the issue.  Typing c in the storybook is seemingly working 100% of the time during my testing.  A codepen or stackblitz would be great for reproducing.

**Comment by natanbcpc** [comment]
Tried starting a new project to test it and not getting this bug, closing this for now. Thanks for looking into it!

**Comment by natanbcpc** [comment]
Found out what was causing the issue: CX Support uses react-hotkeys-hook, which automatically ignores key events from inside inputs through this line: https://github.com/JohannesKlauss/react-hotkeys-hook/blob/main/src/validators.ts#L27

However, for the modus text input, the tagName is not `input`, but `modus-text-input`. Adding the prop `contentEditable` to the text input fixed the issue.
