### ISSUE TITLE
Borderless table should have bottom line

### ISSUE THREAD

**Issue by enowak1031** [trimble-oss/modus-web-components#2675]
The implementation of borderless tables in web components is incorrect. The borderless table rows should always have a bottom line (see Figma).

**Comment by cjwinsor** [comment]
We will need to add a new property to `displayOptions` that controls the vertical borders.  Initial thought is to add a prop like `cellVerticalBorderless` but it seems a little verbose so I am open to suggestions.  We will keep borderless and `cellBorderless` alone. 

If the user selects `cellBorderless: true, cellVerticalBorderless: false`, then the cell has no borders as `cellBorderless` has priority.

**Comment by ElishaSamPeterPrabhu** [comment]
> We will need to add a new property to `displayOptions` that controls the vertical borders. Initial thought is to add a prop like `cellVerticalBorderless` but it seems a little verbose so I am open to suggestions. We will keep borderless and `cellBorderless` alone.
> 
> If the user selects `cellBorderless: true, cellVerticalBorderless: false`, then the cell has no borders as `cellBorderless` has priority.

Added a new prop `cellVerticalBorderless` and set it to true, this is how the table looks with no vertical borders and borderless is set to true
![image](https://github.com/user-attachments/assets/b92f1168-e7e3-4232-8feb-11e3c4591072)
and when borderless is set to false
![image](https://github.com/user-attachments/assets/096ad4e1-bfb9-4ec9-b759-d4695e6985f1)
