### ISSUE TITLE
Date Picker: Enable display of valid & invalid dates

### ISSUE THREAD

**Issue by raymondboswel** [trimble-oss/modus-web-components#2679]
### Prerequisites

- [X] I have [searched](https://github.com/trimble-oss/modus-web-components/issues?q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [Modus style guidelines](https://modus.trimble.com/components/web/introduction/)

### Proposal

Add an optional input property that accepts a list of dates which will be displayed in the date picker as clickable; dates not in the passed in list are displayed as disabled. An alternate solution could be to expose an isDateEnabled function, which the user can then pass in to handle their specific logic. This is how Ionic handles the same type of functionality: https://ionicframework.com/docs/api/datetime#advanced-date-constraints

### Motivation and context

We have a use case where the user has to select a date window to display machine data across. Machines however don't have data available every day; it would thus be useful to provide some visual affordance to guide the user towards picking days that actually do have data available, instead of picking dates and seeing an error message pop up.

### What is the issue regarding ?

@trimble-oss/modus-web-components

### Priority

Medium

### What product/project are you using Modus Components for ?

WorksOS / Machine Playback

### What is your team/division name ?

CCFS/Weka

### Are you willing to contribute ?

Yes

**Comment by prashanth-offcl** [comment]
@prashanth-offcl to check this issue and update

**Comment by raymondboswel** [comment]
Hi @prashanth-offcl, sorry, I missed this message. I should be able to make some time for this in a few weeks time :+1:

**Comment by raymondboswel** [comment]
I've started to look into this. I have some basic functionality working, where the date picker exposes a property isDateEnabled, which takes a function. The function is called for every date being rendered and returns true or false. In this screenshot, only weekend dates are valid as an example. 
![image](https://github.com/user-attachments/assets/bbaae30f-d036-4bf1-b98b-a9926f65c699)

This will cover some cases, but falls short in others. I can imagine that it might be expensive for a service to return all valid dates across all time upfront and instead make requests as the calendar is being operated. The simplest interface I can imagine is adding an additional property isDateEnabledLoading, which sets a boolean that displays a loading bar at the top, as show in the clip below:

https://github.com/user-attachments/assets/6755d4d7-7310-4ab8-85b8-9a6059b4f74e

This would also require another event to be emitted from the calendar, something like calendarNavigated (emitting the date), which the developer can then use to fetch data for that month (they can also prefetch next & previous months to avoid showing the loader when possible). Let me know what you think @prashanth-offcl .

**Comment by jewel-shajan** [comment]
This issue has been resolved in the PR #2934 . Hence closing the issue
