### ISSUE TITLE
Autocomplete: Option can be selected multiple times

### ISSUE THREAD

**Issue by leosole-trimble** [trimble-oss/modus-web-components#2696]
### Prerequisites

- [X] I have [searched](https://github.com/trimble-oss/modus-web-components/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/trimble-oss/modus-web-components/blob/main/CONTRIBUTING.md)

### Describe the issue

When using autocomplete with custom options, each time the user clicks on an option, a chip is added, even if the option was already selected
![image](https://github.com/user-attachments/assets/39c2b622-1d32-46a4-bf05-69ea0ca74b29)

### What is the issue regarding ?

@trimble-oss/modus-web-components

### Priority

High

### What product/project are you using Modus Components for ?

Trimble Inspections

### What is your team/division name ?

Camaleão/Transportation

### Are you willing to contribute ?

Maybe

**Comment by prashanth-offcl** [comment]
Able to reproduce this issue in the storybook and this should be fixed.
