### ISSUE TITLE
Pagination: Numbers for the nonactive pages are not visible in dark mode

### ISSUE THREAD

**Issue by sorina-ocheana** [trimble-oss/modus-web-components#2702]
### Prerequisites

- [X] I have [searched](https://github.com/trimble-oss/modus-web-components/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/trimble-oss/modus-web-components/blob/main/CONTRIBUTING.md)

### Describe the issue

In the dark mode the number coloring for the nonactive page is identical to the background and the numbers are not visible.
The current version of the pagination component:
![chrome_w0pztHNj7S](https://github.com/user-attachments/assets/3f369ea1-983d-46bd-a7b6-45337cb48dd7)
The Modus figma design for the pagination component on dark mode:
![Egu1vN1Zjn](https://github.com/user-attachments/assets/849dd09a-ac69-459c-aa89-504305665d5f)

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome

### What is the issue regarding ?

@trimble-oss/modus-web-components

### What version of npm package are you using ?

v0.34.0

### Priority

High

### What product/project are you using Modus Components for ?

ADMS

### What is your team/division name ?

Team Red / Trimble Utilities

### Are you willing to contribute ?

Yes

### Are you using Modus Web Components in production ?

Yes

**Comment by coliff** [comment]
Fixed with: https://github.com/trimble-oss/modus-web-components/pull/2703
