### ISSUE TITLE
ButtonGroup: Unable to reset the selection using the selected property

### ISSUE THREAD

**Issue by anwishaZ** [trimble-oss/modus-web-components#2718]
### Prerequisites

- [X] I have [searched](https://github.com/trimble-oss/modus-web-components/issues?q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [Modus style guidelines](https://modus.trimble.com/components/web/introduction/)

### Proposal

The user is unable to deselect the button group in a modus button group (single select) because, once the button is selected, an active property is applied by default and is not removed, making it impossible for the user to remove the selection.I propose that it would be ideal if we could eliminate the selected property along with the active property..

### Motivation and context

In our use case we have a reset button in the form and on clicking that ,the selected button from button group should go deselected .

### What is the issue regarding ?

@trimble-oss/modus-web-components

### Priority

Medium

### What product/project are you using Modus Components for ?

TRIMBLE FORESTRY 

### What is your team/division name ?

Central Product development

### Are you willing to contribute ?

None

### Are you using Modus Web Components in production ?

Yes

**Comment by prashanth-offcl** [comment]
@anwishaZ I see the selected property only works during the initial rendering and updates to the `selected` property do not reflect in the UI after the component has been rendered. Is there a specific reason as to why you would want to remove the selected property and implement an alternate approach to manage the selected state?
