### ISSUE TITLE
Autocomplete: Duplicate error message displayed

### ISSUE THREAD

**Issue by coliff** [trimble-oss/modus-web-components#2720]
Example:
https://modus-web-components.trimble.com/?path=/story/user-inputs-autocomplete--default&args=errorText:Vehicle+Name+Required

![image](https://github.com/user-attachments/assets/7fa17866-52f3-45e7-95d9-870b1911f33b)

**Comment by coliff** [comment]
Originally reported via Google Chat channel:
![image](https://github.com/user-attachments/assets/70b6138e-28e3-45ee-8dad-b411d59a8794)

**Comment by prashanth-offcl** [comment]
We can remove the error message displayed inside the modus-text-input component
