### ISSUE TITLE
Alert: Warning alert icon is incorrect color (light mode)

### ISSUE THREAD

**Issue by coliff** [trimble-oss/modus-web-components#2726]
With the latest changes the warning alert is not the same color as the border `#e49325` but it should be.

![image](https://github.com/user-attachments/assets/4e986584-1500-4fde-8fed-1aef31adff06)

Style guide:
![image](https://github.com/user-attachments/assets/c11632be-0b2c-47bf-9a74-fabf7314550e)

**Comment by ElishaSamPeterPrabhu** [comment]
> With the latest changes the warning alert is not the same color as the border `#e49325` but it should be.
> 
> ![image](https://private-user-images.githubusercontent.com/1212885/351773266-4e986584-1500-4fde-8fed-1aef31adff06.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0MDM5NjAsIm5iZiI6MTcyMjQwMzY2MCwicGF0aCI6Ii8xMjEyODg1LzM1MTc3MzI2Ni00ZTk4NjU4NC0xNTAwLTRmZGUtOGZlZC0xYWVmMzFhZGZmMDYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDczMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MzFUMDUyNzQwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9M2ViMDRmM2IxNDRmZTNjZjI1M2YxZDc2Yjg0NGUyYjY3ZTQ0YWVkYWI1MGE3YTBkZTUwZDA5ZjU5ODE5NDNjZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.hrGrEHtQa0BRgjz6g70u_OtRA7r7vtROF3KSQUe_lMU)
> 
> Style guide: 
![image](https://private-user-images.githubusercontent.com/1212885/351772881-c11632be-0b2c-47bf-9a74-fabf7314550e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0MDM5NjAsIm5iZiI6MTcyMjQwMzY2MCwicGF0aCI6Ii8xMjEyODg1LzM1MTc3Mjg4MS1jMTE2MzJiZS0wYjJjLTQ3YmYtOWE3NC1mYWJmNzMxNDU1MGUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDczMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MzFUMDUyNzQwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODFmZmQwYmFhYzA3NzM5ODUzYTQ5OWI3YmQ1M2YzZmIxMWY5ZGZmZmNkMDNhNjI3OGM1YzQyODEyZGQwODI4MyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.pO9FwHRC1ip-4odwy17PpoHUn_FaUIJdAujPPoLJqgg)

Are you talking about the alert icon color difference with respect to border?

`#252a2e`

![Image](https://github.com/user-attachments/assets/76d78af1-9844-4ed9-82b7-702a89bddf58)

`#e49325`

![Image](https://github.com/user-attachments/assets/0024922a-8a6e-4506-af78-6c48cfddff32)

**Comment by cjwinsor** [comment]
Also not the icon is wrong in the MWC for Error and Warning, they are reversed with how they should be.
