### ISSUE TITLE
Table: extra blank space shown when sort is active

### ISSUE THREAD

**Issue by leosole-trimble** [trimble-oss/modus-web-components#2752]
### Prerequisites

- [X] I have [searched](https://github.com/trimble-oss/modus-web-components/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/trimble-oss/modus-web-components/blob/main/CONTRIBUTING.md)

### Describe the issue

When the sort is active and there are no row actions, the table adds a blank space at the end that is not needed, along with a scrollbar, as shown in the images
With sort:
![image](https://github.com/user-attachments/assets/90d2e1d6-bae3-4fc7-a990-f8911bbbc7ee)

Without sort:
![image](https://github.com/user-attachments/assets/4f603d3c-11c1-4746-9ffb-edbb06630be1)

### What is the issue regarding ?

@trimble-oss/modus-web-components

### Priority

High

### What product/project are you using Modus Components for ?

Trimble Inspections

### What is your team/division name ?

Camaleão/Transportation

### Are you willing to contribute ?

No

**Comment by prashanth-offcl** [comment]
@leosole-trimble I'm trying to reproduce this behavior, can you provide me an example codepen or share your table configuration?

**Comment by leosole-trimble** [comment]
@prashanth-offcl sure. I forgot to add that the column resize option needs to be enabled.
[storybook link](https://modus-web-components.trimble.com/?path=/story/components-table--row-actions&args=hover:true;sort:true;columnResize:true;columns[0].header:Email;columns[0].accessorKey:email;columns[0].id:email;columns[0].dataType:link;columns[0].size:!undefined;columns[0].minSize:!undefined;columns[0].footer:!undefined;columns[0].sortingFn:sortForHyperlink;columns[1].header:Status;columns[1].accessorKey:status;columns[1].id:status;columns[1].size:!undefined;columns[1].minSize:!undefined;columns[2].header:Profile+Progress;columns[2].accessorKey:progress;columns[2].id:progress;columns[2].size:!undefined;columns[2].minSize:!undefined;columns[3].header:Created+At;columns[3].accessorKey:createdAt;columns[3].id:createdAt;columns[3].dataType:date;columns[3].maxSize:!undefined;columns[3].showTotal:!undefined;columns[3].minSize:!undefined;columns[4]:!undefined;columns[5]:!undefined;columns[6]:!undefined;columns[7]:!undefined;rowActions[0]:!undefined;rowActions[1]:!undefined;rowActions[2]:!undefined;rowActions[3]:!undefined;rowActions[4]:!undefined)
