### ISSUE TITLE
Progress bar: Indeterminate state

### ISSUE THREAD

**Issue by marius-kazlauskas-trimble** [trimble-oss/modus-web-components#2785]
### Prerequisites

- [X] I have [searched](https://github.com/trimble-oss/modus-web-components/issues?q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [Modus style guidelines](https://modus.trimble.com/components/web/introduction/)

### Proposal

It will be nice have Indeterminate progress bar option in React like angular material has:
https://material.angular.io/components/progress-bar/overview

### What is the issue regarding ?

@trimble-oss/modus-web-components

### Priority

Medium

### What product/project are you using Modus Components for ?

Numark

### What is your team/division name ?

Numark

### Are you willing to contribute ?

None

**Comment by prashanth-offcl** [comment]
@jtran267 Can you please provide UX inputs on how it should look?

**Comment by prashanth-offcl** [comment]
- Introduce new optional prop called `mode` that accepts "determinate" | "indeterminate" as value. 
- The default value should be "determinate" 
- Remove aria-valuenow property if the mode is "indeterminate"
