### ISSUE TITLE
Table: Retain cell error state even if the focus is changed

### ISSUE THREAD

**Issue by prashanthr6383** [trimble-oss/modus-web-components#2798]
In current implementation, the cell error styling and message is only persisted when the cell is in edit mode. If the user clicks away or edits a different cell then the previous cell error border and message is removed. Ideally the error state of the cell should be retained until the user corrects the cell value. 

**Acceptance Criteria**
- No changes to the existing prop or events
- Table cell in error state should be identified using red border and a error message if the input is focused.
- Table cell in error state should only retain the red border if the focus is changed.

**Comment by prashanth-offcl** [comment]
@prashanthr6383 Updated the description and added acceptance criteria as discussed.
