### ISSUE TITLE
Datepicker: Unable to clear out modus date-picker internal error state 'Invalid date range'

### ISSUE THREAD

**Issue by venkyn13** [trimble-oss/modus-web-components#2806]
### Prerequisites

- [X] I have [searched](https://github.com/trimble-oss/modus-web-components/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/trimble-oss/modus-web-components/blob/main/CONTRIBUTING.md)

### Describe the issue

In our 'Field Data' application, inside filter panel, we are using modus date-picker component. This component maintains an internal error state 'Invalid date range', when an user selects invalid 'from and to date range'. While we have tried to clear out this date range on our own, the date range got cleared out but the message 'Invalid date range' is still appearing
![Modus bug - date picker](https://github.com/user-attachments/assets/2be3ed0b-6ceb-4929-802a-1dcd8df834b7)

### What is the issue regarding ?

@trimble-oss/modus-web-components

### Priority

High

### What product/project are you using Modus Components for ?

Field Data

### What is your team/division name ?

Geospatial - CPD

### Are you willing to contribute ?

None

**Comment by prashanth-offcl** [comment]
See if we can re-validate by listening to the valueChange event of the date inputs.

**Comment by venkyn13** [comment]
This issue has been resolved after adding errorText field to modus-date-picker component.
