### ISSUE TITLE
Toast: error on dismiss [React wrapper]

### ISSUE THREAD

**Issue by leosole-trimble** [trimble-oss/modus-web-components#2835]
### Prerequisites

- [X] I have [searched](https://github.com/trimble-oss/modus-web-components/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/trimble-oss/modus-web-components/blob/main/CONTRIBUTING.md)

### Describe the issue

When dismissing the toast (either by clicking the x button or letting the timer expire) I'm getting the following error:
`NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.`
I'm using the react wrapper. This doesn't seems to be happening in storybook.

This is how I'm using the toast:
```
{toast && (
        <ModusToast type={toast.type} showIcon onDismissClick={() => setToast(null)}>
          {toast.message}
        </ModusToast>
)}
```

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome

### What is the issue regarding ?

@trimble-oss/modus-web-components

### What version of npm package are you using ?

0.37.0-react18

### Priority

High

### What product/project are you using Modus Components for ?

Trimble DVIR

### What is your team/division name ?

Camaleão/Transportation

### Are you willing to contribute ?

No

**Comment by prashanth-offcl** [comment]
For the current implementation to work, the consumer will have to create new toast element for every new message which is not ideal so we will introduce a new prop `retainElement` that will control the removal of element when the toast message is dismissed. The default value for the prop will be set to `false`.
