### ISSUE TITLE
Date Picker: Calender doesn't display when used inside another web component

### ISSUE THREAD

**Issue by raymondboswel** [trimble-oss/modus-web-components#2837]
### Prerequisites

- [X] I have [searched](https://github.com/trimble-oss/modus-web-components/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/trimble-oss/modus-web-components/blob/main/CONTRIBUTING.md)

### Describe the issue

The click outside listener does not deal with the shadow DOM boundary correctly, resulting in a click on the calender icon also triggering the click outside listener, effectively closing the calender before it can open. 

### Reduced test cases

This repo provides a reproduction: https://github.com/raymondboswel/modus-datepicker-reproduction

### What operating system(s) are you seeing the problem on?

Linux

### What browser(s) are you seeing the problem on?

Chrome

### What is the issue regarding ?

@trimble-oss/modus-web-components

### What version of npm package are you using ?

0.37.0

### Priority

Medium

### What product/project are you using Modus Components for ?

WorksManager

### What is your team/division name ?

Field Systems

### Are you willing to contribute ?

Yes

### Are you using Modus Web Components in production ?

Yes

**Comment by prashanth-offcl** [comment]
Fixed in #2838
