### ISSUE TITLE
Modal Pop up : Need an event for the close button on the right corner of the pop up

### ISSUE THREAD

**Issue by umagesh1** [trimble-oss/modus-web-components#2840]
### Prerequisites

- [X] I have [searched](https://github.com/trimble-oss/modus-web-components/issues?q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [Modus style guidelines](https://modus.trimble.com/components/web/introduction/)

### Proposal

We would need an event that will be triggered when the Close button on the modap pop up is clicked, like primary and secondary button clicks. This would help the application maintain the state of the pop up.

### Motivation and context

This would help the application maintain the state of the pop-up

### What is the issue regarding ?

@trimble-oss/modus-web-components

### Priority

High

### What product/project are you using Modus Components for ?

Inventory Web app

### What is your team/division name ?

CPD

### Are you willing to contribute ?

None

**Comment by prashanth-offcl** [comment]
Capturing the integration logic on the consumer side after the initial discussion
- Toggle modal visibility based on a boolean state variable
- Call modal close / open methods when the state variable changes (through Observable)
- Update state variable to false when `closed` or `secondaryButtonClick` events are emitted

The logic above creates a infinite loop as below: User clicks close button > closed event is emitted > consumer updates state variable to false > consumer calls the modal close method > modus component emits the closed event again. 

I've asked the team to have prevention logic to avoid this loop. From our side, for both open and close methods we will if the modal is already is open or closed state before performing the action and emitting the event.
