### ISSUE TITLE
Accordion: Add supporting label and fix left icon spacing

### ISSUE THREAD

**Issue by Parrtist** [trimble-oss/modus-web-components#2850]
### Prerequisites

- [X] I have [searched](https://github.com/trimble-oss/modus-web-components/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/trimble-oss/modus-web-components/blob/main/CONTRIBUTING.md)

### Describe the issue

In Figma, the accordion component does not match what is documented on the Modus and Web Component websites. 

Figma: <img width="684" alt="image" src="https://github.com/user-attachments/assets/3647b056-136b-43c3-9d6a-af68d63b4ca2">

Modus: 
<img width="635" alt="image" src="https://github.com/user-attachments/assets/ee06f298-1470-4115-954d-476e8324768a">

Web Component: 
<img width="714" alt="image" src="https://github.com/user-attachments/assets/90023561-57e5-4823-acad-2554c559c525">

### What operating system(s) are you seeing the problem on?

macOS

### What is the issue regarding ?

@trimble-oss/modus-web-components

### Priority

High

### What product/project are you using Modus Components for ?

Trimble Unity Maintain

### What is your team/division name ?

O&PS

### Are you willing to contribute ?

Maybe

### Are you using Modus Web Components in production ?

Not yet

**Comment by prashanth-offcl** [comment]
Tasks:
- [ ] Fix left icon and label incorrect gap
- [ ] Add supporting label
