### ISSUE TITLE
Blue Navbar Logo Broken

### ISSUE THREAD

**Issue by kuhnboy** [trimble-oss/modus-web-components#2876]
### Prerequisites

- [X] I have [searched](https://github.com/trimble-oss/modus-web-components/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/trimble-oss/modus-web-components/blob/main/CONTRIBUTING.md)

### Describe the issue

`https://modus-bootstrap.trimble.com/img/trimble-logo-rev.svg` has been removed and therefore existing usage of this is broken. For example in the storybook (https://modus-web-components.trimble.com/?path=/docs/components-navbar--default):

![image](https://github.com/user-attachments/assets/cbbba941-eea7-4b75-95de-7a5ab4e7cc4e)

Hopefully this file is restored so anyone using this isn't broken.

### What is the issue regarding ?

@trimble-oss/modus-web-components, Modus Web Components Website (Storybook)

### What version of npm package are you using ?

N/A

### Priority

Medium

### What product/project are you using Modus Components for ?

AECO

### What is your team/division name ?

O&PS

### Are you willing to contribute ?

None

**Comment by coliff** [comment]
Fixed! https://modus-bootstrap.trimble.com/img/trimble-logo-rev.svg is restored.
