### ISSUE TITLE
Tables: Click+Shift select rows

### ISSUE THREAD

**Issue by enowak1031** [trimble-oss/modus-web-components#2883]
https://trimble-arch.aha.io/ideas/ideas/MOD-I-114

Allow Shift+Click and Shift + Up/Down arrow to select multiple rows in a table. The checkboxes are checked to indicate which rows have been selected.

Similar to the behavior in the Content Tree component:
The prop multi-selection lets multiple items to be selected using Shift + Up/Down arrow and Ctrl + click.

![Image](https://github.com/user-attachments/assets/7bd367b1-5aef-4d7c-82c5-4b30b6df7d0d)

**Comment by prashanth-offcl** [comment]
The scope of the ticket is to implement the shift + click and shift + up/down arrow to select a range of items in the table component with checkbox selection enabled.

**Comment by enowak1031** [comment]
- BUG: The space and enter keys should both select the checkbox/row. Currently space selects and unselects on one press. 
- Continuous selection with shift+up/down and discontinuous selection with control/command+shift+up/down should work.

**Comment by enowak1031** [comment]
User can select multiple discontinuous rows when pressing space/return (selects checkbox in the row = selects row). User can shift and use arrows for continuous selection of rows. There is no need for the user to have to click command for discontinuous selection.

**Comment by jewel-shajan** [comment]
@enowak1031 @coliff ,The document mentions that by default, the Modus Table allows selecting only one row at a time, but this can be modified to allow multiple selections using the `rowSelectionOptions` option. However, the current behavior differs when `rowSelectionOptions` is not used, as the table behaves differently. Should we update the document to reflect this?

**Comment by enowak1031** [comment]
Yes, we should update the documentation to say that both single and multiple selection of rows is allowed.
