### ISSUE TITLE
Font for Multilingual Support

### ISSUE THREAD

**Issue by enowak1031** [trimble-oss/modus-web-components#2888]
I'm improving Topics's PDF export in Trimble Connect and for that I would need one .ttf font file that supports all 17 languages that Trimble Connect is supporting. Would you know if we have fonts that would fit this usage? Currently we are using Open Sans font, which works on most languages, but not all, for example Korean is not rendered. I have found one font that would fit (Arial Unicode), but its license needs to be sorted and I wanted to check if we have suitable fonts already licensed.

Best regards,
  Marko Myllymaa

Modus recommends Noto but multiple families need to be installed to support all the languages. Marko needs one font.

**Comment by enowak1031** [comment]
@prashanth-offcl Let's create documentation based on Marko's findings about the option to merge multiple Noto families suites.

**Comment by prashanth-offcl** [comment]
Marko used [FontForge](https://fontforge.org/en-US/) to combine several font files into one. Here's what he did:

**Base Font**: He started with Noto Sans Regular as the base.

**Merged Fonts**: He then merged the following regular versions:

- Noto Sans KR
- Noto Sans TC
- Noto Sans SC
