### ISSUE TITLE
Alerts are not correct color

### ISSUE THREAD

**Issue by coliff** [trimble-oss/modus-web-components#2913]
### Prerequisites

- [X] I have [searched](https://github.com/trimble-oss/modus-web-components/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/trimble-oss/modus-web-components/blob/main/CONTRIBUTING.md)

### Describe the issue

This was my fault!
https://coliff.github.io/modus-web-components-example/#alerts

![image](https://github.com/user-attachments/assets/c3369b4d-e7e2-4c88-aabc-a06865a11f1f)

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Microsoft Edge

### What is the issue regarding ?

@trimble-oss/modus-web-components

### Priority

Medium

### What product/project are you using Modus Components for ?

Modus

### What is your team/division name ?

Modus

### Are you willing to contribute ?

Yes

**Comment by enowak1031** [comment]
@coliff Can you give it an estimate? And can you fix it in this sprint?

**Comment by coliff** [comment]
Yes, added to the sprint and gave it a '1' point.
