### ISSUE TITLE
Modify the Web Component to Accept Callback Props (Events)

### ISSUE THREAD

**Issue by marius-kazlauskas-trimble** [trimble-oss/modus-web-components#2984]
### Prerequisites

- [X] I have [searched](https://github.com/trimble-oss/modus-web-components/issues?q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [Modus style guidelines](https://modus.trimble.com/components/web/introduction/)

### Proposal

Is it possible to add callback props (events) like?
`@Prop() onItemSelectionChange: (event: TreeItemSelectionChange) => void;`

For example here (and in other web components other events too):
https://github.com/trimble-oss/modus-web-components/blob/main/stencil-workspace/src/components/modus-content-tree/modus-tree-view-item/modus-tree-view-item.tsx

### Motivation and context

This will be helpful because then we can use events directly like: 
`<modus-tree-view-item itemSelectionChange={() => {...`

And without this we have to use events in that way, which looks more like workaround:

```
  useEffect(() => {
    defineCustomElements();

    const treeView = treeViewRef.current;
    treeView?.addEventListener('itemSelectionChange', handleSelectionChange);

    return () =>
      treeView?.removeEventListener(
        'itemSelectionChange',
        handleSelectionChange
      );
  }, []);
```

### What is the issue regarding ?

@trimble-oss/modus-web-components

### Priority

Medium

### What product/project are you using Modus Components for ?

Numark

### What is your team/division name ?

Numark

### Are you willing to contribute ?

None

**Comment by marius-kazlauskas-trimble** [comment]
It seems that there is other solution how to use these events without addEventListener. We can use `on:` like
`on:itemSelectionChange={(e: CustomEvent) => {
                console.log('Item changed', e);
              }}`

**Comment by raymondboswel** [comment]
Just for extra context, this was in a SolidJS codebase. Solid by default assumes lowercase event names as that is how all standard DOM events are named, so 'click' is handled by onClick. To handle other casings in Solid you have to use 'on:', e.g 'buttonClick' is handled by on:buttonClick.
