### ISSUE TITLE
Dropdown formatting: fix corner radii

### ISSUE THREAD

**Issue by enowak1031** [trimble-oss/modus-web-components#3000]
In the dropdown component, the list container and highlight for selected items have rounded corners. They should be square. Related to side navigation issue #2927

**Comment by ElishaSamPeterPrabhu** [comment]
<img width="267" alt="Image" src="https://github.com/user-attachments/assets/76e1d0ba-322e-4330-bd12-f1e22b9e5c6f" />
Something like this is expected? @enowak1031 @apaddock 
or 
![Image](https://github.com/user-attachments/assets/e743121c-e333-45dc-bb56-694c2d0a7123)

**Comment by enowak1031** [comment]
Ideally we would like to change the corner radius to 0 pixels for all dropdowns with an option to customize it or increase it to 2 or 4 pixels.
