### ISSUE TITLE
Table - Allow passing language as a parameter

### ISSUE THREAD

**Issue by janwiebe-glasbergen** [trimble-oss/modus-web-components#3045]
### Prerequisites

- [X] I have [searched](https://github.com/trimble-oss/modus-web-components/issues?q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [Modus style guidelines](https://modus.trimble.com/components/web/introduction/)

### Proposal

Add a `language` property to the modus-table that overrides the `navigator.language`.

### Motivation and context

In our current applications we give the user the possibility to change the language using a query parameter. Currently we have to use a ugly hack to redefine the `navigator.language` property.

In my opinion `navigator.language` is okay as a fallback, but shouldn't be the only way to set the language of the components. As some applications require to switch the language on the fly.

### What is the issue regarding ?

@trimble-oss/modus-web-components

### Priority

Low

### What product/project are you using Modus Components for ?

Nova / Construction calculation platform UI

### What is your team/division name ?

ACDC

### Are you willing to contribute ?

Maybe

**Comment by prashanthr6383** [comment]
Hi @janwiebe-glasbergen The team decided that enabling a prop for the table component is not ideal, as translation support is being implemented across all components, and adding a similar prop to each would not be scalable. Instead, improvements have been made to the translation system. It now prioritizes the document's lang attribute, which can be dynamically updated based on select component actions.
