### ISSUE TITLE
SPIKE: Side Nav Dropdown Options

### ISSUE THREAD

**Issue by enowak1031** [trimble-oss/modus-web-components#3057]
Explore options for implementing doropdown in the side navigation. Related to #2927

**Comment by ElishaSamPeterPrabhu** [comment]
Can this be the approach?

https://github.com/user-attachments/assets/46378df5-dacb-424c-8557-2c55d4565b59

**Comment by ElishaSamPeterPrabhu** [comment]
Update the functionality based on what we discussed @enowak1031 @mitch-trimble @prashanthr6383 
@apaddock This video demonstrates the updated behavior compared to the previous one. Could you review this?
https://github.com/user-attachments/assets/f8c2d1cb-19f2-4d28-b9fd-f4915ff4f066

**Comment by ElishaSamPeterPrabhu** [comment]
> Update the functionality based on what we discussed [@enowak1031](https://github.com/enowak1031) [@mitch-trimble](https://github.com/mitch-trimble) [@prashanthr6383](https://github.com/prashanthr6383) [@apaddock](https://github.com/apaddock) This video demonstrates the updated behavior compared to the previous one. Could you review this? https://github.com/user-attachments/assets/f8c2d1cb-19f2-4d28-b9fd-f4915ff4f066

This approach is expected.
