### ISSUE TITLE
Create a Changelog

### ISSUE THREAD

**Issue by gabriel-piltzer-trimble** [trimble-oss/modus-web-components#31]
The file should live at the root of the project and be called "CHANGELOG.md"

Use [Keep a Changelog](https://keepachangelog.com/en/1.0.0/) as a guide.

Every release should highlight new features, bug fixes, and breaking changes.

**Comment by coliff** [comment]
Manually maintaining a CHANGELOG.md could be extra work, but some users may expect to see a CHANGELOG in the project root.

One idea could be to have a CHANGELOG.md with a link to check release notes at: https://github.com/trimble-oss/modus-web-components/releases
