### ISSUE TITLE
README badge links

### ISSUE THREAD

**Issue by coliff** [trimble-oss/modus-web-components#362]
- Contributors link could go to https://github.com/trimble-oss/modus-web-components/graphs/contributors

- version number link could go to npm https://www.npmjs.com/package/@trimble-oss/modus-web-components

**Comment by ryan-henness-trimble** [comment]
Good calls :)

**Comment by coliff** [comment]
I think we need to mention on the README how a developer can install it from npm.

`npm i @trimble-oss/modus-web-components  --save`

**Comment by ryan-henness-trimble** [comment]
oh yea, I'm going to get started un updates for the README and the Storybook
