### ISSUE TITLE
tables in mdx files

### ISSUE THREAD

**Issue by coliff** [trimble-oss/modus-web-components#370]
heya @ryan-henness-trimble 

Right now the tables in the `.mdx` files are HTML tables. I suggest we use markdown tables instead as they'll be easier to view at a glance in the source code. When compiled in Storybook they will look identical. Example of what I mean exactly:

![image](https://user-images.githubusercontent.com/1212885/155316370-008cee2e-f980-4233-ae40-20dd44edd405.png)

![image](https://user-images.githubusercontent.com/1212885/155318104-4140e8a8-3637-40f8-b261-cdd80704ceda.png)

If you agree, I'd be happy to make a PR with the tables converted. It doesn't take long to do in VS Code (you can copy and paste from the web page and then do toggle markdown table to format it with this useful extension:
https://marketplace.visualstudio.com/items?itemName=mdickin.markdown-shortcuts)
Prettier takes care of making all the columns equal width.

**Comment by ryan-henness-trimble** [comment]
Agreed! I think we might be able to steal these markdown tables from the docs that Stencil auto-generates so that we don't have to write them by hand

**Comment by ryan-henness-trimble** [comment]
Here's an example of one of those auto-generated files https://github.com/trimble-oss/modus-web-components/blob/main/src/components/modus-button/readme.md

**Comment by msankaran0712** [comment]
@coliff  Do we need to keep this one? We have been modifying it all the components in the PRs

**Comment by coliff** [comment]
I think it's fine to close now...
