### ISSUE TITLE
Content Tree in Web Components - Keyboard Interaction and accessibility

### ISSUE THREAD

**Issue by enowak1031** [trimble-oss/modus-web-components#407]
As a user of the design system, I want to have the content tree component available in Web Components for easy implementation.

REF: [modus.trimble.com/components/content-tree](https://modus.trimble.com/components/content-tree/)

Here's how its looking in Modus React Bootstrap:
[deploy-preview-118--modus-react-bootstrap.netlify.app/components/content-tree/#TreewithActions](https://deploy-preview-118--modus-react-bootstrap.netlify.app/components/content-tree/#TreewithActions)

**Comment by ryan-henness-trimble** [comment]
1. Extend `modus-list-item` to include drag icon, tree arrow, checkbox, and left-fixed icon

**Comment by ryan-henness-trimble** [comment]
@enowak1031 
Do we have any specs for what to do when the items aren't show within the given width of the component? I can see a case where deeply nested items would eventually not be shown on the screen

I see that there is a text overflow spec but I don't know if it completely handles this case. I think allowing the component to be scrolled horizontally might be a good approach

**Comment by msankaran0712** [comment]
Preview:
https://icy-ground-0374a1310-637.centralus.1.azurestaticapps.net/?path=/docs/components-content-tree--default

**Comment by Balaji-trimble** [comment]
@msankaran0712 @enowak1031 QA done. Hence this ticket can be closed.
