### ISSUE TITLE
Text-Input: Add HTML5 `pattern` attribute to modus-text-input

### ISSUE THREAD

**Issue by gallelauren816** [trimble-oss/modus-web-components#427]
- Give the ability for a developer to create input validation based of a specific pattern set in the html (i.e. `pattern="[(][0-9]{3}[)] [0-9]{3}-[0-9]{4}"` for a phone number input). 
- There is currently no "pattern" attribute on this component that allows for any type of validation 

REF: https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/pattern

**Comment by msankaran0712** [comment]
@gallelauren816 are you willing to contribute?

**Comment by msankaran0712** [comment]
@msankaran0712 check with @gallelauren816

**Comment by msankaran0712** [comment]
This is to reaffirm that Modus has approved the functionality for development.

cc @gallelauren816 

Note: Modus team assign a `modus-approved` tag to the approved issues

**Comment by cjwinsor** [comment]
@cjwinsor Folllow-up with implementation details

**Comment by cjwinsor** [comment]
Just passthrough the pattern attribute to the input.
