### ISSUE TITLE
[2] Content tree - Implement Barebones Content Tree

### ISSUE THREAD

**Issue by ryan-henness-trimble** [trimble-oss/modus-web-components#459]
# Description

Build a barebones `modus-content`-tree which displays the parent/child items that can be expanded and collapsed on button click. 

This content tree will take a JavaScript object as its input, it will not be composable. 

It will take the object and compose it itself using the modus-list-item component. This should give us better leverage for the Action functionality since we will be able to modify the object and output its changes.

It is important to try to define a good input model for these items that can be extended to fit the needs of all the Actions.

**Comment by msankaran0712** [comment]
Preview:
https://deploy-preview-582--modus-web-components.netlify.app/?path=/story/components-content-tree--default
