### ISSUE TITLE
Modus Modal should have a higher z-index than others

### ISSUE THREAD

**Issue by ryan-henness-trimble** [trimble-oss/modus-web-components#470]
**Describe the bug**
Right now the Modus Modal has a lower z-index than other components, such as the Modus Navbar. Modals should overlay the entire application so we should make sure that the they have the highest z-index of the components.

**Expected behavior**
Modal overlays entire application

**Comment by coliff** [comment]
can this be closed as fixed in #491 ?

**Comment by ryan-henness-trimble** [comment]
Yep good call, think so. Forgot this way here
