### ISSUE TITLE
[BUG] Accordions Expand Icon

### ISSUE THREAD

**Issue by coliff** [trimble-oss/modus-web-components#503]
Go to: https://modus-web-components.trimble.com/?path=/docs/components-accordion--default

The expand icon SVG is not correct. It should be lighter. I think the CSS should be:

```css
background: url(data:image/svg+xml,%3Csvg%20xmlns=%22http://www.w3.org/2000/svg%22%20width=%2226%22%20height=%2216%22%3E%3Cpath%20fill=%22%236a6e79%22%20d=%22M3.5.6l9.7%209.8L22.9.6c.7-.8%202-.7%202.7.0l.1.1c.7.8.7%202%200%202.7L13.2%2016%20.8%203.4C0%202.6.0%201.4.8.6L.9.5c.7-.7%201.9-.7%202.6.1z%22/%3E%3C/svg%3E)no-repeat right .3125rem center/.875rem;
```

**Comment by msankaran0712** [comment]
hey @enowak1031 we can close this bug if you don't have any comments,
preview: https://icy-ground-0374a1310-982.centralus.1.azurestaticapps.net/?path=/docs/components-accordion--default
PR: https://github.com/trimble-oss/modus-web-components/pull/982
