### ISSUE TITLE
Update the React integration Storybook docs

### ISSUE THREAD

**Issue by ryan-henness-trimble** [trimble-oss/modus-web-components#514]
**Describe the solution you'd like**
Now that there are generated NPM packages for the Angular and React implementations, update the Storybook documentation to describe how to use these packages rather than wrapping the components manually.

**Additional context**
There may be hiccups with the generated components that we don't know about yet. This issue is probably best done after some smoke testing of the generated components.

**Comment by msankaran0712** [comment]
@enowak1031 Maybe we can get some help from the extended dev team in India to help us automate the deployment and smoke testing of the components

**Comment by msankaran0712** [comment]
We have https://github.com/trimble-oss/modus-web-components/issues/1157 for Angular so this issue can be used for adding React reference.

**Comment by msankaran0712** [comment]
And moved to the next sprint to be with the React spike https://github.com/trimble-oss/modus-web-components/issues/1051
