### ISSUE TITLE
Show password as Text toggle Input

### ISSUE THREAD

**Issue by ryan-henness-trimble** [trimble-oss/modus-web-components#515]
**Describe the solution you'd like**
There should be a button that allows the user to view a password Text Input as a regular text input. This is useful for users to verify that their value is correct

**Additional context**
It looks like there may be an eye icon that we can use. We will also need the eye icon with a cross through it, indicating the password text is not visible.

**Comment by coliff** [comment]
I made a tiny little library that does this :-)
https://github.com/coliff/bootstrap-show-password-toggle
