### ISSUE TITLE
[BUG] Published packages missing README

### ISSUE THREAD

**Issue by ryan-henness-trimble** [trimble-oss/modus-web-components#551]
**Describe the bug**
The published NPM packages are missing the README file. 

**To Reproduce**
1. Go to https://github.com/trimble-oss/modus-web-components/packages/827579?version=0.1.9
2. See `ERROR: No README data found!`

**Expected behavior**
In the previous versions, like 0.1.5, you can see the README is available

**Additional context**
This probably has to do with moving the directories around. I'm guessing that a path to the README is broken

**Comment by coliff** [comment]
I think we need to include it in the [root of the repo that is published](https://docs.npmjs.com/about-package-readme-files) (i.e. alongside the `package.json`).
We should either:

- a) use a script to copy `README.md` from the repo root to the stencil-workspace folder before publishing to npm. (but add `stencil-workspace/README.md` to .gitignore)

_or_

- b) copy and paste the stencil-workspace and keep it there. Maybe the READNE in the root will diverge from the stencil-workspace one with the root one being a brief overview of the whole repo and the stencil-workspace one being about stuff specific to stencil-workspace / storybook etc.
