### ISSUE TITLE
Pagination Icon

### ISSUE THREAD

**Issue by coliff** [trimble-oss/modus-web-components#568]
Pagination left and right icons are using thick icons.

We should use standard ones.

https://modus-bootstrap.trimble.com/foundations/icons/?q=icons&filter=chevron+right#icons

![image](https://user-images.githubusercontent.com/1212885/178916614-5404af1f-446a-46f9-a3dc-01b813af36e6.png)

**Comment by prashanth-offcl** [comment]
The changes are already merged so closing this issue
