### ISSUE TITLE
Lists Selected Item shouldn't have a tick icon by default

### ISSUE THREAD

**Issue by coliff** [trimble-oss/modus-web-components#575]
RE: https://modus-web-components.trimble.com/?path=/story/components-list--default

![image](https://user-images.githubusercontent.com/1212885/179503502-e6f5f8a4-6a27-4e93-94bb-d9d24cb76646.png)

The Modus guidelines don't specify or suggest that a selected item in a list group should have a checkmark icon.
REF: https://modus.trimble.com/components/lists/

I propose the tick icon should either be removed or make it an option which is off by default.

cc @msankaran0712

**Comment by cjwinsor** [comment]
For accessibility, we need the checkmark to designate the selected list item as selected.

**Comment by coliff** [comment]
Ok, so should we add the checkmark to the styleguide here:
https://modus.trimble.com/components/web/lists/
?
