### ISSUE TITLE
Automate Changelog

### ISSUE THREAD

**Issue by coliff** [trimble-oss/modus-web-components#586]
It'd be great to automate the Release Notes. I think we could not include changes in the CHANGELOG.md and instead have them listed at: https://github.com/trimble-oss/modus-web-components/releases

We can use a GitHub Action:
https://github.com/release-drafter/release-drafter

It's used by Bootstrap looks easy to set up...
https://github.com/twbs/bootstrap/blob/main/.github/workflows/release-notes.yml

**Comment by ryan-henness-trimble** [comment]
Oh hmmm, so this will create a draft release, and continue to update its release notes until we're ready to publish?
