### ISSUE TITLE
Dynamic icons inputs

### ISSUE THREAD

**Issue by ryan-henness-trimble** [trimble-oss/modus-web-components#587]
**Describe the solution you'd like**
Some components require the user to pass in which icon they want to use as a slot. Since they are able to pass any HTML element into the slot that they would like, it may be better to have them pick from our existing icons by passing a string.

This could also be useful for components that have fixed icons but could benefit from dynamic icons.

We would probably want some internal component that will switch out the icons depending on the string passed in.

**Additional context**
For example, instead of this usage
```js
<example-component>
    <svg slot="some-name" />
</example-component>
```

it would be something like this
```js
<example-component icon="some-icon-name" />
```

**Comment by msankaran0712** [comment]
@ryan-henness-trimble is this issue still valid?

**Comment by msankaran0712** [comment]
@ryan-henness-trimble closing the issue as it is not needed anymore, if we are doing #1860
