### ISSUE TITLE
Slider / Range ARIA label issues

### ISSUE THREAD

**Issue by coliff** [trimble-oss/modus-web-components#598]
There are a few a11y issues with Sliders:
https://modus-web-components.trimble.com/?path=/story/components-slider--default

![image](https://user-images.githubusercontent.com/1212885/181207805-222b02ff-e7ca-46ec-8958-4f2cd1656b29.png)

I suggest we remove `aria-valuemax`, `aria-valuemin` and `aria-valuenow` from the wrapping div and add `aria-label` to the input range itself. That will solve all the issues.

**Comment by coliff** [comment]
what do you think about this @ryan-henness-trimble ? I don't know why this component was built this way and if there is a valid reason for having aria attributes on the wrapping div.

**Comment by ryan-henness-trimble** [comment]
would the range input need the `value` arias, or just the `label`?

**Comment by coliff** [comment]
> would the range input need the `value` arias, or just the `label`?

just the label I think.
