### ISSUE TITLE
[BUG] Azure Static Web Apps Deploy Previews for Dependabot (or forks) updates are not working

### ISSUE THREAD

**Issue by coliff** [trimble-oss/modus-web-components#612]
Azure Static Web Apps Deploy Previews for Dependabot updates are not working:

Similar issue: https://github.com/Azure/static-web-apps/issues/788

**To Reproduce**
1. Go to https://github.com/trimble-oss/modus-web-components/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc+author%3Aapp%2Fdependabot
2. see Azure GitHub Action is failing with

**Expected behavior**
It should complete without error

**Screenshots**
![image](https://user-images.githubusercontent.com/1212885/182544793-52836785-112c-4f39-9ae8-8f4df8bbe114.png)

**Comment by ryan-henness-trimble** [comment]
hmm, I'm seeing this in all PRs

**Comment by coliff** [comment]
> hmm, I'm seeing this in all PRs - it may have to do with it being on a forked repo

Yep, I’ll look into this some more. I always make PRs on a branch from the repo (not a fork) and they work fine that way. Honestly, Netlify was much easier :-(

**Comment by ryan-henness-trimble** [comment]
@coliff okay sounds good, let me know what you find!

**Comment by ryan-henness-trimble** [comment]
@coliff have you gotten a change to look into this again? Do we still need the Azure preview if we can preview with Netlify?

**Comment by danielwoodhead** [comment]
Hi, I had this same issue and adding the deployment token as a Dependabot-specific secret fixed it (Settings -> Security -> Secrets -> Dependabot).

**Comment by coliff** [comment]
> Hi, I had this same issue and adding the deployment token as a Dependabot-specific secret fixed it (Settings -> Security -> Secrets -> Dependabot).

awesome tip! thanks! I'll give that a try

**Comment by coliff** [comment]
thanks @danielwoodhead - got it working for Dependabot.

**Comment by msankaran0712** [comment]
@coliff can you please close the issue if it is fixed ?

**Comment by msankaran0712** [comment]
@coliff @enowak1031 should we keep this issue to find an alternative for using Christian's Netlify license?

**Comment by coliff** [comment]
I think this issue should be kept open. It's possible that a contributor could find this issue and know of a fix.

**Comment by coliff** [comment]
We've migrated all Deploy Previews to Netlify now so I can close this.
