### ISSUE TITLE
Automate Builds for separate Angular output versions

### ISSUE THREAD

**Issue by ryan-henness-trimble** [trimble-oss/modus-web-components#614]
**Describe the solution you'd like**
The Angular components are built out for version 13 but could be useful for versions 13+ as well. Figure out how to handle multiple versions.

~We may consider outputting multiple packages with multiple workspaces:~
~`angular-13-workspace` -> `@trimble-oss/modus-angular-13-components`~
~`angular-14-workspace` -> `@trimble-oss/modus-angular-14-components`~
~etc...~

~This way we can keep the package versions in sync with the web components package like~
~`@trimble-oss/modus-angular-13-components@1.0.9`~
~`@trimble-oss/modus-angular-13-components@1.0.9`~

With a microfrontend use case it seems necessary for these framework integration package versions to be parallel with the web components package since the browser will only register the web components once at a single version

> This idea has changed a bit, check the discussion below

---

**Progress**
- [X] Create new branch `output-target/ng13`. This naming convention can be used to add branch protection rules for all output target branches
- [X] Add branch protection for `output-target/*` that match the protection rules of the default `main` branch
- [X] Upgrade `main`'s Angular output to Angular 14 - [Completed](https://github.com/trimble-oss/modus-web-components/pull/626/files)
- [X] Update `main`'s Angular package config to include the pre-release flag: `@trimble-oss/modus-angular-components@0.1.11-1411` - [Completed](https://github.com/trimble-oss/modus-web-components/pull/626/files)
- [x] Release `@trimble-oss/modus-angular-components@0.1.11-1411`
- [ ] Update `output-target/ng13` to include the pre-release flag: `@trimble-oss/modus-angular-components@0.1.11-1330`
- [ ] Release `@trimble-oss/modus-angular-components@0.1.11-1330`
- [ ] Update docs explaining the branching definitions

---

**Questions**
- How should we structure the GitHub actions?

**Comment by leohaughton** [comment]
This seems reasonable to me. My only (minor) issue with it is that the number of directories will increase as the versions of Angular and React increase.

Is there a possibility of managing this through branches?

main - always has the latest React and Angular integration
ng13 - contains the angular 13 components
react18 - contains the react 18 components

Package version naming convention could still be as you have proposed above, or it could be something like:

@trimble-oss/modus-angular-components@1.0.9-1301
Where the pre-release flag indicates the version of angular it is running?

What are your thoughts @ryan-henness-trimble ?

**Comment by ryan-henness-trimble** [comment]
Both of those ideas seem like the best way to go about this. Managing versions through branches and using the pre-release flag seem like it would keep things clean and descriptive. I'm not familiar with the best git practices for this type of thing but it seems like the workflow may look something like this:
1) Make a change to `stencil-workspace` in `main`
2) `npm run build` from `stencil-workspace` in `main`
3) Commit the changes and generated files to `main`
4) Merge `main` into `ng13` (and other version specific branches)
5) Resolve conflicts by keeping modified versions of files on `ng13`
6) `npm run build` from `stencil-workspace` in `ng13`
7) Commit the generated files to `ng13`

That would leave us with a structure like this:
```
        main/
	  + Latest Web Components package config
	  	--> @trimble-oss/modus-web-components@0.1.10
  	  + Latest React package config
	  	--> @trimble-oss/modus-react-components@0.1.10-1702
  	  + Latest Angular package config
	  	--> @trimble-oss/modus-angular-components@0.1.10-1410
	
	ng13/
	  + Latest Web Components package config
	  + Latest React package config
	  + Angular v13.3.0 package config
	  	--> @trimble-oss/modus-angular-components@0.1.10-1330
```

I'll dig a bit more into this @leohaughton

**Comment by msankaran0712** [comment]
Check again in Sprint 63

**Comment by coliff** [comment]
Update: We now have a build process for Angular 14 and 15... next week we'll look to add Angular 16.
I'm currently working on a GitHub Action to automate the publishing of it.
