### ISSUE TITLE
Contributors list on website

### ISSUE THREAD

**Issue by coliff** [trimble-oss/modus-web-components#651]
currently there is a list of contributors on homepage: https://modus-web-components.trimble.com/?path=/story/introduction-welcome--page

I propose we remove that list and instead, have something like:

Thanks to all of our contributors! (with a link to):
https://github.com/trimble-oss/modus-web-components/graphs/contributors

If we want to keep list of contributors then we should add @msankaran0712 - but I'd prefer to remove that list altogether rather than manually maintain it.

**Comment by ryan-henness-trimble** [comment]
Yea I think that is a good idea, might as well link to something we don't have to maintain ourselves!

This seems like a fun idea as well https://allcontributors.org/docs/en/overview

**Comment by msankaran0712** [comment]
> yeah - that's better! ![image](https://user-images.githubusercontent.com/1212885/185342979-067f43c6-0651-433c-a9e1-7f2424dbafa4.png)

I vote for this one

**Comment by ryan-henness-trimble** [comment]
I like it!

We should keep in mind the allcontributors project too. The current contributors page is missing people that help out with PRs

**Comment by coliff** [comment]
> I like it!
> 
> We should keep in mind the allcontributors project too. The current contributors page is missing people that help out with PRs

cool - ok. I requested access to add it via: https://allcontributors.org/docs/en/bot/installation
I think Jeff has to approve app installations. hopefully it'll be available soon. sounds easy and fun to work with! https://allcontributors.org/
