### ISSUE TITLE
Add more Modus icons for the Icon Map

### ISSUE THREAD

**Issue by ryan-henness-trimble** [trimble-oss/modus-web-components#676]
**Describe the solution you'd like**
We now have an icon map that allows the consumer to pass in a string to a component to define which icon they'd like to use. We should bring in more of the icons as functional components so there is a bigger set to choose from.

https://modus-icons-test.netlify.app/common-solid/

**Additional context**
We should update the docs to explain how to find the values for the icon names.

**Comment by msankaran0712** [comment]
@ryan-henness-trimble I think we can handle this in https://github.com/trimble-oss/modus-web-components/issues/1098. 
should we close this one ?

**Comment by msankaran0712** [comment]
@ryan-henness-trimble Closing this issue for now. Please feel free to reopen if it is not resolved.
