### ISSUE TITLE
Modus Data Table - Sticky headers & scrolling

### ISSUE THREAD

**Issue by ryan-henness-trimble** [trimble-oss/modus-web-components#684]
**Describe the solution you'd like**
The Data Table should have the option to include sticky headers when the table body is being scrolled

**Comment by aknoll-transporeon** [comment]
Are there any updates on this?
Having a sticky header is a requirement for Taskflow too.
We would even be happy with a workaround until the new table drops

**Comment by msankaran0712** [comment]
Hey @aknoll-transporeon, we will release the new Table with scrolling in August, and the `Modus Data Table` is marked for deprecation. Hence we are not planning to fix bugs/add features to it. 

Would you be interested in contributing a fix?

**Comment by aknoll-transporeon** [comment]
Does the new table support sticky headers (and columns, footer)?

**Comment by msankaran0712** [comment]
Yes @aknoll-transporeon, the new Table has sticky headers. Below is the rough status of the new Table Component,

Completed,

- Sorting
- Pagination
- Column Reordering
- Column Resizing
- Hide/Show Columns
- Footer Row

In Progress (https://github.com/trimble-oss/modus-web-components/pulls?q=is%3Aopen+is%3Apr+label%3Atable),

- Expandable Rows
- Scrollable Table with sticky header and footer

Planned,

- Editable Cells
- HyperLink in Cells
- Row Selection using row click and checkbox
- Filtering Columns
- Save Table Preferences
