### ISSUE TITLE
Add standard events to Input/Select components

### ISSUE THREAD

**Issue by ryan-henness-trimble** [trimble-oss/modus-web-components#73]
Add standard events to Input and Select components.

Some standard events already work with the Modus components, so they will need to be checked before implementation.

The events that the components should support are:
- onclick
- onfocus
- onblur

**Comment by msankaran0712** [comment]
@ryan-henness-trimble we can close the issue if it is not needed anymore

**Comment by prashanth-offcl** [comment]
Closing this issue as the mentioned events are already handled.
