### ISSUE TITLE
Modus Table - Inline Editing using Mouse Interactions

### ISSUE THREAD

**Issue by ryan-henness-trimble** [trimble-oss/modus-web-components#742]
The Modus Data Table should support inline cell editing with text inputs. Dig deeper into the requirements when taking on this issue

**Comment by msankaran0712** [comment]
hey @Hulsegge Apologies for the delayed response, we are trying to release the Inline editing this week.

**Comment by prashanth-offcl** [comment]
The changes are already merged so closing this issue
