### ISSUE TITLE
Standardize icon component sizes

### ISSUE THREAD

**Issue by gabriel-piltzer-trimble** [trimble-oss/modus-web-components#75]
Create a shared const for the icon components DEFAULT_SIZE (probably 16).

Reference this instead of hard coded sizes in each icon component.

Check if any other components using the icons are setting the size to 16, if so, remove that code.

**Comment by msankaran0712** [comment]
cc @ryan-henness-trimble 

This won't be required anymore as we plan to add support for all the Modus Icons and keeping a typescript file for each icon is not an ideal method.
