### ISSUE TITLE
Add Animation Code

### ISSUE THREAD

**Issue by gabriel-piltzer-trimble** [trimble-oss/modus-web-components#76]
We skipped adding animations as we built components for multiple reasons. One being, finding the Modus specs for them is really difficult. The other is that it's time consuming. Create a list of components that require animations along with the animation specs.

**Comment by msankaran0712** [comment]
hey, @coliff does this issue sound familiar to you?

**Comment by coliff** [comment]
yes, I think we'll add animation CSS with the specs/guidance from the Tiger Team. I'm fine if you close this issue - we can/will add new specific ones once decided exactly what needs to be done.
