### ISSUE TITLE
Create separate README files for each output

### ISSUE THREAD

**Issue by ryan-henness-trimble** [trimble-oss/modus-web-components#786]
We should have a root README for the project as well as READMEs for the individual outputs

This work will include removing the 'copy files' logic to get the root README into the Stencil workspace

**Comment by coliff** [comment]
We can't run `npm i` from the stencil-workspace directory now beacuse it expects a README.md and a SUPPORT.md to be there. I think we should remove SUPPORT.md from the files array (not need in an npm package) and add the README.md.
