### ISSUE TITLE
Dark Mode - Modus root variables

### ISSUE THREAD

**Issue by ryan-henness-trimble** [trimble-oss/modus-web-components#788]
Add the root color variables to the `modus-colors.scss`. 

Eventually these variables will replace the colors we currently have in the stylesheet. We should not remove the current variables until they are no longer in use - when adding these new root colors, we should prepend or append them with text that indicates that they are the new values. Once we've got all of our component switched over to these new root values, we can remove the old ones and get rid of the prepended/appended text on the variable names

**Comment by coliff** [comment]
This is taken care with other issues/PRs already so we can close this.
