### ISSUE TITLE
Dark Mode - Accordion

### ISSUE THREAD

**Issue by ryan-henness-trimble** [trimble-oss/modus-web-components#789]
This issue depends on #788 being completed

Implement the root variables in the Accordion and Card components. Component-specific colors should be scoped to their own stylesheets.

The components should switch their theme depending on a global site variable, and be able to be overridden by a data attribute `data-mwc-theme` or `data-modus-theme`

**Comment by msankaran0712** [comment]
Moved Card to #797

**Comment by msankaran0712** [comment]
components changed and merged with `dev/msankaran/dark-mode-main`
