### ISSUE TITLE
Date & Time Picker in Web Components

### ISSUE THREAD

**Issue by enowak1031** [trimble-oss/modus-web-components#821]
- [x] #972
- [x] #977
- [ ] #978
- [ ] #973

**Comment by msankaran0712** [comment]
@enowak1031 This needs to be broken down into more minor issues, but I need to start working on this to get a clear idea of how it can be divided.
Also increased the story points to 8.

**Comment by enowak1031** [comment]
@msankaran0712 Should we delete this issue?
