### ISSUE TITLE
File Dropzone: Add support for `disabled` state

### ISSUE THREAD

**Issue by msankaran0712** [trimble-oss/modus-web-components#847]
Currently, there is no property to set a disabled state for the component.

**Comment by msankaran0712** [comment]
Maha to check @enowak1031 and close the issue if none needs it.

**Comment by prashanth-offcl** [comment]
Refer [Figma link](https://www.figma.com/design/wyfVJUHWRMkeCfdB38HFEE/Modus---Web?node-id=5762-22364&node-type=CANVAS&t=pMyYyKERZV4vEe7R-0) for the disabled state.
