### ISSUE TITLE
File Upload Dropzone - Not able to reset error state

### ISSUE THREAD

**Issue by msankaran0712** [trimble-oss/modus-web-components#851]
Once an error state is achieved looks like there is no way to attempt the upload again, trying to drop a valid file is not clearing the error message.

1. Go to [File upload drop zone](https://modus-web-components.trimble.com/?path=/docs/components-file-dropzone--default)
2. Upload multiple files and appears an error message
3. Attempt upload again with a valid file, the error message doesn't go away, and the file used in the upload is opening in the browser.

**Expected behavior**
The error message should be cleared when the upload is valid.

![chrome_ZwIPPkwfE2](https://user-images.githubusercontent.com/50131391/201022056-99f55c4d-e594-4504-a7f6-9fcd64bd4a13.gif)

**Comment by cjwinsor** [comment]
@enowak1031 @egunther39 Can we refine the requirements on the interactions? Do we allow for user to clear error message? I assume it should allow drop regardless.

**Comment by prashanth-offcl** [comment]
The expected behavior is to reset to the initial state of the component on clicking the reset button.
