### ISSUE TITLE
Incorrect blue in primary badges

### ISSUE THREAD

**Issue by soniakaukonen** [trimble-oss/modus-web-components#871]
The Figma and XD kit has the Primary blue `#0063A3` and the web component uses blue dark `#0E416C` for primary badges. Please fix web components. /found by Aruna Ch.

**Comment by msankaran0712** [comment]
hey @soniakaukonen, looks like web components badges have Primary blue `#0063A3`. Please verify again.

**Comment by msankaran0712** [comment]
As discussed with @soniakaukonen this bug isn't there anymore.
