### ISSUE TITLE
Navbar responsiveness

### ISSUE THREAD

**Issue by gabriel-piltzer-trimble** [trimble-oss/modus-web-components#89]
The navbar needs to conform to the responsive breakpoints in the Modus documentation. This includes things like font-size, spacing (margin and padding), icon sizes, etc.

**Comment by enowak1031** [comment]
@coliff and @msankaran0712 Do we have this covered yet in other issues?

**Comment by msankaran0712** [comment]
hey @enowak1031 I don't think this is covered in any other issue. Please correct me if am wrong @ryan-henness-trimble @coliff

**Comment by msankaran0712** [comment]
@coliff, I am closing this issue as we now have the logo responsive. We can reopen it if you think anything is missing.
