### ISSUE TITLE
Add Sonar Scan GitHub Action

### ISSUE THREAD

**Issue by coliff** [trimble-oss/modus-web-components#963]
We have this setup already on the other Modus projects e.g. https://github.com/trimble-oss/website-modus-bootstrap.trimble.com/blob/main/.github/workflows/sonar-scan.yml

Adding the GitHub Action workflow is easy, but I'm not sure how to add this project to: https://sonar.trimble.tools/projects

**Comment by msankaran0712** [comment]
Yes, I can help you with this, hope if it's okay to do it tomorrow.
