### ISSUE TITLE
Add Dark/Light Mode Switch to Navbar Component

### ISSUE THREAD

**Issue by enowak1031** [trimble-oss/modus-web-components#970]
Make optional in the navbar.

**Comment by enowak1031** [comment]
Do we need to include it in the documentation and add it to React as well?

**Comment by ryan-henness-trimble** [comment]
Yea, this change will be reflected in the Storybook docs for the Web Components once it's completed. 
I think it would make sense to add it to the React components as well

**Comment by coliff** [comment]
We closed this feature as not planned. Web apps would likely have the dark mode toggle in a preferences panel or in sidebar or footer... but not in the navbar.

**Comment by ryan-henness-trimble** [comment]
We've got the use case for the toggle being in the Navbar in our Work Center project

**Comment by coliff** [comment]
> We've got the use case for the toggle being in the Navbar in our Work Center project

ah sorry about that. We don't plan to add official guidance about the design/functionality of a dark mode toggle in navbars to the Modus styleguide, but we have all agreed we like the implementation we use on the Modus styleguide itself so I think that should be a useful guide for the design/functionlity if it will be added to MWC

**Comment by msankaran0712** [comment]
@ryan-henness-trimble did any team request for this feature? if not, we should close it and handle it when a request comes. @enowak1031 thoughts?

**Comment by ryan-henness-trimble** [comment]
my team would benefit from it

**Comment by ryan-henness-trimble** [comment]
This should be closed upon: https://github.com/trimble-oss/modus-web-components/pull/1341

**Comment by msankaran0712** [comment]
@ryan-henness-trimble Navbar now has the ability to generate any icon button, hence closing the issue. 
https://modus-web-components.trimble.com/?path=/docs/components-navbar--default

**Comment by msankaran0712** [comment]
@ryan-henness-trimble Navbar now has the ability to generate any icon button, hence closing the issue. 
https://modus-web-components.trimble.com/?path=/docs/components-navbar--default
